.clang-format

The clang-format tool can use the coding style defined in .clang-format
Refer to https://clang.llvm.org/docs/ClangFormatStyleOptions.html for more options

Added .clang-format

---

docs/howto/how_to_add_a_gps_receiver.md

Thanks for providing great open source resource.
* Added inline code highlights
* Removed period in summary, since they are not complete sentences
* Fixed typo and changed wording in introduction

Document improvements

---

modules/hmi/utils/hmi_status_helper.py
modules/hmi/web/config.py
modules/hmi/web/handlers.py
modules/hmi/web/hardware_api.py
modules/hmi/web/hmi_main.py
modules/hmi/web/module_api.py
modules/hmi/web/ros_service_api.py
modules/hmi/web/runtime_status.py
modules/hmi/web/runtime_status_api.py
modules/hmi/web/system_cmd.py
modules/hmi/web/tool_api.py
modules/tools/control_info/control_info.py
modules/tools/diagnostics/Message.py
modules/tools/diagnostics/diagnostics.py
modules/tools/dump_rosbag/dumpbag.py
modules/tools/planning_traj_plot/main.py
modules/tools/realtime_plot/item.py
modules/tools/realtime_plot/realtime_plot.py
modules/tools/realtime_plot/stitem.py
modules/tools/realtime_plot/xyitem.py
modules/tools/record_play/rtk_player.py
modules/tools/record_play/rtk_recorder.py

The diff is generated with this command: yapf -i --style='{based_on_style: google}' --recursive modules

format python code to google style with yapf

---

apollo.sh

add a message reminding developers that apollo is continuing building after the message about warning on ESD CAN.

add message for starting building after warning on ESD CAN

---

CONTRIBUTING.md

GitHub only takes CONTRIBUTING.md as the contributing guidelines

moved how_to_contribute_code.md to CONTRIBUTING.md

---

README.md

Forget to change the link? :)
Fix the nit.

Fix the how to contribute link

---

apollo.sh

After test, this setting does not affect the compiling time.
related with issue #75

limit the bazel compile resource by set --jobs=10

---

scripts/apollo_base.sh

replace `date %s%N/1000000` to `date %s`.
In some system, the date command does not support %N

Only get second-level time accuracy by the date command

---

docker/dev.dockerfile

We may get core dumps in data/core/ and need gdb to debug it in dev docker container.

Add gdb to dev docker.

---

WORKSPACE.in

The latest master revision does not work.
This fixed Issue #166

use a working revision of boringssl

---

modules/common/math/math_utils.cc
modules/common/math/math_utils.h
modules/common/math/math_utils_test.cc
modules/control/common/trajectory_analyzer.cc

change double_compare to DoubleCompare in common/math/math_utils.cc

fix a coding style

---

modules/common/math/kalman_filter.h

Add a setter to the state covariance matrix P in kalman filter. This will be used in prediction module which is still in developing.

add a setter for state covariance in kalman filter for future use

---

scripts/apollo_base.sh

apollo.sh source "scripts/apollo_base.sh" which causes function name conflict.  When running "./apollo.sh" without any parameter,  it will call the function "print_usage" defined in "apollo_base.sh".

Fix function name conflict in apollo.sh and scripts/apollo_base.sh

---

modules/control/proto/control_cmd.proto

Fixing comment for clarity - in practice the steering rate is always 100.0 (set with a command line flag in the lateral controller), and it cannot be in [-100.0, 0.0).

Fixing description of steering rate.

---

modules/drivers/gnss/CMakeLists.txt

Fix can not generate the parser_cli to parse the modules/drivers/gnss/test_data/novatel.bin

can not generate the parser_cli

---

modules/hmi/web/handlers.py
modules/tools/py27_requirements.txt

To our knowledge, new version of python, such as 2.7.13, doesn' work well with eventlet 0.21.
See https://github.com/eventlet/eventlet/issues/428

HMI: Migrate to gevent from eventlet which has a known fatal bug.

---

modules/drivers/canbus/can_comm/can_receiver.h
modules/drivers/canbus/can_comm/message_manager.h
modules/drivers/canbus/can_comm/message_manager_test.cc
modules/drivers/canbus/can_comm/protocol_data.h
modules/drivers/delphi_esr/delphi_esr_canbus.h
modules/drivers/delphi_esr/delphi_esr_message_manager.h
modules/drivers/delphi_esr/delphi_esr_message_manager_test.cc

two versions of Parse() in message_manager and protocol_data (with and without timestamp) seem to be identical; merging into one without timestamp

remove timestamp in message_manager and protocol_data

---

scripts/record_bag.sh

1. The default behavior doesn't change.
2. We'll test the IO performance of recording to portable disk.

Scripts: Auto-find largest portable disk to store bag.

---

docs/specs/qp_spline_path_optimizer.md

Either I am completely mistaken and understand nothing, or the matrix always has the size (n+1)x(n+1) when representing the derivative of nth order polynom.

Fix matrix size in the notice

---

apollo.sh

this option cannot use on px2 platform

build: only use -maxv2 gcc build option on X86 platforms

---

modules/planning/tasks/traffic_decider/reference_line_end.cc

when reference line is not enough.

planning: added minimum reference line remain distance to enforce stop

---

modules/map/pnc_map/pnc_map.cc
modules/map/pnc_map/pnc_map.h
modules/map/pnc_map/pnc_map_test.cc
modules/map/pnc_map/route_segments.cc
modules/planning/common/frame.cc
modules/planning/common/frame.h
modules/planning/testdata/sunnyvale_loop_test/result_change_lane_0.pb.txt

* when there are repeated routing lanes, the vehicle may stop
when it near the destination location. With PncMap tracking the adc's
driving progress, we can distinguish whether we should stop based on
if this destination is the last stop.

planning: avoid creating destination obstacle if only pass by

---

apollo.sh
scripts/apollo_base.sh
third_party/local_integ.BUILD

"apollo.sh release" will create a directory ~/.cache/apollo_release, which maps to the root path "/" in release image.
So all apollo binaries, conf and data go to ~/.cache/apollo_release/apollo/
All system libs, such as /usr/local/A go to ~/.cache/apollo_release/usr/local/A
The simply copy "~/.cache/apollo_release" to "/" when making release image, everything will be just right.

Docker: Add necessary system libs when making release image.

---

modules/canbus/common/canbus_gflags.cc

Due to the time is micros,so and it multiply 1000,so it should be ms.
```
void Canbus::OnControlCommand(const ControlCommand &control_command) {
int64_t current_timestamp =
apollo::common::time::AsInt64<common::time::micros>(Clock::Now());
// if command coming too soon, just ignore it.
if (current_timestamp - last_timestamp_ < FLAGS_min_cmd_interval * 1000) {
ADEBUG << "Control command comes too soon. Ignore.\n Required "
"FLAGS_min_cmd_interval["
<< FLAGS_min_cmd_interval << "], actual time interval["
<< current_timestamp - last_timestamp_ << "].";
return;
}
```

Update canbus_gflags.cc bug :fix "us" to "ms"

---

scripts/deploy_local_sanity_check.sh

Sanity check is a part of Early Warning System that Qt project used.
It checks coding style, commit message style and etc.
More details on http://wiki.qt.io/Early_Warning_System
This is not enabled by default, but you can try it with manually installation:
To install, run the script under Apollo source root dir:
$./scripts/deploy_local_sanity_check.sh
then when you modify, commit, it will check your changes and gives you feedback if you not following the coding/commit rules. :-)  (rules may need to be adjusted.)
To remove, run:
$scripts/deploy_local_sanity_check.sh -u

scritps: add a script to deploy sanity check tool

---

modules/drivers/velodyne/velodyne/launch/export_pcd_online.launch
modules/drivers/velodyne/velodyne/launch/export_pcd_online_16.launch
modules/drivers/velodyne/velodyne/launch/start_velodyne.launch
modules/drivers/velodyne/velodyne/launch/start_velodyne_16.launch
modules/drivers/velodyne/velodyne/launch/start_velodyne_bj.launch

Move extrinsics_broadcaster to  /apollo/modules/tools/

remove extrinsics_broadcaster from velodyne

---

docker/scripts/dev_start.sh

When -C option is used,  the repository name which pulled from local docker registry mirror is "registry.docker-cn.com/apolloauto/apollo",
So this is need to be passed to "docker run" instead of using default repo("apolloauto/apollo")
to start docker container from the right image.
~~~
$docker image ls
REPOSITORY                                 TAG                        IMAGE ID            CREATED             SIZE
registry.docker-cn.com/apolloauto/apollo   dev-x86_64-20171229_0957   532e2c8a3925        36 hours ago        11.8GB
registry.docker-cn.com/apolloauto/apollo   dev-x86_64-v2.0.0          532e2c8a3925        36 hours ago        11.8GB
apolloauto/apollo                          dev-x86_64-20171223_1501   e18241c37e87        7 days ago          11.8GB …

scripts: fix docker repo when -C option is used

---

modules/map/hdmap/hdmap_common.cc
modules/prediction/container/obstacles/BUILD
modules/prediction/container/obstacles/obstacle.cc
modules/prediction/container/obstacles/obstacle.h
modules/prediction/container/obstacles/obstacle_clusters.cc
modules/prediction/container/obstacles/obstacle_clusters.h
modules/prediction/container/obstacles/obstacles_container.cc
modules/prediction/container/obstacles/obstacles_container.h

Prediction: add obstacle clusters, to keep lane graph info to avoid redundant computing

---

modules/planning/tasks/dp_poly_path/dp_road_graph.cc

Though it won't happen according to our conf.

Planning: Fix size type to avoid infinite loop when vector size > 256.

---

docs/FAQs/Software_FAQs.md

adding a solution to 'Ubuntu 14.04 login loop problem after installing the pre-built Apollo kernel'

adding a solution to 'Ubuntu 14.04 login loop problem after installing the pre-built Apollo kernel'

---

modules/common/time/time.h

- static_assert failure on underlying type check of std::chrono::nanoseconds
- The only requirement of std::chrono::nanoseconds is that it is an integral type of at least 64bits. Different implementations may have different underlying types. Ther
efore it is better to check whether its size is greater than or equal to sizeof(int64_t).

issue #2702 (static_assert failure)

---

modules/common/adapters/adapter.h
modules/common/adapters/adapter_manager.h
modules/common/adapters/adapter_test.cc
modules/perception/traffic_light/base/image.cc
modules/perception/traffic_light/base/image.h
modules/perception/traffic_light/onboard/tl_preprocessor_subnode.cc
modules/perception/traffic_light/onboard/tl_preprocessor_subnode.h
modules/perception/traffic_light/visualizer/tl_visualizer.cc
modules/planning/tasks/st_graph/st_boundary_mapper.cc
modules/planning/tasks/traffic_decider/keep_clear.cc

From previous profiling, it takes a considerable amount of time in Adapter::EnqueueData, which involves copying data over to the queue.

Reduce Adapter memory footprint

---

modules/tools/calibration/result2pb.py

Which would cause indexError exception in this case. Also, simply
the file I/O via with statement.

result2pb: fix the wrong number of arguments check-ups (#2945)

---

modules/common/data/gem_config.pb.txt

Prior to this commit the gem configs were just placeholders. This commit adds the correct values for the GEM configs.

Add defined gem configs

---

modules/canbus/tools/teleop.cc
modules/canbus/vehicle/gem/gem_controller.cc
modules/canbus/vehicle/gem/protocol/steering_cmd_6d.cc

Prior to this commit there were some incorrect scaling values, as well as some assuptions about payload sizes that prevented the gem from fully working. This commit fixes those issues.

[Canbus] Resolving GEM issues. 

---

modules/canbus/vehicle/gem/protocol/turn_cmd_63.cc

Prior to this commit there was a bug in the turn signal reset command. This commit fixes that issue.

Fix bug in turn signal command reset

---

modules/map/relative_map/navigation_lane.cc

I create a condition here that sets the "last_project_index_" to 0, should the vehicle reach the end point of a cyclic/circular route. For cyclic/circular navigation lines where the distance between their starting and end points are very small, it is tedious and unnecessary to re-send navigation lines every time.

Relative_map: eliminate the need for re-seding navigation lines on circular roads

---

modules/common/util/util.h
modules/dreamview/backend/hmi/hmi.cc
modules/monitor/monitor.cc
modules/planning/common/indexed_queue_test.cc

The helper function "std::make_unique()" is defined since C++14. 
The definition of "std::make_unique()" borrowed from C++14 is given here so that it can be used in C++11.

Common: borrow the "std::make_unique" definition from C++14 so that it can be used both for single objects and arrays of unknown bound in C++11.

---

modules/planning/planning.cc
modules/planning/reference_line/smoother_util.cc

Prefer "std::make_unique" to direct use of "new".
Compared to direct use of new, make functions eliminate source code duplication,
provides cleaner, concise codes, improve exception safety.
Reference "https://herbsutter.com/gotw/_102/" for details.

Planning: replace "std::unique_ptr<T>(new T(...))" with "std::make_unique<T>(...)".

---

modules/planning/integration_tests/planning_test_base.cc
modules/planning/planner/em/em_planner.cc

FLAGS_enable_trajectory_check is temporarily disabled, otherwise EMPlanner and LatticePlanner can't pass the unit test.

Planning: fixed a bug for validating trajectories in EMPlanner.

---

scripts/apollo_base.sh
scripts/record_bag.sh
scripts/record_bag_local.sh
scripts/record_bag_navigation_perception.sh
scripts/record_bag_pnc.sh
scripts/record_bag_sensor.sh
scripts/record_map_data.sh

if we record a log of bags,then it would be very confused what the env is 
By this,every bag would have a log with it .
the log would contain date,branch,newest commit id , git diff and git diff --staged.

scritps: write log to a file about the env when record bag

---

README.md
README_cn.md
docs/howto/how_to_build_and_release.md

如果build后面不加参数,build的时候会非常卡,尤其是在机械硬盘上运行更加明显.加入参数后不仅卡顿得到优化,合理的参数编译速度也有所提升,目前已在公司多台电脑验证.
第二个参数为CPU个数,开启编译的进程为该值的2倍,但进程数不会超过5个(任务限制),经研究该数值在1.0到2.0比较合理(不同的电脑配置会有一些区别)

optimized compilation

---

docker/scripts/dev_start.sh

Starting the Docker container fails when the user starting the process is a 
member of multiple groups, as the space separated list of groups is passed 
unquoted to the docker command, which breaks the command. This is fixed 
by quoting the group parameter.
Fixes #4366

Fix startup script for users with multiple groups

---

modules/map/pnc_map/path.cc
modules/map/pnc_map/path.h
modules/map/pnc_map/path_test.cc

In the original implementation, `explicit Path(std::vector<MapPathPoint> path_points)` always creates a temporary vector, even if you use a `std::move()` function in its constructor to move this temporary object. 
For example, in the following code:
```cpp
std::vector<MapPathPoint> points{
MapPathPoint({0, 0}, M_PI_2, LaneWaypoint(lane_info, 0)),
MapPathPoint({0, 1}, M_PI_2, LaneWaypoint(lane_info, 1)),
MapPathPoint({0, 2}, M_PI_2, LaneWaypoint(lane_info, 2)),
MapPathPoint({0, 3}, M_PI_2, LaneWaypoint(lane_info, 3))};
const Path path(points, {}, 2.0);
```
`path(points, {}, 2.0)` always generates a temporary vector for `points`.
If you use a move constructor `explicit Path(std::vector<MapPathPoint>&& path_points)`, `path(std::move(points), {}, 2.0)` will only move the vector instead of …

Map: modified constructors for the class "Path" in PncMap.

---

modules/monitor/hardware/gps/gps_monitor.cc

Monitor: Extend acceptable_gnss_best_pose_unstable_duration to 120s.

---

modules/map/relative_map/tools/BUILD
modules/map/relative_map/tools/navigator.cc
scripts/navigator.sh

Usage:
Example 1:
```bash
bash scripts/navigator.sh modules/tools/navigator/path_csc_left.bag.txt.smoothed  modules/tools/navigator/path_csc_right.bag.txt.smoothed
```
or
```bash
cd /apollo/modules/tools/navigator/
bash /apollo/scripts/navigator.sh path_csc_left.bag.txt.smoothed  path_csc_right.bag.txt.smoothed
```
Example 2:
```bash
bash scripts/navigator.sh data/bag/csc/path_csc_left.bag.txt.smoothed  data/bag/csc/path_csc_right.bag.txt.smoothed
```
or
```bash
cd /apollo/data/bag/csc
bash /apollo/scripts/navigator.sh path_csc_left.bag.txt.smoothed  path_csc_right.bag.txt.smoothed
```

Map: added a C++ version for the navigation line sender.

---

modules/control/control_test.cc

death test often generates core files

control: remove death test

---

docker/scripts/dev_start.sh

Manipulate map data containers after apollo_dev is removed, if not,
the associated volume will not be automatically deleted(--rm) since
it's still in use, and it will become in dangling state once
apollo_dev is removed (not with -v).

scripts: fix docker data volume leak

---

modules/map/relative_map/common/relative_map_gflags.cc
modules/map/relative_map/common/relative_map_gflags.h
modules/map/relative_map/tools/navigator.cc
scripts/navigator.sh

Apollo 3.0 uses a new smoothing algorithm to generate the navigation path, which makes the number of points in the navigation path very large. It may cause the ROS buffer to overflow and thus result in the navigation path not being sent successfully. Using a down sampling strategy can effectively solve this problem.
Instructions:
1. Do not use downsampling
```
  bash /apollo/scripts/navigator.sh left.smoothed right.smoothed --navigator_down_sample=0
```
2. Use downsampling
```
  bash /apollo/scripts/navigator.sh left.smoothed right.smoothed --navigator_down_sample=1
```
or
```
  bash /apollo/scripts/navigator.sh left.smoothed right.smoothed
```

RelativeMap: down sampled raw navigation path data.

---

modules/planning/tasks/st_graph/st_boundary_mapper.cc

FYI:  *top 5 most common logs in plannning*
102128 st_boundary_mapper.cc:136] No mapping for decision: ignore {
39561 dp_st_speed_optimizer.cc:163] Mapping obstacle for dp st speed optimizer failed.
39560 em_planner.cc:462] Slowing down the car with polynomial.
39560 em_planner.cc:194] Failed to run tasks[DpStSpeedOptimizer], Error message: Mapping obstacle for dp st speed optimizer failed.

planning: remove the most common unnecessary log.

---

modules/common/monitor_log/monitor_log_buffer_test.cc

The core dump settings of the system will not be affected.

test: remove core file in death tests

---

modules/localization/msf/common/util/extract_ground_plane.h

Since it haven't check whether inlier_idx is exceed the size of inliners .It will cause segmentation fault in some time.

[Localization] Fix bug in extract_ground_plane

---

apollo.sh

apollo.sh build told wrong message, even with build_cpu option,
the script always tell: "Running build under GPU mode". This patch
fixed this problem and added USE_GPU="1" for all options where
have --define USE_GPU=true set in the build command.

All: Fix bug when testing USE_GPU flag in apollo.sh.

---

modules/guardian/guardian.cc

It is reasonable to make the steering angle to zero in a low steering speed.

guardian:set steering rate to 25% in safety mode

---

modules/tools/map_gen/map_gen.py

Lacking f.close after called open in the old code, though this is
not mandatory, use with statement is better.

Tools/map_gen: Use with statement to open file.

---

modules/localization/README.md

Fix typo 'Localizaiton' to 'Localization'

Localization: Fix typo in README.md

---

modules/planning/navi_planning.cc
modules/planning/navi_planning.h

This PR is for fixing a crash when launching a navigation planner. Currently, the navi planner does not initialize thread pool. This PR fixes this crash. Please check the log message and call stack below:
```
F1018 14:26:15.044888 24254 thread_pool.cc:36] Check failed: 'instance()->pool_.get()' Must be non NULL 
*** Check failure stack trace: ***
@     0x7ffff12d9ec0  google::LogMessage::Fail()
@     0x7ffff12d9e07  google::LogMessage::SendToLog()
@     0x7ffff12d97de  google::LogMessage::Flush()
@     0x7ffff12dc83b  google::LogMessageFatal::~LogMessageFatal()
@           0x5f132a  google::CheckNotNull<>()
@           0x5ef952  apollo::common::util::ThreadPool::pool()
@           0x4bd590  apollo::planning::DpRoadGraph::GenerateMinCostPath()
@           0x4bcb07 …
```

Planning: fix thread pool crash in navi planner

---

modules/tools/configurator/configurator.py
modules/tools/prediction/mlp_train/common/feature_io.py
modules/tools/prediction/multiple_gpu_estimator/counting.py
modules/tools/prediction/multiple_gpu_estimator/mlp_utils.py

1. modules/tools/configurator/configurator.py: use xrange from six to keep the compatible between Python2.x/3.x
2. modules/tools/prediction/multiple_gpu_estimator/counting.py: os module is unused, don't need to import.
3. modules/tools/prediction/multiple_gpu_estimator/mlp_utils.py: s/== None/is None/
4. modules/tools/prediction/mlp_train/common/feature_io.py: remove close() operation since we use with statement for file IO.

4 Fixes on the tools under modules/tools/prediction and modules/tools/configurator

---

modules/perception/obstacle/camera/lane_post_process/cc_lane_post_processor/cc_lane_post_processor.cc

This pull request is to fix the possible endless loop in cc_lane_post_processor.cc. In the original code, if `xy_p(2)` is less than `1e-6`, `x` and `y` are not changed. Then it will enter an infinite loop.

Perception: fix endless loop in cc_lane_post_processor

---

modules/dreamview/backend/sim_control/sim_control.cc
modules/dreamview/backend/sim_control/sim_control.h
modules/planning/open_space_planning.cc
modules/planning/open_space_planning.h

1. Reverse Path point theta in Planning when in reverse gear
2. Idle Time for gear shifting
3. related fix on Sim control "PublishLocalization" by reverting the reverse of theta when in reverse gear because of point 1 above @siyangy @unacao

Planning& Dreamview: Idle gear shift time

---

modules/tools/calibration/process.py

The processing.py script finds the first usable index by searching for the last entry where the brake percentage is at (exactly) 40. This is only useful for a case where the stationary vehicle always keeps the brake at 40 percent. I've added an additional check for cases where a brake percentage of 40 is not present in the data. In these cases, the velocity of the vehicle will be used to find the index of the first entry to be used for calibration.

Tools: modified calibration script to allow starting from stationary position as well

---

modules/transform/BUILD
modules/transform/static_transform_component.cc
modules/transform/static_transform_component_test.cc

Without this unit test, the building still passes if you remove "@yaml_cpp//:yaml" from cc_library(static_transform_component_lib), while cyber cannot load it because of missing symbol definition.
So we should add a test which is static linked to guarantee that all dependencies are added.

Transform: Add init test to avoid shared linking error.

---

scripts/apollo_base.sh

a few scripts generate incorrect ANSI escape sequence, for example, on master:
```
> bash docker/scripts/dev_start.sh
[\e[34m\e[1mINFO\e[0m] Start pulling docker image apolloauto/apollo:dev-x86_64-20181210_1500 ...
dev-x86_64-20181210_1500: Pulling from apolloauto/apollo
```
With this change:
```
bash docker/scripts/dev_start.sh
[**INFO**] Start pulling docker image apolloauto/apollo:dev-x86_64-20181210_1500 ...
```

\e is not universally understood as an escape sequence

---

cyber/tools/cyber_launch/cyber_launch

For the cyber_launch script, it called `traceback.print_exc()` in line 244
However, that script haven't import traceback at all.
So I just add back the import
Since traceback is a standard library for both python 2 and 3.
This change will not cause any bad effect.

Cyber: Fix the missing import in cyber_launch

---

modules/prediction/common/feature_output.cc
modules/prediction/proto/offline_features.proto

To avoid adding more protos, DataForLearning can also play the role of the "ModelFeatures" proto.

Prediction: refactored DataForLearning proto.

---

modules/perception/lidar/tools/offline_lidar_obstacle_perception.cc

Maybe we can remove UNKNOWN* check as well, but that might affect the code readable as well as the logic.

perception: remove unnecessary type value re-assignment

---

cyber/record/record_reader.cc
cyber/tools/cyber_recorder/main.cc
cyber/tools/cyber_recorder/player/play_param.h
cyber/tools/cyber_recorder/player/play_task_producer.cc
cyber/tools/cyber_recorder/player/player.cc
docs/cyber/CyberRT_Developer_Tools.md

add -p/--preload for playing record.
When playing a single record with multiple chunks or several records in directory /mnt/nfs, we need to set a larger time to preload record files due to slower network transmission rate.

framework: add new option for playing record

---

docker/build/installers/install_ipopt.sh

updated the dev container's `installer_ipopt.sh` script to add the `universe` apt repository which is required to install the `gfortran` package
I opened issue [6735](https://github.com/ApolloAuto/apollo/issues/6735) to track this.

updated the dev container's installer_ipopt.sh

---

docker/build/installers/install_bosfs.sh

fixing build error for installer script install_bosfs.sh used building the dev container
1) added 'autotools-dev' and 'automake' to 'apt-get install' to fix the missing 'aclocal' command used in 'autogen.sh' in bosfs gzip
2) added 'uuid-dev' to 'apt-get install'. since fresh containers are missing this package, the build of bosfs fails in:
file: ./model/bce_request.cpp:16:23: fatal error: uuid/uuid.h: no such file
I created issue [6732](https://github.com/ApolloAuto/apollo/issues/6732) to track this.

fixing bosfs build error in installer script install_bosfs.sh

---

docker/build/installers/install_python_modules.sh
docker/build/installers/py27_requirements.txt

Based on comments in PR [6742](https://github.com/ApolloAuto/apollo/pull/6742), `leveldb` has been replaced with sqlite and I confirmed that removing `plyvel` from the requirements file does fix the [6741](https://github.com/ApolloAuto/apollo/issues/6741) issue.  I will close the PR.

removing plyvel from py27_requirements.txt

---

docker/build/installers/install_osqp.sh

changed install directory of `osqp` headers to `/usr/local/include`
The bazel BUILD of the math common module is expecing the osqp dependency under `/usr/local/include`.
Fixes issue [6756](https://github.com/ApolloAuto/apollo/issues/6756)

changed install directory of osqp headers to /usr/local/include

---

docker/build/dev.x86_64.dockerfile
docker/build/installers/install_poco.sh

1) the current version of the script installs from apt
2) Ubuntu 14.04 supports Poco 1.3.x which is an old release
3) The script has code that is commented out, which can install from source instead
4) The install from source uses version 1.9.0 but has a variable for changing that version
Fixes issue: [6771](https://github.com/ApolloAuto/apollo/issues/6771)

added a container installer script for the poco library

---

docker/build/installers/install_bazel_packages.sh

- added the civetweb v1.11 release artifact to install_bazel_packages.sh
Fixes issue [6769](https://github.com/ApolloAuto/apollo/issues/6769)

added the civetweb v1.11 release artifact to install_bazel_packages.sh

---

docker/build/dev.x86_64.dockerfile
docker/build/installers/install_qt.sh
docker/build/installers/qt-noninteractive.qs

Added a headless Qt 5.1.1 install script and corresponding controller script:
```
1) installer download https://download.qt.io/archive/qt/5.8/5.8.0/qt-opensource-linux-x64-5.8.0.run
2) uses qs-noninteractive.qs controller script for headless install
3) installs default selections then removes unecessary directories (Extras, Docs, Tools)
```
Fixes issue [6760](https://github.com/ApolloAuto/apollo/issues/6760)

Added a headless Qt 5.1.1 install script

---

docker/build/dev.x86_64.dockerfile

Added libgtest-dev to the list of packages installed into dev dockerfile
Fixes issue [6783](https://github.com/ApolloAuto/apollo/issues/6783)

Added libgtest-dev to the list of packages installed into dev dockerfile

---

modules/perception/radar/app/radar_obstacle_perception.cc

In the previous code, when all radar objects are out of ROI, ROIfilter() returns false and CHECK will kill the perception. Having 0 radar objects is common. For the solution, I removed CHECK

Perception: Fix the crash of HDMap ROI filter with radar

---

modules/planning/common/ego_info.cc
modules/planning/common/path_decision.cc
modules/planning/scenarios/lane_follow/lane_follow_scenario.cc

Verified using dreamland scenarios

planning: code clean up; removed two locally defined params.

---

modules/planning/tasks/deciders/speed_bounds_decider.cc
modules/planning/tasks/optimizers/speed_optimizer.cc

fix a bug where speed planning results are not ploted on dreamview

Planning: fix speed planning visualizing on dreamview

---

cyber/record/record_viewer.cc
cyber/record/record_viewer.h

The current `cyber_recorder play`  will hold all the loaded message in the memory.
It cause memory issue while playing many bags.
Example:
`cyber_recorder play -f /path/to/data//20190304154029.record.0000*`
This commit is aims at fixing this issue:
- Clear the data of the RecordReader if that file is already finish playing
This fix isn't the best solution (will still having memory issue while reading a single super large data), but it is a usable solution for general case. (A lot of sequential small data)
The below is the memory statistic before this change
The below is the memory statistic after this change
The peak memory have been reduced from 7.x GB to 2.x GB

Cyber: Fix the memory issue of cyber_record

---

modules/planning/common/ego_info.cc
modules/planning/common/ego_info.h
modules/planning/common/ego_info_test.cc
modules/planning/common/planning_gflags.cc
modules/planning/common/reference_line_info.h
modules/planning/common/speed_profile_generator.cc
modules/planning/common/speed_profile_generator.h
modules/planning/common/speed_profile_generator_test.cc
modules/planning/on_lane_planning.cc
modules/planning/scenarios/lane_follow/lane_follow_stage.cc
modules/planning/scenarios/side_pass/stage_stop_on_wait_point.cc
modules/planning/scenarios/stage.cc
modules/planning/tasks/deciders/path_bounds_decider.cc

This reverts commit d284446629dbeec90bafc32a8f3e7cc671ed143e.
Conflicts:
modules/planning/tasks/deciders/path_bounds_decider.cc

Revert "Planning: remove code related to front obs distance"

---

apollo.sh

Also:
**The reason why the coverage is inaccurate:**
target="$COV_DIR/objs/modules${f##*modules}"
Because the directory of target is cut, many different ".gcda" files are copied to the same one through {cp "$f" "$target"}.
**Solution**
We can merge multiple .gcda files into a single .gcda using gcov-tool which is available Since Ubuntu 16.04. I will try to fix the inaccurate issue after the OS is upgraded.

fix coverage error: can't find .gcno files

---

cyber/tools/cyber_recorder/main.cc
cyber/tools/cyber_recorder/player/play_param.h
cyber/tools/cyber_recorder/player/play_task_producer.cc

black channels: not play specified channel(s) when play record file .
`-k, --black-channel <name>		not play the specified channel`

framework: enable black channels for cyber_recorder play mode 

---

modules/canbus/proto/chassis.proto
modules/canbus/vehicle/lincoln/lincoln_controller.cc
modules/canbus/vehicle/lincoln/lincoln_controller_test.cc

Update the Lincoln model as the first example.

Canbus: classify the specific chassis error type in Chassis channel

---

modules/perception/fusion/lib/gatekeeper/pbf_gatekeeper/pbf_gatekeeper.cc

Traffic cone was not published since any camera object within 50 meters was discarded. Since the camera is the best way to detect a traffic cone, I removed 50 meter condition for publishing a traffic cone.

Perception: Publish traffic cone using camera only

---

CONTRIBUTING.md

Corrected link for Python License example in CONTRIBUTING.md

DOC: Corrected link for Python License example in CONTRIBUTING.md

---

cyber/tools/cyber_launch/cyber_launch

fix traceback when run `cyber_launch start some_launch file` signal Keyboard interrupt :
```
Traceback (most recent call last):
File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 521, in <module>
main()
File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 508, in main
start(params.file)
File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 438, in start
all_died = pmon.run()
File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 280, in run
time.sleep(0.2)
TypeError: signal_handler() takes exactly 1 argument (2 given)
```

framework:fixed TypeError: signal_handler()

---

modules/control/controller/lat_controller.cc
modules/control/controller/lat_controller.h

Control module updates in a very high rate. A formula is calculated in every frame, whose variables are never changed. 
So, use a variable to store the result of this formula.
After testing on TX2, this could reduce the CPU usage of Control by 3%-5%.

use a variable to store result of formula to avoid calculating repeatedly

---

modules/common/configs/BUILD
modules/common/configs/config_gflags.cc
modules/common/configs/config_gflags.h
modules/common/configs/cpu_bind_helper.cc
modules/common/configs/cpu_bind_helper.h
modules/common/configs/cpu_bind_helper_test.cc
modules/common/data/cpu_bind.yaml
modules/dreamview/backend/BUILD
modules/dreamview/backend/dreamview.cc
modules/perception/BUILD
modules/perception/perception.cc

This feature aims to monitor CPU usage of processes. 
Generally, It brings two benefits:
1. for a certain process and its threads, reduce the possibility of jumping between different cores
2. reduce the consumption of accessing memory and maintaining cache coherence when a process or thread switch cores
Trying to merge to v3.1_dev

add cpu binding module for monitoring CPU usage more conveniently

---

modules/planning/tasks/deciders/open_space_roi_decider.cc

1, remove virtual obstacles from open space
2, the rigid transfer to obstacles should be according to original point instead of the obstacle's center.

planning: open space fix rigid transform bug when extracting obstacles

---

modules/control/controller/mpc_controller.cc
modules/control/controller/mpc_controller.h
modules/control/controller/mpc_controller_test.cc
modules/control/proto/control_cmd.proto

Similar modifications on MPC controller, as on lon/lat controllers. 
Generated records already verified by Dreamland simulation

Control: compute the acceleration, jerk variables for Mpc Controller

---

cyber/tools/cyber_launch/cyber_launch

* fix a bug on cyber_launch from [#7382](https://github.com/ApolloAuto/apollo/pull/7382/files#diff-f3273e146da2e951b7535a9a181f606dL97), which cause logging info overwhelming.
The ColoredFormatter class is using '#' to split the logging, please don't change the logging info. @freeHackOfJeff

Cyber: fix cyber_launch bug from #7382

---

modules/planning/tasks/deciders/path_assessment_decider.cc

* This low ```kBackToSelfLaneComparisonTolerance``` make inconsistent path decision, which may switch the path from left to right.

Planning: enlarge BackToSelfLaneTolerance

---

apollo.sh

enable bazel's feature to compute md5 checksums in parallel.
`docker/scripts/dev_start.sh` brings in over a GB of map data. Then, the maps are globbed and turned into a `file_group` in https://github.com/ApolloAuto/apollo/blob/master/modules/map/BUILD#L3. bazel server will compute the md5 sums and keep it in memory the first time `bazel build` or `bazel test` runs on `modules/map`. Digesting these files takes longer as file sizes grow.
Running in parallel is much faster and doesn't seem to cause any problems.

apollo.sh experimental_multi_threaded_digest

---

modules/planning/conf/scenario/lane_follow_config.pb.txt
modules/planning/tasks/rss/decider_rss.cc
modules/planning/tasks/rss/decider_rss.h

When running public and stable test scenarios, some corner cases may trigger rss malfunction and print error message "ad_rss::extractSituation failed".
this issue has been root caused. Former environment conversion in lateral projection may be out of range and introduce this failure.
This patch contain this fix. Please Apollo team review and comment on it.

rss-open-library-fix-lateral-out-of-range-issue

---

modules/canbus/vehicle/ch/ch_controller.cc

warning: unused variable 'real_angle_spd' [-Wunused-variable]

canbus:fix build warning

---

modules/canbus/canbus_component.cc
modules/canbus/canbus_component.h

-Override Clear() from ComponentBase so internal handles are cleaned up
during shutdown.
-Fixes #8053

[#8053] canbus component does not exit gracefully.

---

modules/drivers/gnss/proto/config.proto

The rationale behind this change is explained in https://github.com/ApolloAuto/apollo/issues/7450
This is justified by https://docs.novatel.com/oem7/Content/SPAN_Commands/CONNECTIMU.htm
It has been tested to solve IMU problems with Apollo running with a PwrPak7-E1

[gnss] Assign the IMU ID 41 to the EPSON G320N as required by Novatel

---

modules/planning/conf/planning_config.pb.txt
modules/planning/on_lane_planning.cc
modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_optimizer.cc
modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_optimizer.h
modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_provider.cc

Since we have decided to change designs to use Astar when smoother failed, there is no point of making the recording part more complicated than needed.

Planning: revert breaking open space debug, and fix for missing open space decider conf

---

docker/scripts/dev_start.sh

```
git clone https://github.com/ApolloAuto/apollo.git repo1
docker/scripts/dev_start.sh
git clone https://github.com/ApolloAuto/apollo.git repo2
docker/scripts/dev_start.sh
ll / | grep apollo
```
The symlink will point to repo2

enable different clone locations

---

docker/scripts/dev_start.sh

To improve CI efficiency, add two new options in docker script as dev_start.sh
* -b for build only, not pulling any map information
* -f for unit tests, pull only limited set of map information
Due the growing number of maps, it's pain to pulling all the map at each CI steps.
We have 5 steps in total in CI right now. First three steps can run well without
any map, and the rest will need some limited map support.
Total time of all steps in a CI reduces from about 2 hours to 90mins, which save
both time and resources.
Previous tested CI with -b and -f options to prove its correctness:
https://travis-ci.com/ApolloAuto/apollo/builds/112120858
https://travis-ci.com/ApolloAuto/apollo/builds/112129192

docker: adding more options for docker script to improve CI efficiency

---

modules/map/BUILD
modules/map/data/BUILD
modules/map/hdmap/BUILD
modules/map/pnc_map/BUILD
modules/map/tools/BUILD
modules/planning/integration_tests/BUILD
modules/planning/tasks/deciders/speed_bounds_decider/BUILD
modules/tools/manual_traffic_light/BUILD

bazel is still hashing a lot of maps, it doesn't need to. Two tests only need sunnyvale_big_loop and sunnyvale_loop. Bazel's hashing is useful for reproducing test results, but a lot of libraries didn't actually need all the maps exactly as they are.
```
docker/scripts/dev_start.sh && ./apollo_docker.sh citest_extended && docker/scripts/dev_start.sh && time ./apollo_docker.sh citest_extended
```
is about 25 seconds regardless of this change.
```
docker/scripts/dev_start.sh && docker/scripts/dev_into.sh
bazel test //modules/planning/integration_tests:sunnyvale_big_loop_test
```
Goes from 230 seconds to 18 seconds.

dont depend on all maps

---

cyber/python/cyber_py/topology_manager.py

Recently, I called the Topology Manager to my own scripts.
I found that it have about 2 second blocking when calling it function.
Then I found that the original Topology Manager will create the new node_manager or node_manager in every function call.
It cause a blocking while it is meaningless to recreate those manager in every function call.
Fix it to improve performance

Cyber: Improve the performance of python Topology Manager.

---

modules/common/data/global_flagfile.txt

This reverts commit 870a12dc55a2c575429f1baa26e910985235f779.
It breaks at runtime.

Revert "Common: change default log level for mpi_dev banch"

---

modules/perception/camera/lib/obstacle/detector/yolo/proto/yolo.proto
modules/perception/camera/lib/obstacle/detector/yolo/region_output.cu
modules/perception/camera/lib/obstacle/detector/yolo/region_output.h
modules/perception/camera/lib/obstacle/detector/yolo/yolo_obstacle_detector.cc
modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-r4-half/deploy.pt

Change code to accept multi-scale camera object detection outputs of neural networks. Preparation work for Yolo-v3 object detection network.

Perception: prepare code for multi-scale camera object detection

---

modules/prediction/launch/prediction.launch

Prediction: remove LD_PRELOAD in prediction.launch because the issue has been fixed by something else

---

modules/drivers/velodyne/dag/velodyne128.dag

The path was incorrect. velodyne128_compensator_conf.pb.txt does not exist.

Velodyne: conf path is incorrect

---

modules/prediction/scenario/prioritization/obstacles_prioritizer.cc

Actually we can get the `lane_graph` after inserted the ego vehicle position information for the first time.
Fixed at least the ERROR report every loop.
```
E0611 10:19:06.131490   190 obstacles_prioritizer.cc:200] [prediction] Ego vehicle has no history
```

prediction: udpate feature history size condition

---

modules/tools/configurator/ModuleConf.py

Value Error exception :
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
return _convert(node_or_string)
File "/usr/lib/python2.7/ast.py", line 79, in _convert
raise ValueError('malformed string')
ValueError: malformed string
```

tools: fixed issue:#8759 configurator.sh is no longer functioning

---

modules/planning/conf/planning_config.pb.txt
modules/planning/conf/scenario/valet_parking_config.pb.txt

Note: this modification will compensate the previous commit 5fc5579,  in which only the default value of the iou (but not the one eventually used) gets changed

Planning: (effectively) reduce iou checkout ratio for trajectory switch

---

cyber/common/time_conversion.h

Undefined behavior in `-b` and `-e` arguments cause the `cyber_recorder play` program to add numbers incorrectly on my computer. This change was tested with `valgrind`.
Here is a explanation on the fix: https://stackoverflow.com/a/24185697

mktime called with properly initialized data

---

modules/planning/README_cn.md

modules/planning/README_cn.md architecture image haven't shown as README.md(English version), because the image name should be architecture.png, not planning_architecture.png. This patch fixed the problem.

Update modules/planning/README_cn.md fix architecture image problem

---

docs/specs/apollo_3.0_development_kits_user_manual_cn.md

Update the markdown file of coohigh's user manual which is cherry-picked from branch v3.1_dev to branch r3.0.0 the fifth time

Update the markdown file of coohigh's user manual which is cherry-picked from branch v3.1_dev to branch r3.0.0 the fifth time

---

docker/scripts/dev_start.sh

We check the status of "docker run", not "set +x"

scripts: fix command exit status check

---

cyber/time/time.h

It might be nice to enable value initialization or aggregate initialization for this class through the default constructor: https://stackoverflow.com/a/2418195. That way the class can be zero'd out if desired. Also, it seems that the destructor definition isn't doing anything.

cyber time default constructor

---

docker/scripts/dev_start.sh

After:
```
[INFO] Starting docker container "apollo_dev_xmyqsh" ...
++ local_volumes
++ set +x
+ nvidia-docker run -it -d --privileged --name apollo_dev_xmyqsh --volumes-from apollo_map_volume-sunnyvale_big_loop_xmyqsh --volumes-from apollo_map_volume-sunnyvale_loop_xmyqsh --volumes-from apollo_map_volume-sunnyvale_with_two_offices_xmyqsh --volumes-from apollo_map_volume-san_mateo_xmyqsh --volumes-from apollo_yolo3d_volume_xmyqsh --volumes-from apollo_localization_volume_xmyqsh --volumes-from apollo_paddlepaddle_volume_xmyqsh --volumes-from apollo_local_third_party_volume_xmyqsh -e DISPLAY=:0 -e DOCKER_USER=xmyqsh -e USER=xmyqsh -e DOCKER_USER_ID=1000 -e DOCKER_GRP=xmyqsh -e DOCKER_GRP_ID=1000 -e DOCKER_IMG=apolloauto/apollo:dev-x86_64-20190617_1100 -e USE_GPU=1 -v …
```

only print docker run

---

modules/perception/camera/lib/motion_service/motion_service.cc
modules/perception/camera/lib/traffic_light/preprocessor/tl_preprocessor.cc
modules/perception/onboard/component/fusion_camera_detection_component.cc
modules/perception/onboard/component/fusion_component.cc
modules/perception/onboard/component/lane_detection_component.cc
modules/perception/onboard/component/radar_detection_component.cc
modules/perception/onboard/component/radar_detection_component.h
modules/perception/onboard/component/recognition_component.cc
modules/perception/onboard/component/segmentation_component.cc
modules/perception/onboard/component/trafficlights_perception_component.cc
modules/perception/onboard/msg_serializer/msg_serializer.cc

Unify perception module with cyber time.
Because all of the perception sensor drivers use cyber time.
And if [9161](https://github.com/ApolloAuto/apollo/pull/9161) is approved.
Then we could unify all of the time with Clock time(Tick time).

Perception: unify with cyber time

---

modules/perception/lidar/lib/object_builder/object_builder.cc

object checker and id could/have been set before.

Perception: refine object_builder

---

modules/perception/lidar/common/cloud_mask.cc
modules/perception/lidar/common/cloud_mask.h
modules/perception/lidar/lib/segmentation/cnnseg/spp_engine/spp_engine.cc
modules/perception/lidar/lib/segmentation/cnnseg/spp_engine/spp_engine.h

fix RemoveGroundPointsInForegroundCluster
Note: the non_ground_indices is the indices of the cloud,
not the indices of roi_indices
(This mismatch may be caused by API update)
set points_in_roi

Perception: fix RemoveGroundPointsInForegroundCluster and set points_in_rois

---

cyber/init.cc
cyber/logger/logger_util.h

There's a warning whenever any cyber program is run. To reproduce
```
bazel build //cyber/examples:talker
bazel-bin/cyber/examples/talker
```
The warning is
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
```
After this change, the warning will go away. All glog calls should occur after the `google::InitGoogleLogging(binary_name);`. I assume this check is for async logger. Must all singletons be checked for not null?

Cyber: moved common globaldata instance check

---

cyber/tools/cyber_recorder/info.cc

Start new line to align `cyber_recorder ` field channel info.

cyber: align channel info for cyber_recorder info record

---

cyber/record/file/record_file_base.h
cyber/record/file/record_file_test.cc
cyber/record/file/record_file_writer.cc

- Fixed index positions so they point to the beginning of their respective sections
- Before: indexes were pointing to the end of channel and chunk sections which makes the index useless

cyber: fix for record file

---

modules/tools/sensor_calibration/README.md
modules/tools/sensor_calibration/ins_stat_publisher.py
modules/tools/sensor_calibration/odom_publisher.py

Cause the GNSS device(NEWTON M2) of development_kits can't generate topic "/apollo/sensor/gnss/odometry" & "/apollo/sensor/gnss/ins_stat", but those topics required by Apollo's sensor calibration tools , so the scripts are used to publish "/apollo/sensor/gnss/odometry" through subscribe "/apollo/localization/pose" and publish a fake "/apollo/sensor/gnss/ins_stat".

add scripts for perception sensors calibration

---

modules/tools/sensor_calibration/README.md
modules/tools/sensor_calibration/ins_stat_publisher.py
modules/tools/sensor_calibration/odom_publisher.py

Cause the GNSS device(NEWTON M2) of development_kits can't generate topic "/apollo/sensor/gnss/odometry" & "/apollo/sensor/gnss/ins_stat", but those topics required by Apollo's sensor calibration tools , so the scripts are used to publish "/apollo/sensor/gnss/odometry" through subscribe "/apollo/localization/pose" and publish a fake "/apollo/sensor/gnss/ins_stat".

Tools:add scripts for perception sensors calibration

---

.gitignore
docker/scripts/dev_into.sh

It's convenient to return to the container and lookup old commands in the bash history. For example,
```
docker/scripts/dev_into.sh
echo 1
exit
docker/scripts/dev_into.sh
```
Pressing up or using ctrl-R will use bashes history to lookup previous commands.

container writes bash history

---

modules/prediction/common/road_graph.cc

LaneById may return nullptr,and push into vector.

prediction:fix coredump when get map by LaneById return nullptr

---

modules/planning/common/reference_line_info.cc

obstacle and mutable_obstacle do not point to the same object

Planning: change obstacle to mutable_obstacle, obstacle and mutable_obstacle do not point to the same object

---

scripts/apollo_base.sh
scripts/docker_adduser.sh

In dreamland online service, docker_adduser.sh will not be called. "unset OMP_NUM_THREADS" will not work when dreamland build.

Move unset OMP_NUM_THREADS to apollo base.

---

modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc

There is UB on reading unitialized `lane_boundary_type`, when `lane_borrow_info` is set to `NO_BORROW`.

Planning: path_bounds_decider handles NO_BORROW

---

modules/map/pnc_map/pnc_map.cc

`range_lane_ids_` is an unordered_set.
We cannot handle it well with these code snips:
```
while (range_start_ + 1 < adc_index) {
// TODO(Hongyi): Delete this when confirmed
// range_lane_ids_.erase(route_indices_[range_start_].segment.lane->id().id());
++range_start_;
}
```
```
if (range_lane_ids_.count(lane_id) != 0) {
break;
}
```

Map: enhance UpdateRoutingRange

---

modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc

Two things have been done.
The first is to finish the request of `// TODO(jiacheng): using ToFrenetFrame only.`. @panjiacheng 
The second is the changing of `adc_frenet_ld_ ` assignment.
`adc_frenet_ld_ = adc_sl_info.second[1] * adc_frenet_sd_;`
--->
`adc_frenet_ld_ = adc_sl_info.second[1];`
Please double check the second.

Planning: using ToFrenetFrame only

---

modules/canbus/proto/ch.proto
modules/canbus/vehicle/ch/protocol/brake_status__511.cc
modules/canbus/vehicle/ch/protocol/brake_status__511.h
modules/canbus/vehicle/ch/protocol/ecu_status_1_515.cc
modules/canbus/vehicle/ch/protocol/ecu_status_1_515_test.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.h
modules/canbus/vehicle/ch/protocol/gear_command_114.cc
modules/canbus/vehicle/ch/protocol/gear_command_114.h
modules/canbus/vehicle/ch/protocol/gear_status_514.cc
modules/canbus/vehicle/ch/protocol/gear_status_514.h
modules/canbus/vehicle/ch/protocol/steer_status__512.cc
modules/canbus/vehicle/ch/protocol/steer_status__512.h
modules/canbus/vehicle/ch/protocol/throttle_status__510.cc
modules/canbus/vehicle/ch/protocol/throttle_status__510.h

Coolhigh canbus repor protocols need to add takeover for checkresponse, and update some comments.

Canbus: add the takeover into the coolhigh report protocols

---

modules/planning/common/path/discretized_path.cc
modules/planning/common/path/discretized_path.h
modules/planning/common/path/frenet_frame_path.cc
modules/planning/common/path/frenet_frame_path.h
modules/planning/common/path/frenet_frame_path_test.cc
modules/planning/tasks/deciders/speed_bounds_decider/speed_limit_decider_test.cc
modules/planning/tasks/deciders/speed_bounds_decider/st_boundary_mapper.cc
modules/planning/tasks/deciders/speed_bounds_decider/st_boundary_mapper_test.cc
modules/planning/tasks/optimizers/piecewise_jerk_path/piecewise_jerk_path_optimizer.cc

Motivation of this PR:
There is some piece of code intended to use [FrenetFramePath move constructor](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/common/path/path_data.cc#L262) or [DiscretizedPath move constructor](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/scenarios/lane_follow/lane_follow_stage.cc#L336), while there is no move constructor for FrenetFramePath and DiscretizedPath. Pieces of code like `SetFrenetPath(FrenetFramePath(std::move(frenet_frame_points)));` calls extra copy constructor additionally which is not intended for.

Planning: add move constructor for FrenetFramePath and DiscretizedPath and use it wherever it is possible

---

modules/planning/scenarios/traffic_light/unprotected_left_turn/stage_creep.cc
modules/planning/scenarios/traffic_light/unprotected_right_turn/stage_creep.cc

I don't think we can finish `TrafficLightUnprotectedLeftTurnStageCreep ` or `TrafficLightUnprotectedRightTurnStageCreep` stage when there is any overlaped traffic light is not green.

Planning: adjust traffic_light in stage_creep.cc

---

scripts/apollo_base.sh

Since Apollo is now migrated to Cuda10 and there is no cuda8 anymore, we need to update apollo_base script to put correct path for updated cuda. We can use symlink for cuda-10.

Fix cuda directory path to use cuda symlink

---

modules/planning/tasks/deciders/path_reuse_decider/path_reuse_decider.cc
modules/planning/tasks/deciders/path_reuse_decider/path_reuse_decider.h

From
```
if (current_stop_positions[i].x() != history_stop_positions[i].x() &&
current_stop_positions[i].y() != history_stop_positions[i].y())
```
To
```
if (std::fabs(current_stop_positions[i]->x() -
history_stop_positions[i]->x()) > 1e-6 ||
std::fabs(current_stop_positions[i]->y() -
history_stop_positions[i]->y()) > 1e-6)
```

Planning: refine path reuse decider to make it more efficiency and accurate

---

modules/dreamview/backend/simulation_world/simulation_world_service.cc
modules/dreamview/backend/simulation_world/simulation_world_service.h

Three main fixes on the previous one: #9584 who is reverted by #9591
1. add `mutable` on `boost::shared_mutex route_paths_mutex_;` who will be modified in const member function `Json SimulationWorldService::GetRoutePathAsJson() const {`.
2. fix the scope of temp variable `route_paths` in function `Json SimulationWorldService::GetRoutePathAsJson() const {`.
3. add redundant read lock on 
```
{
boost::shared_lock<boost::shared_mutex> reader_lock(route_paths_mutex_);
if (world_.has_routing_time() &&
world_.routing_time() == routing_response.header().timestamp_sec()) {
// This routing response has been processed.
return;
}
```
by replacing
```
// NOTICE: No need to add read lock here. Because no elsewhere place
//         modifys the world_.routing_time() field concurrently.
// …
```

Dreamview: add rwlock on route_paths_

---

modules/dreamview/backend/BUILD
modules/dreamview/backend/dreamview.cc
modules/dreamview/backend/dreamview.h
modules/dreamview/backend/perception_camera_updater/BUILD
modules/dreamview/backend/perception_camera_updater/perception_camera_updater.cc
modules/dreamview/backend/perception_camera_updater/perception_camera_updater.h
modules/dreamview/backend/simulation_world/BUILD
modules/dreamview/backend/simulation_world/simulation_world_updater.cc
modules/dreamview/backend/simulation_world/simulation_world_updater.h
modules/dreamview/proto/BUILD
modules/dreamview/proto/camera_update.proto
modules/transform/buffer.cc
modules/transform/buffer.h

To provide projecting HDmap to camera view, the frontend adds a 'Camera View' under the point of view, and by default this option is not displayed to users, thus users won't feel any difference; the backend adds a websocket for sending camera image & related transformation matrix (transformation matrix is for calculating camera real-world position & rotation, based on static transforms and localization) to frontend.

Dreamview: camera view backend

---

modules/planning/common/path/path_data.cc
modules/planning/common/path/path_data.h
modules/planning/navi/decider/navi_path_decider.cc
modules/planning/tasks/deciders/path_assessment_decider/path_assessment_decider.cc
modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc
modules/planning/tasks/deciders/speed_bounds_decider/speed_limit_decider_test.cc
modules/planning/tasks/deciders/speed_bounds_decider/st_boundary_mapper_test.cc
modules/planning/tasks/optimizers/piecewise_jerk_path/piecewise_jerk_path_optimizer.cc
modules/planning/tasks/optimizers/road_graph/dp_road_graph.cc

Using default move copy/copy construction and move assignment/assignment operation here on `DiscretizedPath`, `FrenetFramePath` and  `std::vector<std::tuple<double, PathPointType, double>>` should be OK. All their member data are on stack.

Planning: use std::move on path related data wherever it is possible

---

cyber/tools/cyber_monitor/general_message.cc
cyber/tools/cyber_monitor/general_message_base.cc

It's difficult to view messages like `apollo.monitor.SystemStatus.hmi_modules` because the indices keep changing. Protobufs map's indices are not consistent, which is fine for most use cases. For visualizing them, it makes sense to sort the keys lexicographically.

Cyber: sorts map by string keys in cyber_monitor

---

docker/scripts/dev_start.sh

Added these env variables to the docker run command in order to get access to nvidia libraries. 
This looks like a necessary step for nvidia docker v2.

added NVIDIA_DRIVER_DEVICES and NVIDIA_DRIVER_CAPABILITIES

---

modules/perception/camera/lib/lane/common/common_functions.h

Instead of using solver, inverse of 3x3 or 4x4 matrix is used which is a closed form solution

Perception: Fix Eigen::solver crash. 

---

modules/common/util/points_downsampler.h

Reduce the steep turn from 90 degree to 80 degree, so that some turn with nearly 90 degree can be treated as steep ones and drawn more points

Dreamview: update sim_map generation

---

modules/map/pnc_map/pnc_map.cc

`GetWaypointIndex(routing_waypoint_index_.back().waypoint)`
must be always equal to 
`routing_waypoint_index_.back().index`

Map: fix stop_for_destination_ assigning

---

cyber/tools/cyber_monitor/general_message.cc

'iota' is not a member of 'std'

cyber: fix build error on arm

---

docker/build/cyber.x86_64.dockerfile
docker/build/installers/install_python_modules.sh
docker/build/installers/py27_requirements.txt
docker/scripts/cyber_start.sh

a) install python modules so python tools could be fully supported
b) replace ubuntu 18.04 base with Nvidia cuda base image, so streamline
the process from cyber docker image to dev docker image

cyber: update cyber docker image with python and cuda support

---

modules/common/vehicle_state/vehicle_state_provider.cc

In gcc 5.4.0, `bazel test --config=unit_test -c opt --copt=-fpic //modules/common/vehicle_state:vehicle_state_provider_test` will fail. In general, [the eigen project doesn't recommend using auto](https://eigen.tuxfamily.org/dox/TopicPitfalls.html#TopicPitfalls_auto_keyword). I'd recommend using an explicit type here.

remote Eigen auto in vehicle state provider

---

cyber/base/object_pool_test.cc

There is undefined behavior in the object pool test. I'm not sure if it is in the usage as well.
Basically, there shouldn't be any usage of an object before it is constructed. It can get very tricky. There are some CPPCon talks about these kind of issues [CppCon 2019: CJ Johnson “How to Hold a T”
](https://www.youtube.com/watch?v=WX8FsrUbLjc) and [CppCon 2019: Miro Knejp “Non-conforming C++: the Secrets the Committee Is Hiding From You”](https://youtu.be/IAdLwUXRUvg?t=1103).
In C++17 and beyond you can access [indeterminate values](https://eel.is/c++draft/basic.indet), if they are `std::byte` or `unsigned`. Access outside of the lifetime of an object is undefined as per this [example in the standard](https://eel.is/c++draft/conv.lval).
Newer compilers may optimize away parts of the code. …

Cyber: remove UB from cyber base object pool test

---

modules/perception/onboard/proto/trafficlights_perception_component.proto

`/apollop/sensor/camera/front_12mm` -> `/apollo/sensor/camera/front_12mm`

Perception: Fix typo in channel name.

---

docker/build/dev.x86_64.dockerfile

Fixes #10021 
Dockerfile for dev.x86_64 upgraded to work with `Ubuntu 18.04` instead of `14.04` earlier

dev.x86_64 Dockerfile upgraded to Ubuntu 18.04

---

docker/build/installers/install_opuslib.sh

Besides this script, the following are needed:
`sudo apt install libasound2-dev`
`sudo pip install pyalsaaudio`

Audio: dependencies

---

modules/dreamview/backend/teleop/teleop.cc
modules/dreamview/backend/teleop/teleop.h

This adds logic to start / stop video encoders (2 for now).
The first message to start is sent when the user toggles the switch (setting a "starting" status). During the daemon report callback, if the encoders are not all started, then more messages are sent. 
In this PR, the UI is not "aware" of the "starting" / "stopping" status. A single "stopped, starting, started, stopping" list could replace the 4 booleans value.  One thing to note is that if the video is "starting" and the user presses the switch, the backend will go to "stopping" mode. This behavior might surprise the user.
Next, the same recipe should be applicable to audio and "Pull over" (using the planner msg instead of the daemon report). These should be simpler since there's only one audio encoding node, and one pad planner …

Start stop encoders

---

cyber/class_loader/BUILD
cyber/class_loader/class_loader_test.cc

class_loader_test has a runtime dependency on the plugins.
To reproduce
```
bazel test //cyber/class_loader/class_loader_test
```
The other change is to improve the results from valgrind. Unfortunately, there are still problems from the logger and other parts of cyber.

Cyber: stabilize cyber class_loader_test

---

third_party/python27.BUILD
third_party/python3.BUILD

Fixed build errors like:
```bash
ERROR: (11-11 23:37:16.384) /home/nvidia/apollo/cyber/py_wrapper/BUILD:44:1: Linking of rule '//cyber/py_wrapper:py_init_test' failed (Exit 1).
bazel-out/local-dbg/bin/_solib_arm/libcyber_Spy_Uwrapper_Slibpy3_Uinit.so: undefined reference to `PyModule_Create2'
bazel-out/local-dbg/bin/_solib_arm/libcyber_Spy_Uwrapper_Slibpy3_Uinit.so: undefined reference to `_Py_FalseStruct'
bazel-out/local-dbg/bin/_solib_arm/libcyber_Spy_Uwrapper_Slibpy3_Uinit.so: undefined reference to `PyArg_ParseTuple'
bazel-out/local-dbg/bin/_solib_arm/libcyber_Spy_Uwrapper_Slibpy3_Uinit.so: undefined reference to `_Py_NoneStruct'
bazel-out/local-dbg/bin/_solib_arm/libcyber_Spy_Uwrapper_Slibpy3_Uinit.so: undefined reference to `_Py_TrueStruct'
```

Cyber: python build support arm platform

---

cyber/tools/cyber_monitor/general_message.cc

When unfold a repeated field in cyber monitor, the cyber monitor will crash if that field is not CPPTYPE_MESSAGE type

[cyber_monitor] Fix crash when unfold the a repeated field

---

modules/perception/lidar/lib/segmentation/cnnseg/BUILD

fix the absence of detector and filter instance in CNN Segmentation.
absence list:
- modules/perception/lidar/lib/roi_filter/hdmap_roi_filter
- modules/perception/lidar/lib/ground_detector/spatio_temporal_ground_detector

Perception: fix the absence of instance in cnn segmentation

---

modules/map/hdmap/hdmap_impl_test.cc

It might be good to support the `--runs_per_test` feature for all tests. This change should make the test file unique and cleanup the file afterward.
```
bazel test --runs_per_test=50 //modules/map/hdmap:hdmap_map_test
```

Map: hdmap_map_test runs in parallel

---

modules/prediction/common/feature_output.cc
modules/prediction/container/obstacles/obstacles_container.cc

This PR fixes memory leak issue described in #10440 
In offline mode each time after dump containers are cleaned. But in online mode there is no cleanup and the data accumulates infinitely. This leads to an unlimited increase in memory consumption.
So I invoke Clear() in offline mode and add missing cleaning of containers in this method.

Memory leak in prediction module

---

cyber/class_loader/utility/class_loader_utility.cc

more clear use of iterating over std::map containing erasing operations.

bugfix: std::map.erase(iter)

---

apollo.sh

This reverts commit 4f9f1720bad418d677990aef9727a627c579cbf9.
This is not the root cause, while make everyone compile slower. If you met the problem like browser crashing during compiling, a potential reason is that you have a too small swap partition.

Revert "Scripts: May fix CPU drain issue on powerful machines."

---

modules/dreamview/backend/handlers/websocket_handler.cc
modules/localization/ndt/ndt_localization.cc
modules/localization/rtk/rtk_localization.cc
modules/localization/rtk/rtk_localization_component.cc
modules/planning/common/path/path_data.cc
modules/planning/navi/decider/navi_path_decider_test.cc
modules/planning/navi_planning.cc
modules/planning/planner/public_road/public_road_planner.cc
modules/planning/proto/planning_internal.proto
modules/planning/proto/planning_status.proto
modules/planning/proto/st_drivable_boundary.proto
modules/planning/reference_line/reference_line.cc
modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc
modules/planning/tasks/deciders/path_decider/path_decider.cc
modules/planning/tasks/deciders/path_lane_borrow_decider/path_lane_borrow_decider.cc
modules/planning/tasks/deciders/speed_bounds_decider/st_boundary_mapper.cc
modules/planning/tasks/deciders/speed_decider/speed_decider.cc
modules/planning/tasks/deciders/st_bounds_decider/st_obstacles_processor.cc
modules/planning/tasks/optimizers/road_graph/dp_road_graph.cc

for DCHEKC_NOTNULL WARNING, use CHECK_NOTNULL don't need to change logic for now:
// You may see warnings in release mode if you don't use the return
// value of DCHECK_NOTNULL. Please just use DCHECK for such cases.

Build: clean build warnings

---

modules/canbus/conf/canbus_conf.pb.txt
modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc
modules/drivers/canbus/can_client/socket/socket_can_client_raw.h
modules/drivers/canbus/proto/can_card_parameter.proto

Added support for virtual and serial CAN interfaces when using the socket CAN client. Tested with our virtual CAN bus based drive by wire simulator. 
closes #10546

canbus: added option to select socket CAN interface (native, virtual or slcan)

---

modules/dreamview/backend/simulation_world/simulation_world_service_test.cc

This test was relying on the internal implementations order. The internal implementation uses an unordered_set. In newer versions of gcc, the order is less predictable.

remove order dependence on simulation_world_service_test

---

cyber/io/poller.cc
cyber/io/poller_test.cc

I got a few random errors from this test. The valgrind uninitialized values passed to system call may be false positives, but I figure it cannot hurt. The timeout seems to make the results more stable.
Test
```
bazel test -c dbg //cyber/io:poller_test
sudo apt update && sudo apt install valgrind
valgrind bazel-bin/cyber/io/poller_test
```

Cyber: io_poller regularized test results

---

cyber/init.cc
cyber/logger/async_logger.cc
cyber/logger/async_logger.h
cyber/logger/async_logger_test.cc

There is potential for an index out of bounds on a fatal message. It seems that glog writes a zero length message if logtostderr is set: https://github.com/google/glog/blob/58d7f873dcde8cf0fe6f37817643a7ff4e49e6d4/src/logging.cc#L1626.
Also, there's a memory leak for the logger object. Glog does not delete it.
To test the index out of bounds, you can replace the `[]` operator with `at`. Then, call `ACHECK(false)`. You should see an exception out of bounds.
To test the memory leak, you look
```
valgrind --leak-check=full --show-leak-kinds=all mainboard modules/planning/dag/planning.dag
```
before and after the changes.

async_logger bug fixes

---

modules/dreamview/backend/main.cc
modules/dreamview/backend/simulation_world/simulation_world_updater.h

Dreamview sefaults after SIGINT. There are two issues.
1. `~Dreamview()` is called after `apollo::cyber::Clear()`. This causes a segfault because AINFO is called, but the logger is shutdown.
2. The SimulationWorldUpdater timer callback can be run while it is shutting down. This means that it can access out of scope data.
1. `bazel-bin/modules/dreamview/dreamview`
2. Wait 5 seconds
3. Press ctrl-c
4. Assert that the program returns within 5 seconds
5. `echo $?`
6. Assert that the exit code is 0

Dreamview: closes cleanly

---

cyber/mainboard/mainboard.cc
cyber/mainboard/module_argument.cc

It seems like the `SetUsageMessage` doesn't do anything in mainboard. It adds an unnecessary direct dependency on gflags. Therefore, I recommend removing it.
mainboard will hang without parameters. New users may make mistakes and not realize it.
```bash
bazel build -c opt //modules/planning:libplanning_component.so //cyber:mainboard
```
```c++
mainboard && echo $?
mainboard -h && echo $?
```
```c++
mainboard -p asdf && echo $?
mainboard -d modules/planning/dag/planning.dag asdf && echo $?
mainboard modules/planning/dag/planning.dag && echo $?
```
```c++
mainboard -d modules/planning/dag/planning.dag
```

Cyber: mainboard exits without parameters

---

cyber/scheduler/policy/scheduler_choreography.cc

#10902 
1. Fixed in "SchedulerChoreography::RemoveCRoutine", add a condition pid should less than processor num
2. Fixed in "SchedulerChoreography::NotifyProcessor",  add a condition pid should less than processor num, move the "pid = cr->processor_id();" in the lock block.

Fixed processor_id range overflow

---

docs/howto/how_to_add_a_new_can_card.md

1. The can_card_parameter.proto has been removed to other location;
2. Canbus alse affects radar, its' canbus configuration file should be updated too.

fix canbus configuration update guide

---

docker/build/build_dev.sh

add "-l/--local" option to `build_dev.sh` to facilitate local development.

apollo_dev image build:  option for the local_dev tag

---

.bazelignore
.gitignore
apollo.sh
apollo_docker.sh
docker/scripts/cyber_start.sh
docker/scripts/dev_start.sh
docker/scripts/release_start.sh
scripts/ota.sh
tools/bazel.rc

This fixes #issues/11198. We don't put bazel cache in $HOME/.cache outside container; Instead, we take advantage of  bazel's `--output_user_root` startup option (pointing to /apollo/bazel-root inside container, $APOLLO_ROOT/bazel-root outside).  
Although bazel-0.5.3 doesn't support `.bazelignore` file yet, it makes no harm. As soon as we moved to bazel 3.x, `.bazelignore` will come to life!

introduce bazel  "--output_user_root" startup option

---

modules/perception/radar/lib/tracker/matcher/hm_matcher.cc

There is repeat function in hm_matcher.cc, just use "DistanceBetweenObs()" is ok. 
refer #11282

perception: fix repeat function in hm_matcher.cc

---

scripts/apollo.bashrc
scripts/apollo_base.sh
scripts/clang-format.sh

1) `apollo.bashrc` split out from `apollo_base.sh`:  Use the former as a general `.bashrc` file, consisting of functions and enviroment variables for general purpose only.  The later can be used for apollo specific functionalities and settings.
2) Bufix for clang-format.sh: Enhanced check and only lint c/c++/cuda files using clang-format/llvm

Script: apollo.bashrc split out from apollo_base.sh and bugfix for clang-format.sh

---

modules/dreamview/backend/hmi/hmi_worker.cc
modules/dreamview/backend/hmi/hmi_worker.h
modules/guardian/guardian_component.cc
modules/guardian/guardian_component.h
modules/monitor/software/summary_monitor.cc

Since the monitor can crash, it would be nice if there is an indication in dreamview that it wasn't receiving updates.

dreamview times out on system_status

---

cyber/setup.bash

cyber/setup.bash: restore still used bazel-bin/cyber

---

cyber/common/file_test.cc

bazel test as root or non-root will get different result ,all is reasonable.so delete it.

FILE TEST:delete a copyfile test case

---

modules/canbus/vehicle/vehicle_controller.cc

- The member variable driving_mode_ of class VehicleController is accessed
directly in two functions. However, inside SecurityDogThreadFunc() for
each specific vehicle controller, this member variable driving_model_
can be changed if Emergecy() is called.
- There is already a mutex guarded accessor driving_mode() which should be
used instead.
- fixes #10818

[#10818] potential synchronization issue in accessing driving_mode_

---

cyber/common/time_conversion.h
cyber/tools/cyber_recorder/main.cc

can't get a string format from terminal like %Y-%m-%d %H:%M:%S, because space will split it into 2 strings

Cyber: change argument format of cmd cyber_recorder play -b xxx

---

modules/planning/tasks/optimizers/piecewise_jerk_path/piecewise_jerk_path_optimizer.cc

[#11584] dddx_bound is set twice for PiecewiseJerkPathOptimizer

---

modules/calibration/data/dev_kit/cancard_params/canbus.conf
modules/calibration/data/dev_kit/localization_dag/dag_streaming_rtk_localization.dag
modules/dreamview/conf/vehicle_data.pb.txt

1. Add canbus.conf in D-KIT configuration files set
2. D-KIT only support MSF localization mode. As some dreamview hmi mode(RTK, Vehicle calibration) use RTK mode, we need to overwrite the dag with MSF mode.

D-KIT: Update two configuration files of D-KIT

---

modules/calibration/data/dev_kit/cancard_params/canbus.conf
modules/calibration/data/dev_kit/localization_dag/dag_streaming_rtk_localization.dag
modules/dreamview/conf/vehicle_data.pb.txt

* overwrite rtk mode's dag
* D-KIT: Add canbus.conf in configuration file set
* D-KIT: enable_chassis_detail_pub by default
* D-KIT: copy localization dag and canbus.conf

D-KIT: Update two configuration files of D-KIT (#11639)

---

modules/drivers/canbus/can_client/hermes_can/hermes_can_client.h
modules/drivers/canbus/can_client/hermes_can/hermes_can_client_test.cc

By correcting the flag used in destructor.
Cherry-picked from PR for master.

Drivers: fix bug of hermes_can unit test 

---

modules/localization/msf/local_map/lossless_map/BUILD
scripts/apollo_config.sh

Bazel: Enable apollo_config.sh --noninteractive by default

---

docs/cyber/CyberRT_Python_API.md
docs/cyber/CyberRT_Python_API_cn.md

* update examples' paths
* Examples copied from `apollo/cyber/python/cyber_py3/examples/`
* fix typos

Cyber: Update doc for cyber_python from python2 to python3

---

tools/bazel.rc

Since our bazel configuration default to `--config=dbg`, and consider that `unit_test` can be run in `dbg` or `opt` mode. So we'd better make the two (`--config=unit_test` and `-c dbg`) options independent.

Bazel: test:unit_test no longer implies '-c dbg'

---

scripts/apollo_lint.sh

^-- SC2155: Declare and assign separately to avoid masking return values.
https://github.com/koalaman/shellcheck/wiki/SC2155
SC2068: Double quote array expansions to avoid re-splitting elements
https://github.com/koalaman/shellcheck/wiki/SC2068
-- SC1090: Can't follow non-constant source. Use a directive to specify location.
https://github.com/koalaman/shellcheck/wiki/SC1090

apollo_lint: sh lint

---

cyber/proto/BUILD
cyber/proto/clock.proto

This will be used in a follow-up PR to
enable sim_time support for CyberRT.

Add a clock proto to Cyber.

---

scripts/docker_start_user.sh

The grep of ${user_name} in /etc/password will succeed for some user names such as "dev" even if the "dev" user does not exist (due to finding "dev" elsewhere in /etc/password). This will skip calling _create_user_account which will in turn cause dev_into.sh to fail since docker does not like getting a user name. Passing $UID instead of $USER to "docker exec" in dev_into.sh works but then the prompt is wrong because the user doesn't exist.
Fixing the grep to only look at the start of each line (up to ":") in /etc/passwd fixes this, causes the account to actually get created, and allows (docker and) dev_into.sh script to work as expected. Tested several times with user "dev" (where the bug was discovered) and with another non-"dev" user.

Docker: Fix "user exists" test

---

cyber/BUILD
cyber/common/global_data.cc
cyber/common/global_data.h
cyber/common/util.h
cyber/conf/cyber.pb.conf
cyber/cyber.cc
cyber/examples/talker.cc
cyber/init.cc
cyber/node/node.h
cyber/proto/run_mode_conf.proto
cyber/time/BUILD
cyber/time/clock.cc
cyber/time/clock.h
cyber/time/time.cc
cyber/time/time_test.cc

This PR was based on @rongguodong 's request on simulation time support for `CyberRT`.  Cf. #11808 
Env vars and gflags were not used here.  Instead, `cyber/conf/cyber.pb.conf ` was the sole config file for specifying whether system(cyber)-clock or mock-clock should be used.
A clock node was created In `cyber::init` for each process.
Also notice there are `time.h` defs under `modules/common/time`, should we combine all these to provide a unified time model ?

cyber: MockTime mode support

---

cyber/scheduler/policy/scheduler_choreography.cc

review result: 
6 uninit_member: Non-static class member choreography_processor_prio_ is not initialized in this constructor nor in any functions that it calls.
8. uninit_member: Non-static class member pool_processor_prio_ is not initialized in this constructor nor in any functions that it calls

cyber: class member init

---

modules/canbus/vehicle/lincoln/protocol/wheelspeed_6a_test.cc

1. var_decl: Declaring variable timestamp without initializer.

canbus: review to init timeval struct

---

modules/dreamview/conf/hmi_modes/rtk.pb.txt

Reverts ApolloAuto/apollo#11903
test RTK recorder failed.

Revert "Dreamview: change recorder stop_signal to SIGINT in RTK mode"

---

third_party/rtklib/rtkcmn.c

12. uninit_use_in_call: Using uninitialized value pcv. Field pcv.sat is uninitialized when calling addpcv

third_party: zero-initialized pcv_t to pass security check

---

scripts/apollo_build.sh
tools/bazel.rc

With this PR:
`./apollo.sh build` is equivalent to `--config=optimized -c fastbuild`, where the `fastbuild` compilation mode was bazel's default.
`./apollo.sh build_dbg` remains unchanged, equals to `--config=optimized -c dbg`.
`./apollo.sh build_opt` remains unchanged, equals to `--config=optimized -c opt`.
`

Bazel: default to bazel's default compilation mode rather than dbg mode

---

third_party/gpus/cuda/BUILD.tpl
third_party/gpus/cuda/build_defs.bzl.tpl
third_party/gpus/cuda_configure.bzl

`nccl` was not available for aarch64 Jetson boards.
We decide to add `nccl` support in a way similar to how `TensorRT` was introduced.
RTFM: [TensorFlow: third_party/nccl](https://github.com/tensorflow/tensorflow/tree/master/third_party/nccl)

Bazel: revert previous nccl bazel rules as it breaks build on aarch64 

---

modules/drivers/microphone/README
modules/drivers/microphone/README.md
modules/drivers/microphone/microphone_component.cc
modules/drivers/microphone/microphone_component.h
modules/drivers/microphone/respeaker.cc
modules/drivers/microphone/respeaker.h

Not ready
* Sample_width is the number of bytes every sample. I didn't notice that I hardcode them in `microphone_component.cc` 95 as `i` and `i+1` -- originally it was default to be 2. Now I change them to a `for` loop
* Change buffer size from **"_size for all the seconds_"** TO **"_size for only one chunk_"**, reduce startup time by 40% and reduce memory usage.
* Previously, a `for` loop to read all required audio data into buffer (many chunks). Then another `for` loop to copy data in buffer to `bytes` in proto
* Now, one `for` -- read a chunk, copy to buffer, then to `byte` in proto, repeatedly
* Change the way to calculate size.
* refer to readme.
* Fix others like `malloc` to `new`.

Drivers: fix hardcode of sample_width

---

modules/drivers/microphone/conf/respeaker.pb.txt
modules/drivers/microphone/microphone_component.cc

* The firmware of Respeaker was updated to another version that supports higher sample_rate.
* Fix a small fault: `floor` to `ceil`... chunk is not small, it may be better to give a little more instead truncate data

Drivers: Change config of microphone due to firmware update

---

modules/audio/BUILD
modules/audio/audio_component.cc
modules/audio/audio_component.h
modules/audio/common/BUILD
modules/audio/common/audio_info.cc
modules/audio/inference/BUILD
modules/audio/inference/direction_detection.cc
modules/audio/inference/direction_detection.h
modules/drivers/microphone/conf/respeaker.pb.txt
modules/drivers/microphone/proto/microphone_config.proto

* Add direction detection code
* `AudioInfo` Init was not invoked. Besides, we did not have a `microphone_config` to init it at first. So I remove the Init function & get `microphone_config` from `audio_data` dynamically.
* Signal is a signed `int` & due to some C++ weird problem, I change to the line that combines two raw `char` to a `int_16` to `int16_t signal = ((int16_t(data[i])) << 8) | (0x00ff & data[i + 1]);`
* Remove unnecessary symbols suggested by `buildifier`
* Test direction detection

Audio: add audio direction estimation code & fix bugs/lint

---

modules/control/control_component.cc

Control: fix the bug due to the wrong time unit which is cherry-pick from master PR: Control: fix the bug due to the wrong time unit #10659 .

Control: fix the bug due to the wrong time unit which is cherry-pick from master

---

.teamcity/run_ci.sh
docker/scripts/dev_start.sh
modules/contrib/cyber_bridge/README.md
scripts/bridge.sh

To fix error msgs (see below) when running `run_ci.sh` on Teamcity.
```
[INFO] Start pulling docker image apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest ...
19:38:44
map_volume-sunnyvale_with_two_offices-latest: Pulling from apolloauto/apollo
19:38:44
Digest: sha256:5893abb847f7cffb5dd310f9bac307d5c2537797c247eb1c609f36de1943bdf5
19:38:44
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest
19:38:44
docker.io/apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest
19:38:45
docker: Error response from daemon: Conflict. The container name "/apollo_map_volume-sunnyvale_with_two_offices_root" is already in use by container "75897d1962d75147642dfd2c456246cd4150b08568ca3eb471f31dfd067999c3". You have to remove (or rename) that …
```

Build: reuse or start volumes for CI run

---

modules/perception/production/conf/perception/lidar/velodyne128_detection_conf_lgsvl.pb.txt
modules/perception/production/conf/perception/lidar/velodyne64_detection_conf.pb.txt
modules/perception/production/dag/dag_streaming_perception_lgsvl.dag

Set `lidar_query_tf_offset` 200 in velodyne 128 detection for lgsvl, to solve the problem of matching timestamps.

Perception: add conf for lgsvl dag

---

modules/audio/common/audio_info.cc
modules/audio/inference/direction_detection.cc
modules/audio/tools/audiosaver.py

* Fix a bug that it is small endianness when assembling bytes.
* Since the frequency is increased, the duration of a single wave is too small. I pack them together. When finish playing the record, use ctrl+c to stop the audio saver program and it will save all frames to a wave file.

Audio: fix bugs & improve audio saver

---

cyber/record/record_writer.cc
cyber/record/record_writer.h

When `RecordWriter` calls `RecordFileWriter::Close`, it has to write out its data. There's a sleep in there for 100ms, if it doesn't write fast enough. during that time new messages are coming in. If too many messages come in, cyber's callback threads will be exhausted and messages will be stuck in the queue. The result is messages with the same received timestamp.
This proposed solution is to put the destructor call on another async task. The next time the file is split, the previous async operation cleaned up and a new async operation is created via `~future()` and `async` operation respectively. Similarly, std::future will clean itself up on `~RecordWriter`.

cyber_recorder close file asynchronously

---

apollo.sh
docker/scripts/cyber_start.sh
docker/scripts/dev_start.sh
scripts/apollo.bashrc
scripts/apollo_build.sh
scripts/apollo_config.sh
scripts/apollo_coverage.sh
scripts/apollo_test.sh
third_party/libtorch/libtorch_gpu.BUILD
tools/apollo.bazelrc.sample
tools/bazel.rc
tools/platform/BUILD

Build: improved CPU/GPU build/test/coverage support
1) Introduce USE_GPU_TARGET (inside docker) to determine if device/tools/libraries is ready to be GPU capable
2) Use of USE_GPU_HOST now only in cyber|dev_start.sh
For build,
1) Mixed used of '--config=cpu' and '--config=gpu' not allowed
2) Make CPU build (i.e., '--config=cpu') on GPU capable machine possible
3) Error and exit attempting to run GPU build (`--config=gpu`) on CPU-only machines
4) Default to USE_GPU_TARGET if none of cpu|gpu build specified
Build: --config=cpu/gpu not written into .apollo.bazelrc
{cyber|dev}_start.sh: introduce EnvVar USE_GPU_HOST
Bazel: bugfix for libtorch_gpu.BUILD
Bazel: bugfix for USE_GPU to accord with bazelrc settings

Build: Improved CPU & GPU build/test/coverage support

---

scripts/bootstrap.sh

When the proxy is set for docker, it may defeat the curl testing used in the scripts/bootstrap.sh for obtaining the HTTP status code. OTOH, the  dreamview is running on localhost, which really don't need proxy for connection to. 
See here for more discussions on the relative problem:
https://github.com/ApolloAuto/apollo/issues/12285#issuecomment-682435918

Disable the possible proxy for curl when obtaining the HTTP status code in the scripts/bootstrap.sh

---

WORKSPACE

To speed up download speed and decrease Error situation,add bos to download.
if this change is OK, more will be modified in third party.

bazel dependency: add bos to download

---

modules/perception/radar/common/types.h
modules/perception/radar/lib/preprocessor/conti_ars_preprocessor/conti_ars_preprocessor.cc
modules/perception/radar/lib/preprocessor/conti_ars_preprocessor/conti_ars_preprocessor.h

Enable the Conti Radar pre-processor to handle obstacles ids in the whole range int32 (previously only in the range 0-99).
This fix enable the use of LGSVL's RADAR for obstacle detection.

Improve Conti radar preprocessor.

---

modules/drivers/hesai/BUILD
modules/drivers/hesai/driver.h
modules/drivers/hesai/hesai40_parser.cc
modules/drivers/hesai/hesai40_parser.h
modules/drivers/hesai/hesai64_parser.cc
modules/drivers/hesai/hesai64_parser.h
modules/drivers/hesai/hesai_component.cc
modules/drivers/hesai/hesai_component.h
modules/drivers/hesai/hesai_convert_component.cc
modules/drivers/hesai/hesai_convert_component.h
modules/drivers/hesai/parser.cc
modules/drivers/hesai/parser.h
modules/drivers/hesai/parser_factory.cc
modules/drivers/hesai/parser_factory.h
modules/drivers/hesai/tcp_cmd_client.cc
modules/drivers/hesai/type_defs.h
modules/drivers/hesai/udp_input.cc

Demo PR to show Best Practices on Building C++ with Bazel.
1) Avoid using "using xxx;"  in header files.
2) Split targets into smaller ones, as described here: https://docs.bazel.build/versions/master/bazel-and-cpp.html#build-files
3) Shared `HESAI_COPTS` variable, See: https://docs.bazel.build/versions/master/skylark/tutorial-sharing-variables.html
4) Include necessary headers **ONLY**
5) Prefer C++ headers to C headers. E.g., using `<ctime>` rather than `<time.h>`
6) Pay attention to header orders. Run `scripts/apollo_format.sh modules/drivers/hesai` to format C/C++ files and BAZEL BUILD files.
7) Don't Over/Under estimate your dependency. No more, No less
8) Using `scripts/mdfmt.sh path/or/file` to format markdown/json/yaml files.
@xiaoxq @changsh726 @lfcarol @lx18233184051 @Capri2014 …

Best practice Hesai Driver

---

modules/drivers/velodyne/fusion/pri_sec_fusion_component.cc

Solve two bugs :
1. "/apollo/sensor/lidar16/front/center/Scan" and "/apollo/sensor/lidar16/front/center/PointCloud2" message frequency inconsistency.
2. When the "driver/velodyne" runs for long time, the messages "/apollo/sensor/lidarXXX/compensator/PointCloud2" don't output.

Drivers: fix bug about lidar messages

---

scripts/apollo_base.sh
scripts/camera.sh
scripts/camera_and_video.sh
scripts/lidar_calibration.sh
scripts/navigation_usb_camera.sh
scripts/record_bag.py
scripts/record_bag.sh
scripts/record_bag_local.sh
scripts/record_bag_navigation_perception.sh
scripts/record_bag_pnc.sh
scripts/record_bag_sensor.sh
scripts/record_map_data.py
scripts/record_map_data.sh
scripts/record_message.py
scripts/rtk_player.sh
scripts/rtk_recorder.sh
scripts/sensor_calibration.sh
scripts/transform.sh
scripts/velodyne.sh
scripts/velodyne_16.sh
scripts/velodyne_for_map_data_colloector.sh

Apollo uses `pgrep -c -f` to determine if processes are running. Unfortunately, this finds them in the inline container startup command. This is a problem when we try to run Apollo in our own container on cloud where the container startup command contains some strings matching Apollo's pgrep string.
This change uses of `pgrep -f` to ignore when PID 1 is output by filtering the output with `| grep -v '^1$'`, and use `| wc -l` to count the lines of the output.

Change scripts which use "pgrep" to avoid PID 1.

---

apollo.sh

When building apollo as opt method on arm platform, should change `-fpic` to `-fPIC` or will failed. 
Reasons below:
```
-fpic Generate position-independent code (PIC) suitable for use in a shared library, if supported for the target machine. Such code accesses all constant addresses through a global offset table (GOT). The dynamic loader resolves the GOT entries when the program starts (the dynamic loader is not part of GCC; it is part of the operating system). If the GOT size for the linked executable exceeds a machine-specific maximum size, you get an error message from the linker indicating that -fpic does not work; in that case, recompile with -fPIC instead. (These maximums are 8k on the SPARC, 28k on AArch64 and 32k on the m68k and RS/6000. The x86 has no such limit.) …
```

Update apollo.sh fix bug

---

cyber/tools/cyber_monitor/cyber_topology_message.cc
cyber/tools/cyber_monitor/cyber_topology_message.h
cyber/tools/cyber_monitor/general_channel_message.cc
cyber/tools/cyber_monitor/general_channel_message.h
cyber/tools/cyber_monitor/general_message.cc
cyber/tools/cyber_monitor/general_message.h
cyber/tools/cyber_monitor/general_message_base.cc
cyber/tools/cyber_monitor/general_message_base.h
cyber/tools/cyber_monitor/renderable_message.h
cyber/tools/cyber_monitor/screen.cc
cyber/tools/cyber_monitor/screen.h

Currently, cyber_monitor's highlighted bar can be located anywhere on the terminal as shown below, which is unreasonable.
In this PR, the location of the highlighted bar is restricted to where there is content.

Cyber: improve the visual effect for cyber_monitor

---

docker/build/installers/install_qa_tools.sh
docker/build/installers/install_shellcheck.sh

To apply the new features only available in recent versions of shellcheck.

Docker: installer for latest shell-check binaries

---

cyber/BUILD
cyber/binary.cc
cyber/common/log.h
cyber/init.cc

There's some potential threading problems when using the header only binary library. I separated the header and the source file to hide the mutex header and added a mutex. The problems are reported by running a threading sanitizer.

Cyber: binary threading fixes

---

cyber/record/file/record_file_base.h
cyber/record/file/record_file_test.cc
cyber/record/file/record_file_writer.cc
cyber/record/file/record_file_writer.h
cyber/record/record_viewer_test.cc
cyber/record/record_writer.cc
cyber/record/record_writer.h
tools/bazel.rc

There is a threading bug in record_file_writer.cc. The problem is that it doesn't wait for the flush to be fully swapped before swapping.
There are some examples of how this can be done
1. https://web.stanford.edu/~ouster/cgi-bin/cs140-spring14/lecture.php?topic=locks#:~:text=Condition%20variables%3A%20used%20to%20wait,re%2Dacquire%20lock%20before%20returning.
2. https://github.com/eProsima/Fast-DDS/blob/e66790bf080b5c66f2c3a70c547e0b6122b83560/src/cpp/fastdds/log/Log.cpp#L110-L143
Since the event happens in tens of seconds and the time to start a thread may be in microseconds, I chose to go with `std::async` for simplicity.
You can reproduce the problem with
```
bazel build -c dbg --copt -fsanitize=thread --linkopt -fsanitize=thread //cyber/record:record_viewer_test
```
Note that you …

Cyber: cyber_recorder file writer threading bug fix

---

WORKSPACE

@lx18233184051 Please help with  hosting https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz on https://apollo-platform-system.cdn.bcebos.com/archive/6.0/bazel_skylib-1.0.3.tar.gz , thank you.

Bazel: bump bazel-skylib to 1.0.3

---

scripts/proto_build_generator.py

Based on @QIU1995NONAME 's previous work with changes:
1) escape `\(` only
2) remove regex match for extra spaces as
i) the line was already stripped
ii) no extra spaces are allowed in our proto files.

Scripts: update proto_build_generator

---

modules/perception/production/conf/perception/perception_common.flag

To reduce missing obstacles when running lidar perception module with 128c Lidar driver.

Perception: change a default setting

---

modules/contrib/cyber_bridge/client.cc
modules/contrib/cyber_bridge/client.h

Existing bridge cannot handle messages larger than 65536 bytes. More details see https://github.com/lgsvl/simulator/issues/941.
This MR implemented the solution suggested by Yun and Martins on GitHub. If the big message is published at high frequency, the pending buffer may accumulate more and more data. To avoid too much accumulated data, I set a max size of 1GB and discard the pending buffer if its size is larger than the max size.

Use two buffers to handle message larger than 65536 bytes.

---

modules/perception/production/dag/dag_streaming_perception.dag
modules/perception/production/dag/dag_streaming_perception_lgsvl.dag
modules/perception/production/dag/dag_streaming_perception_lidar.dag

1. Remove redundant Velodyne16 Detection Component to release GPU memory.
2. Adjust dags' format.

Perception: simplify dag to release GPU memory

---

scripts/apollo_auto_complete.bash

Good job of @changsh726  to provide us with bash completion support for `apollo.sh` !

Scripts: remove hard-coded modules in apollo_auto_completion.bash

---

cyber/setup.bash

Fix debug glog config in setup.bash, glog can't set LogSeverityto -1, detail discuss in #12723

cyber: fix debug glog config in setup.bash

---

modules/canbus/proto/ch.proto
modules/canbus/proto/chassis.proto
modules/canbus/proto/devkit.proto
modules/canbus/vehicle/ch/ch_controller.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.h
modules/canbus/vehicle/ch/protocol/ecu_status_2_516_test.cc
modules/canbus/vehicle/devkit/devkit_controller.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h
modules/canbus/vehicle/devkit/protocol/vcu_report_505_test.cc

Which are cherry-picked from master:
add the new battery soc info in chassis for vehicle dev_kit
add the battery info in vehicle ch (#12900)

Canbus: add the battery soc info in vehicle ch and dev_kit

---

cyber/component/BUILD
cyber/record/file/record_file_test.cc
modules/common/math/kalman_filter_test.cc
modules/control/submodules/BUILD
modules/control/submodules/preprocessor_submodule.h
modules/map/hdmap/hdmap_impl_test.cc
modules/perception/onboard/transform_wrapper/transform_wrapper.h
third_party/glog/glog.BUILD
third_party/glog/workspace.bzl

Build: glog_library(with_gflags=0) to workaround glog coredump issue

---

cyber/BUILD
cyber/common/BUILD
modules/dreamview/backend/map/BUILD
modules/localization/msf/BUILD
modules/localization/msf/common/util/BUILD
modules/localization/msf/local_integ/BUILD
modules/localization/msf/local_pyramid_map/base_map/BUILD
modules/localization/msf/local_pyramid_map/ndt_map/BUILD
modules/localization/msf/local_pyramid_map/pyramid_map/BUILD
modules/localization/ndt/BUILD
modules/localization/ndt/ndt_locator/BUILD
modules/map/hdmap/BUILD
modules/map/hdmap/adapter/BUILD
third_party/glog/workspace.bzl

To accord with its upstream name: https://github.com/google/glog#bazel

Build: package com_google_glog renamed to com_github_google_glog

---

WORKSPACE
cyber/BUILD
cyber/io/BUILD
cyber/python/internal/BUILD
cyber/sysmo/BUILD
cyber/task/BUILD
cyber/timer/BUILD
cyber/transport/BUILD
cyber/transport/common/BUILD
cyber/transport/dispatcher/BUILD
cyber/transport/integration_test/BUILD
cyber/transport/message/BUILD
cyber/transport/rtps/BUILD
cyber/transport/shm/BUILD
dist/BUILD
dist/README.md
scripts/apollo_build.sh

1) created a top-level directory `dist` to host release-build related bazel rules and scripts. An advantage of this approach is to not mess up with existing Bazel rules.
2) Each module (cyber, perception, planning, etc.) should have its own section in the BUILD file under the `dist` directory. 
All useful binaries, shared/static libraries, config/data files, setup scripts, should be packaged together under the name `modname-dist`.
3) With this PR, you can now generate apollo-dist.tar, cyber-dist.tar under `./bazel-bin/dist` directory with a single comman: 
```
./apollo.sh build dist
```
To check if the binaries, shared libraries, are self content, just run `ldd my_binary/libmy_lib.so` to see that it didn't depend on extra libs/symbols from Apollo.
Run each binary with relative configs to …

Release build: framework/first attempt on release build

---

docs/specs/prerequisite_software_installation_guide.md

The current command for the installation of NVIDIA container toolkit has been changed into the following:
`
$ sudo apt-get install -y nvidia-docker2`
See [the official document](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit) and this [discussion](https://github.com/NVIDIA/nvidia-docker/issues/1407) filed on nvidia-docker issues list for more info.

Use the nvidia-docker2 package for the installation/setting of the NVIDIA container toolkit.

---

modules/calibration/data/dev_kit_advanced_sne-r/localization_conf/localization.conf

correct default lidar_extrinsics_file in localization_conf

D-KIT: correct default lidar_extrinsics_file in localization_conf

---

modules/calibration/data/dev_kit_advanced_sne-r/localization_conf/localization.conf

correct default lidar_extrinsics_file in localization_conf

D-KIT: correct default lidar_extrinsics_file in localization_conf 

---

docker/build/installers/install_pcl.sh
docker/build/installers/installer_base.sh
modules/perception/camera/app/BUILD
modules/task_manager/BUILD

Please don't use `//external:gflags` to specify build dependencies.

Build: removed non-existent CUDA SM=7.2 for x86_64 

---

modules/dreamview/frontend/yarn.lock

Since the dependabot can't sign our CLA ... lol.

Security: Bump ini from 1.3.5 to 1.3.8 in /modules/dreamview/frontend by buildabot

---

WORKSPACE

upstream `py_repositories` and `pip_repositories` rule(s) were no-op/deprecated since  rules_python 0.0.2/0.1.0.

Bazel: updated WORKSPACE for rules_python

---

modules/perception/fusion/app/obstacle_multi_sensor_fusion.cc
modules/perception/fusion/app/obstacle_multi_sensor_fusion.h
modules/perception/fusion/lib/data_association/hm_data_association/hm_tracks_objects_match.cc
modules/perception/fusion/lib/dummy/dummy_algorithms.cc
modules/perception/fusion/lib/dummy/dummy_algorithms_test.cc
modules/perception/fusion/lib/fusion_system/probabilistic_fusion/probabilistic_fusion.cc
modules/perception/fusion/lib/fusion_system/probabilistic_fusion/probabilistic_fusion_test.cc
modules/perception/fusion/lib/gatekeeper/pbf_gatekeeper/pbf_gatekeeper.cc
modules/perception/fusion/lib/interface/base_fusion_system.h
modules/perception/onboard/component/fusion_component.cc
modules/perception/onboard/component/fusion_component.h
modules/perception/onboard/proto/fusion_component_config.proto
modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt
modules/perception/production/conf/perception/fusion/fusion_component_conf.pb.txt
modules/perception/production/dag/dag_motion_service.dag
modules/perception/production/dag/dag_streaming_perception.dag
modules/perception/production/dag/dag_streaming_perception_lane.dag
modules/perception/production/dag/dag_streaming_perception_lgsvl.dag
modules/perception/production/dag/dag_streaming_perception_lidar.dag
modules/perception/production/dag/dag_streaming_perception_lidar_segmentation.dag
modules/perception/production/launch/perception.launch
modules/perception/production/launch/perception_all.launch

1. Enable Camera & Lidar fusion.
2. Add camera obstacle detection to Perception module's default dag.

Perception: resume camera obstacle detection in sensor fusion

---

modules/tools/vehicle_calibration/data_collector.py

When input a command like "15 2 -20", the car will accelerate first, then decelerate and stop at last , then exit the loop and waiting for the next command. But the `self.case` is `d` and not init to 'a' again. when we input the next command because the d-kit's speed is 0, it will enter the `case d` and immediately exit!!!
when we input the next command init the `self.case` to `a`.

tools: fix bug for cannot input command multi times

---

docker/scripts/dev_start.sh

When stopping containers using `dev_start.sh stop`, the following message appears: 'Error: No such container:'
```bash
$ docker/scripts/dev_start.sh stop
[INFO] Now stop container apollo_dev_user ...
[INFO] Done.
[INFO] Now stop container apollo_smoke_volume_user ...
Error: No such container: apollo_smoke_volume_user
[INFO] Done.
[INFO] Now stop container apollo_faster_rcnn_volume_user ...
Error: No such container: apollo_faster_rcnn_volume_user
...
```

Docker: Hide message 'Error: No such container:'

---

cyber/class_loader/shared_library/shared_library.cc
cyber/class_loader/shared_library/shared_library.h
docker/build/installers/install_dreamview_deps.sh

@daohu527 
@JackFu123 
Without this PR, running `mainboard -d modules/planning/dag/planning.dag` will complains:
```text
INTEL MKL ERROR: /usr/local/lib/libmkl_avx2.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

Cyber: bugfix for dlopen operations in SharedLibrary impl

---

modules/calibration/data/dev_kit/planning_conf/planning_config.pb.txt
modules/calibration/data/dev_kit_advanced_ne-b/planning_conf/planning_config.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/planning_conf/planning_config.pb.txt
modules/calibration/data/dev_kit_advanced_sne-r/planning_conf/planning_config.pb.txt
modules/calibration/data/dev_kit_standard/planning_conf/planning_config.pb.txt

modify planning configs to make vehicle follow the center of the road by default

D-KIT: modify planning configs

---

docker/build/build_docker.sh

There is no `-b `argument, but the example specifies it:
```bash
...
echo "${TAB}${prog} -f dev.aarch64.dockerfile -m download -b testing"
...
```
Must be fixed to` -d`

Docker: Fix typo into build_docker.sh

---

docker/build/build_docker.sh

It is convenient to specify cyber image timestamp when dev image building, rather than hard code it into script.

Docker: Add cyber image timestamp argument for dev stage

---

docker/build/installers/install_doxygen.sh

When I try to install the doxygen package using the install_doxygen.sh script, an error occurs:
```bash
[INFO] Start to download doxygen-1.8.19.src.tar.gz from http://doxygen.nl/files/doxygen-1.8.19.src.tar.gz ...
--2021-02-04 09:59:13--  http://doxygen.nl/files/doxygen-1.8.19.src.tar.gz
Resolving doxygen.nl (doxygen.nl)... 195.5.163.171
Connecting to doxygen.nl (doxygen.nl)|195.5.163.171|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.doxygen.nl/files/doxygen-1.8.19.src.tar.gz [following]
--2021-02-04 09:59:13--  https://www.doxygen.nl/files/doxygen-1.8.19.src.tar.gz
Resolving www.doxygen.nl (www.doxygen.nl)... 195.5.163.171
Connecting to www.doxygen.nl (www.doxygen.nl)|195.5.163.171|:443... connected.
HTTP request sent, awaiting …
```

Docker: Change doxygen package version to find resource

---

docker/build/installers/install_opencv.sh

The errors occurs when installing GPU enabled OpenCV package:
1. `# bash install_opencv.sh gpu`
```bash
...
/tmp/installers/opencv-4.4.0 /tmp/installers
CMake Error: The source directory "/tmp/installers/opencv-4.4.0/build/8.6"" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```
2. `# bash install_opencv.sh gpu`
```bash
...
CMake Error at modules/core/CMakeLists.txt:40 (message):
CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
repository: https://github.com/opencv/opencv_contrib
```

Docker: Fix errors when installing GPU-enabled OpenCV package

---

modules/calibration/data/dev_kit/perception_launch/dev_kit_perception_lidar.launch
modules/calibration/data/dev_kit_advanced_ne-b/perception_launch/dev_kit_perception_lidar.launch
modules/calibration/data/dev_kit_advanced_ne-s/perception_launch/dev_kit_perception_lidar.launch
modules/calibration/data/dev_kit_advanced_sne-r/perception_launch/dev_kit_perception_lidar.launch
modules/calibration/data/dev_kit_standard/perception_launch/dev_kit_perception_lidar.launch
modules/drivers/lidar/velodyne/launch/velodyne128.launch
modules/drivers/lidar/velodyne/launch/velodyne16.launch
modules/drivers/lidar/velodyne/launch/velodyne64_16.launch
modules/perception/production/launch/perception.launch
modules/perception/production/launch/perception_all.launch
modules/perception/production/launch/perception_lidar.launch
modules/perception/production/launch/perception_trafficlight.launch
modules/perception/production/launch/perception_trafficlight_viz.launch

fix error  in `modules/drivers/lidar/velodyne/launch` 
Uniform and standardized naming 
```
lidar_perception to perception_lidar
perception_traffic_light to perception_trafficlights
```

config: fix error in modules\drivers\lidar\velodyne\launch and improve other launch

---

modules/map/relative_map/navigation_lane.cc
modules/planning/navi_planning.cc

ego_info should be updated before initframe(). Because in initframe(), it will use ego_info->ego_box() to find collision obstacles. Otherwise it will get errors at first frame running.

[Planning]Update navi_planning.cc

---

scripts/docker_start_user.sh

The tricky part with setting core dump path under `/apollo` is as follows:
Changing core pattern inside Docker will change also that on the host. However, there may not exist a top level directory named `/apollo`.
Of course we can change core pattern to something like `/tmp/core/core_%e.%p`, which will be lost when Apollo container restarts.
What's your opinion? @zhoujie5517 @xiaoxq

Scripts: re-enable buggy core pattern

---

scripts/docker_start_user.sh

Fix https://github.com/ApolloAuto/apollo/pull/13622
Without this, it seems to fail on host
```
---> Running in 427e7861043d
Adding group `apollo' (GID 1001) ...
Done.
Adding user `apollo' ...
Adding new user `apollo' (1001) with group `apollo' ...
Creating home directory `/home/apollo' ...
Copying files from `/etc/skel' ...
/apollo/scripts/docker_start_user.sh: line 96: /proc/sys/kernel/core_pattern: Read-only file system
The command '/bin/sh -c /apollo/scripts/docker_start_user.sh' returned a non-zero code: 1
```

scripts: write core_pattern only when it's writable

---

modules/common/vehicle_state/vehicle_state_provider.cc
modules/control/controller/lon_controller.cc

The vehicle coordinates of Apollo are as [link](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/coordination_cn.md)
And you can find in localzation module
https://github.com/ApolloAuto/apollo/blob/770eba2024ceca51f6e771fe9caa6f42ad66eaa7/modules/localization/ndt/ndt_localization.cc#L287-L289

control: fix vehicle_state pitch error

---

modules/perception/inference/tensorrt/plugins/BUILD

This option was needed to build apollo simulator.

perception: fix linking issue

---

modules/control/controller/lon_controller.cc
modules/control/controller/mpc_controller.cc

If `chassis->gear_location() == trajectory_message_->gear()` then we don't need to change the gear, so we can simplify the judgment condition

control: delete redundant judgment conditions in set_gear_location

---

modules/dreamview/backend/map/map_service.cc

Fix [IDG-Apollo-4319].
Limit "s" of laneWayPoint with max value of the length of the lane. If
laneWayPoint->s > lane.length(), the BinarySearchCheckValidSIndex will
fail and thus cause routing failed.

Dreamview: Limit "s" of laneWayPoint.

---

modules/dreamview/backend/map/map_service.cc
modules/dreamview/frontend/src/store/hmi.js
modules/monitor/common/monitor_manager.cc

Dreamview: The size of vehicle doesn't display correctly.
Monitor: Ignore safety check when using SimControl.

Fix vehicle display bug and ignore safety check when using SimControl.

---

modules/localization/msf/local_tool/data_extraction/cyber_record_parser.cc
modules/localization/msf/local_tool/data_extraction/cyber_record_reader.cc
modules/localization/msf/local_tool/data_extraction/cyber_record_reader.h

cyber_record_parser can only decompress one file, add the function of decompressing multiple files.
Because the recorded bag is cut according to 60s, if the recording time exceeds 60s, we need to decompress multiple files

localization: cyber_record_parser add decompresses multiple files

---

BUILD
modules/common/BUILD
modules/common/vehicle_model/BUILD

* add another BUILD in modules/common
* install /apollo/modules/common/vehicle_model/conf/vehicle_model_config.pb.txt
because without it, the Planning module fails to run in Release Build with:
```
W0527 13:22:21.034180 169970 protobuf_factory.cc:218] [modules/perception/proto/traffic_light_detection.proto] A file with this name is already in the pool.
E0527 13:22:32.143956 169769 on_lane_planning.cc:147] Failed to create reference line
E0527 13:22:32.143985 169769 on_lane_planning.cc:313] PLANNING_ERROR: Failed to create reference line
E0527 13:22:39.902437 169767 trajectory_stitcher.cc:208] the distance between matched point and actual position is too large. Replan is triggered. lon_diff = 2.7352
E0527 13:22:39.902480 169767 file.cc:73] Failed to open file …
```

Release Build: Installation ready for modules/common/vehicle_model

---

modules/map/hdmap/hdmap_common.cc
modules/map/pnc_map/pnc_map.cc
modules/planning/on_lane_planning.cc
modules/planning/tasks/deciders/open_space_decider/open_space_roi_decider.cc
modules/planning/tasks/deciders/open_space_decider/open_space_roi_decider.h
modules/routing/routing.cc
modules/routing/routing.h

Fix $[IDG-Apollo-4346].
When the vehicle is in front of the parking spot, and on the lane next
to the nearest lane to the parking spot, the parking action will fail
because of the following error:
Failed to extract segments from routing.
and the relative error of pnc map like:
Failed to find nearest point: x: 437868.09950172278 y: 4433040.1114324955 z: 0
Cause:
The lane segments of the routing response don't contain the lane nearest
to the parking spot because the vehicle is in front of the parking spot.
When the vehicle approach to the parking spot, no project point can be
found on the routing segments and thus CreateReferenceLine failed.
Solution:
1. Add SupplementParkingRequest function. When the routing segements
doesn't contain the lane nearest to the parking spot, add it into the …

Routing: Fix bug of vertical parking failure.

---

modules/canbus/common/BUILD
modules/canbus/vehicle/ch/BUILD
modules/canbus/vehicle/devkit/BUILD
modules/canbus/vehicle/ge3/BUILD
modules/canbus/vehicle/gem/protocol/BUILD
modules/canbus/vehicle/lexus/protocol/BUILD
modules/canbus/vehicle/lincoln/protocol/BUILD
modules/canbus/vehicle/neolix_edu/BUILD
modules/canbus/vehicle/wey/BUILD
modules/canbus/vehicle/zhongyun/BUILD
modules/planning/BUILD

Add MODULE_NAME definitions so that the relative log can be written in the log of the module instead of mainboard.

chore: Add MODULE_NAME definitions in BUILD file.

---

modules/planning/on_lane_planning.cc
modules/planning/reference_line/reference_line_provider.cc

Fix [IDG-Apollo-4289].
Sometimes routing succeeds but no planning trajectory shows up and the
vehicle won't move. In the planning.log output error like the following:
Failed to find nearest point: ***
Rebooting the planning module will resolve this problem.
Cause:
The function reference_line_provider_->UpdateVehicleState will be nerver
invoked once the ReferenceLineProvider::CreateRouteSegments failed
caused by the wrong vehicle state(Usually the vehicle state is not
updated yet by the SimControl for the sequential factor). And this will
make the failure of ReferenceLineProvider::CreateRouteSegments into an
endless loop. Only rebooting the planning module can resolve this
problem.
Solution:
Change the order of invoking
reference_line_provider_->UpdateVehicleState to remove the endless …

Planning: Planning failed when routing succeeded.

---

modules/dreamview/backend/simulation_world/simulation_world_updater.cc

Dreamview: Remove heading check of end point.
The heading of the end point is added by mistake in previous commit.
It should be reverted because the id of the end point will be calculated
for parking action and it is unnecessary to check the heading in this
case.

Dreamview: Remove heading check of end point.

---

modules/control/common/pid_controller.cc
modules/control/common/pid_controller.h
modules/control/controller/lon_controller.cc

Control: Reset integral when GEAR_NEUTRAL or full_stop.
Fix [IDG-Apollo-4329].
Move too fast after shifting or when entering self-driving.
Cause:
After shifting or entering autonomous driving, no integral zeroing
is carried out, resulting in excessive initial control when re-entering control
Solution:
Reset integral when GEAR_NEUTRAL or full_stop.
Control: Reset the Station PID after switching from reverse to forward.
Fix [IDG-Apollo-4330].
The Station PID parameter is reset in reverse gear, but the Station PID
is not reset after switching from reverse to forward, only the Speed PID
parameter is reset
Solution:
Reset the Station PID after switching from reverse to forward

Control:add set station PID and reset integral

---

modules/control/controller/lon_controller.cc

Control:Reset the Station PID after switching from reverse to forward
Fix [IDG-Apollo-4330].
The Station PID parameter is reset in reverse gear, but the Station PID
is not reset after switching from reverse to forward, only the Speed PID
parameter is reset
Solution:
Reset the Station PID after switching from reverse to forward

control:add ADCTrajectory SPEED_FALLBACK when full_stop.

---

modules/control/common/pid_controller.cc
modules/control/common/pid_controller.h
modules/control/controller/lon_controller.cc
modules/localization/msf/msf_localization.cc
modules/localization/msf/msf_localization.h

Control: add ADCTrajectory SPEED_FALLBACK when full_stop.
Control: Reset integral when GEAR_NEUTRAL or full_stop. 
Control:Reset the Station PID after switching from reverse to forward.
Localization: Compensate the translation between imu and center.

Improve control performance and compensate imu translation for localization.

---

modules/dreamview/backend/simulation_world/simulation_world_service.cc
modules/task_manager/task_manager_component.cc

Fix: [IDG-Apollo-4349].
The routing module receives wrong RoutingRequest history when do the
following steps:
1. Send a normal RoutingRequest along the road from a start to end
point, wait util the planning finishes.
2. Send a ParkingRoutingRequest and shutdown the planning and routing
module, make sure the routing segment of the parking routing doesn't
coincide with that of the first normal RoutingRequest.
3. Reboot the planning and routing module.
The planning module will do the planning without click the button of
"Send Routing Request" but fail. Because the routing module will receive
2 RoutingRequest at this time. The first is the ParkingRoutingRequest
and the second is the normal RoutingRequest.
Cause:
The normal RoutingRequest and ParkingRoutingRequest are sent seperately
with 2 …

Routing: Routing module receives wrong RoutingRequest history.

---

modules/drivers/lidar/lidar_driver_component.cc

`LidarDriverFactory::Instance()->CreateLidarDriver` may return nullptr.
```
std::unique_ptr<LidarDriver> LidarDriverFactory::CreateLidarDriver(
const std::shared_ptr<::apollo::cyber::Node>& node,
const apollo::drivers::lidar::config& parameter) {
auto factory = CreateObject(parameter.brand(), node, parameter);
if (!factory) {
AERROR << "Failed to create lidar with parameter: "
<< parameter.DebugString();
}
return factory;
}
```

Drivers:fix  a potential null pointer problem

---

modules/tools/navigator/BUILD

In Apollo 6.0 and master, Python scripts was managed by Bazel.
However, The `record_extractor.py` script was not built by Bazel.
So in the `modules/tools/navigator/BUILD` files,  the building rule of  `record_extractor. py` script should be added

[tools]The record_extractor.py script was not built

---

tools/bootstrap.py

If we specify `--repository_cache` for the `build` command rather than
a `common` option, commands like `bazel sync` will not respect the
settings there.
Ref:
https://docs.bazel.build/versions/main/guide.html#option-defaults

Bazel: unified --repository_cache for bazel sync

---

cyber/transport/shm/BUILD

`condition_notifier_test` uses shared memory and can't run in parallel with other tests. This change adds an "exclusive" tag to the bazel BUILD file to prevent it from running with other tests at the same time. Please refer:
https://docs.bazel.build/versions/main/test-encyclopedia.html#tag-conventions
Signed-off-by: hans <hans@dkmt.io>

[cyber] fix: add "exclusive" tag to condition_notifier_test

---

modules/control/controller/lon_controller.cc

According to the steering wheel corner feedback, if the steering
is not in place, the throttle and brakes are not output.
Fix [IDG_Apollo-4395].
When the steering wheel is not in place, the trolley starts to move,
which is prone to lateral error
Cause:
In the parking phase, when switching from forward to backward,
it is generally necessary to turn the steering wheel in the opposite
direction, but the steering wheel angle is not considered in the
longitudinal direction. Once switching to the backward track,
the vehicle will immediately reverse. At this time, the steering wheel
is not in place, resulting in lateral error.
Solution:
According to the steering wheel corner feedback, if the steering
is not in place, the throttle and brakes are not output.

Control:According to the steering wheel corner feedback, if the steering is not in place, the throttle and brakes are not output.

---

modules/control/controller/lon_controller.cc

Control:According to the steering wheel corner feedback, if the steering is 
not in place, the throttle and brakes are not output.
Fix [IDG_Apollo-4395].
When the steering wheel is not in place, the trolley starts to move,
which is prone to lateral error
Cause:
In the parking phase, when switching from forward to backward,
it is generally necessary to turn the steering wheel in the opposite
direction, but the steering wheel angle is not considered in the
longitudinal direction. Once switching to the backward track,
the vehicle will immediately reverse. At this time, the steering wheel
is not in place, resulting in lateral error.
Solution:
According to the steering wheel corner feedback, if the steering
is not in place, the throttle and brakes are not output.

Control:Fix bug

---

modules/bridge/udp_bridge_multi_receiver_component.h

fix class load error in "udp_bridge_multi_receiver_component.h"

bridge: fix class load error

---

modules/planning/tasks/optimizers/piecewise_jerk_path/piecewise_jerk_path_optimizer.cc
modules/planning/tasks/optimizers/piecewise_jerk_path/piecewise_jerk_path_optimizer.h

Planning: replace the first input of EstimateJerkBoundary, from dl/ds to ds/dt.
this fix refers to the issue [EstimateJerkBoundary input value error #14208
](https://github.com/ApolloAuto/apollo/issues/14208)

correct jerk boundary estimate in planning module

---

WORKSPACE

Change-Id: Ie9b38d91bd11410bc78a2d48e676234f35b51816

ZLIB: version bug fix

---

cyber/record/file/record_file_reader.cc
cyber/record/file/record_file_reader.h

RecordFileReader doesn't automatically close underlying fd on destructing, this will cause a fd leak.

fix fd leak in RecordFileReader

---

modules/bridge/common/bridge_proto_diserialized_buf.h

当我使用Apollo的bridge模块测试数据的接收与发送时，发现了一个问题：当客户端发送单帧数据时，服务端可以顺利解析并发布到相关的话题，但是当protobuf数据过大，需要客户端将protobuf数据分为多帧进行发送时，服务端却无法将接收数据并发送至相关话题。
经过排查，发现`BridgeProtoDiserializedBuf`的数据成员`sequence_num_`和`proto_name_`没有进行初始化，导致`BridgeProtoDiserializedBuf<T>::IsTheProto`函数无法判断该帧属于哪个protobuf数据，因此需要在`BridgeProtoDiserializedBuf<T>::Initialize`当中对其进行初始化，这样就可以接收多帧的数据并将其发送至相关话题。

[bridge]解决了接收多个帧时无法将数据发布给相应的话题

---

modules/planning/planning_component.cc

planning start timestamp is supposed to be caught before  `common::util::FillHeader`

correct start timestamp of planning component (elegant version)

---

cyber/component/timer_component.cc

The old message callback handler for TimerComponent didn't take the termination condition into account. It is fixed now.

Cyber: fixed a bug for TimerComponent.

---

modules/tools/perception/replay_perception.py

When using the _garage_perception.bash_ script to register the obstacles, the green arrow of obstacle velocity direction doesn't change in the Dreamview because the `perception.velocity` is not updated in the `linear_project_perception` function. Here we add a line of code to update the `perception.velocity`.

Fix perception.velocity direction bug and perception frequency bug

---

modules/planning/planning_component/README_cn.md

The “planning” in the document was misspelled as “lanning”.

fix : fix README_cn.md ;The “planning” in the document was misspelled as “lanning”.

---

docs/01_Installation Instructions/how_to_launch_and_run_apollo.md

Follow up on #15312 
The path for the subsequent command in the documentation did not get updated.

docs: Update path to demo record for cyber_recorder
