ApolloAuto/apollo

apollo.sh

Fix build when ESD CAN lib exists.

---

scripts/env.sh

To better help developer debug environment problems

allow print env when outside docker.

---

docker/dev.dockerfile
docker/run_env.dockerfile

Workaround for chfn pam system error intermittently in docker. Fix #56

---

apollo.sh

I found a little typo in apollo.sh and the patch fix it.

fix typo in apollo.sh

---

docker/scripts/dev_start.sh
docker/scripts/release_start.sh

Fix the case that when the user is root, there is no /home/root
directory

map the mouting directory to the right $HOME directory

---

docker/scripts/dev_start.sh
docker/scripts/release_start.sh

The env parameters in scripts need to be the parameters in host machine not  container.

Fix env parameter in scripts, making it work in mac.

---

FAQ.md

Add white list ports into FAQ.

---

README.md
scripts/apollo_base.sh

'docker' is the container, not the directory. Fix #129

fix misleading document

---

modules/canbus/vehicle/lincoln/protocol/BUILD
modules/canbus/vehicle/lincoln/protocol/steering_65_test.cc
modules/canbus/vehicle/lincoln/protocol/throttle_62_test.cc

fixed data issue in steering_65_test, added throttle_62_test

---

README_cn.md
docs/howto/how_to_tune_control_parameters.md

sync with apollo Develop

---

modules/common/vehicle_state/vehicle_state.cc

make linear_v_ = sqrt(linear_velocity().x()^2 + linear_velocity().x()^2).

fix linear velocity from localization in vehicle state

---

modules/control/controller/lat_controller.h

Add reference paper to lateral controller

---

WORKSPACE.in

https://github.com/ApolloAuto/apollo/issues/166

Update boringssl to a stable version

---

modules/common/proto/geometry.proto
modules/common/proto/gnss_status.proto
modules/common/proto/header.proto
modules/control/proto/calibration_table.proto
modules/control/proto/lat_controller_conf.proto
modules/decision/proto/decision.proto
modules/dreamview/proto/simulation_world.proto
modules/drivers/gnss/proto/config.proto
modules/drivers/gnss/proto/gnss.proto
modules/drivers/gnss/proto/gnss_status.proto
modules/drivers/gnss/proto/gpgga.proto
modules/drivers/gnss/proto/imu.proto
modules/drivers/gnss/proto/ins.proto
modules/perception/proto/perception_map_roi.proto
modules/perception/proto/perception_obstacle.proto
modules/perception/proto/traffic_light_detection.proto
modules/planning/proto/planning.proto
modules/prediction/proto/prediction_obstacle.proto

Unify indents to 2 spaces.
Limit row width to 80 bytes.

Unify proto styles.

---

modules/common/proto/error_code.proto

Add error code for prediction module for the convenience of future work.

add error code for prediction module

---

modules/common/math/kalman_filter.h

Add some functions to get the matrices in the kalman filter. This will be used in the near future in prediction module (maybe and others).

add some getters to kalmanFilter.h for future use.

---

modules/control/common/pid_controller.cc

Accidentally closed the last pull request.

Fix redundant condition check.

---

apollo.sh
modules/monitor/hwmonitor/hw/esdcan/esdcan_checker.h
modules/monitor/hwmonitor/hw/esdcan/esdcan_utils.cc
third_party/can_card_library/esd_can/BUILD

fix Hardware check build err after apply ESD lib @siyangy

fix Hardware check build err after apply ESD lib

---

modules/control/conf/lincoln.pb.txt
modules/control/controller/BUILD
modules/control/controller/lat_controller.cc
modules/control/controller/lat_controller.h
modules/control/proto/lat_controller_conf.proto
modules/control/testdata/conf/lincoln.pb.txt

Adjust the proto instead of mark it deprecated since this is only for config

Replace vehicle related config in lat_controller_conf with the one in modules/common/configs

---

docs/specs/qp_spline_path_optimizer.md
docs/specs/qp_spline_st_speed_optimizer.md

qp_spline_st_speed_optimizer.md

planning: update latex equations in md for better visualization in

---

modules/common/math/math_utils.cc
modules/common/math/math_utils.h
modules/common/math/math_utils_test.cc
modules/control/common/trajectory_analyzer.cc
modules/map/hdmap/hdmap_common.cc

This function can be easily misued.

common: remove DoubleCompare function

---

modules/elo/README.md

update elo readme

---

docs/howto/how_to_run_offline_perception_visualizer.md
modules/perception/tool/gen_pose_file.py
modules/perception/tool/offline_visualizer_tool/conf/offline_lidar_perception_test.flag

(1) Add a FAQ doc "how_to_run_offline_perception_visualizer.md";
(2) Add a python script "modules/perception/tool/gen_pose_file.py" to generate Pose files;
(3) Modify the default parameters in "modules/perception/tool/offline_visualizer_tool/conf/offline_lidar_perception_test.flag".

Add the FAQ doc on How to Run Offline Perception Visualizer

---

docker/scripts/dev_start.sh

This reverts commit 382e435b3c534a4eab9a7e4045021ef381afd62f.

Revert "Add option to pull docker image from China mirror [skip ci]."

---

modules/common/util/factory.h
modules/common/util/factory_test.cc

see usage example in unit test

common: let factory support create objects with variadic arguments

---

modules/planning/reference_line/reference_line.cc
modules/planning/tasks/speed_decider/speed_decider.cc
modules/planning/tasks/speed_decider/speed_decider.h

* simplified the functions in SpeedDecider

planning: added keep clear st boundary handling in SpeedDecider

---

modules/planning/math/smoothing_spline/spline_1d_kernel_test.cc

Planning: Added reference line kernel matrix test for multiple spline

---

apollo.sh
docker/dev.x86_64.dockerfile
modules/planning/planning.cc
scripts/apollo_base.sh

* start app (e.g., planning) with profiling by `bash scripts/planning.sh start_prof`

build: added `bash apollo.sh build_prof` option to support profiling

---

modules/map/hdmap/hdmap.cc
modules/map/hdmap/hdmap.h

add clear area and speed bump interface

add hdmap interface for user

---

modules/map/pnc_map/pnc_map.cc
modules/map/pnc_map/pnc_map.h
modules/map/pnc_map/pnc_map_test.cc
modules/planning/common/frame.cc
modules/planning/reference_line/reference_line_provider.cc

which can be used to define change lane behavior

pnc_map: add position history in pnc map

---

.travis.yml
apollo.sh

This reverts commit 1b636c2b1d9ecc608c546fdc2f0bc3d4c466fdcb.

Revert "Merge ci jobs into one cicheck."

---

modules/map/pnc_map/pnc_map.cc
modules/planning/planning.cc
modules/planning/reference_line/BUILD
modules/planning/reference_line/reference_line_provider.cc
modules/planning/reference_line/reference_line_provider.h

* avoid potential data conflicts.

planning: set position of reference line provider from main thread

---

docs/quickstart/apollo_1_5_quick_start_cn.md

Add a Chinese Version of Apollo 1.5 QS guide

Docs:Add a Chinese Version of Apollo 1.5 QS guide

---

modules/map/pnc_map/pnc_map.cc
modules/map/pnc_map/pnc_map.h
modules/map/pnc_map/pnc_map_test.cc
modules/map/pnc_map/route_segments.cc
modules/map/pnc_map/route_segments.h
modules/planning/common/frame.cc
modules/planning/common/planning_gflags.cc
modules/planning/common/planning_gflags.h
modules/planning/planning.cc
modules/planning/reference_line/reference_line_provider.cc
modules/planning/reference_line/reference_line_provider.h

* prepare for stitching reference line

planning: make pnc map get reference line locate stateless.

---

modules/drivers/canbus/can_comm/message_manager.h
modules/drivers/canbus/sensor_canbus.h
modules/drivers/delphi_esr/delphi_esr_message_manager.h

* drivers: using cvar to trigger publish
* drivers: conf change
* drivers: create a new thread for radar data trigger
* lint fix
* drivers: add lock when clearing sensordata
* drivers: make data_trigger_running flag volatile and fix a typo

 drivers: using cvar to trigger publishment (#931)

---

modules/map/pnc_map/pnc_map.cc
modules/planning/common/path_obstacle.cc
modules/planning/reference_line/reference_line.cc
modules/planning/reference_line/reference_line.h
modules/planning/reference_line/reference_line_provider.cc

planning: check whether static obstacle block road before assign st

---

modules/tools/replay/replay_file.py

* easier to replay different routing on road test

tool: allow replay_file to replay a message in a folder

---

modules/drivers/gnss/src/impl/parser/novatel/novatel_messages.h
modules/drivers/gnss/src/impl/parser/novatel/novatel_parser.cpp
modules/drivers/gnss/src/parser/data_parser.cpp

drivers:gnss add imu parse.

---

modules/drivers/usb_cam/README_cn.md
modules/drivers/usb_cam/launch/start_leopard.launch
modules/drivers/usb_cam/launch/start_one_leopard.launch

add README file of camera; modify topic name.

add README file for usb camera

---

modules/dreamview/frontend/src/components/PlaybackControls/TimeControls.js
modules/dreamview/frontend/src/components/PlaybackControls/index.js
modules/dreamview/frontend/src/store/playback.js
modules/dreamview/frontend/src/store/websocket/websocket_offline.js
modules/dreamview/frontend/src/styles/playback-controls.scss

1. to allow frame seeking 
2. to display retrieved frames on time bar correctly
3. to cache frames

Dreamview: updated playback controls

---

modules/perception/obstacle/onboard/fusion_subnode.cc
modules/perception/obstacle/onboard/radar_process_subnode.cc
modules/perception/obstacle/onboard/radar_process_subnode.h
modules/perception/onboard/transform_input.cc
modules/perception/tool/export_sensor_data/BUILD
modules/perception/tool/export_sensor_data/conf/export_sensor_data.flag
modules/perception/tool/export_sensor_data/export_sensor_data.cc
modules/perception/tool/export_sensor_data/export_sensor_data.h
modules/perception/tool/export_sensor_data/export_sensor_data_main.cc

perception: add export sensor data tool

 perception: add export sensor data tool 

---

modules/perception/obstacle/radar/modest/object_builder.cc

perception: use absolute velocity

perception: use absolute velocity

---

modules/map/pnc_map/pnc_map.cc
modules/map/pnc_map/pnc_map.h
modules/map/pnc_map/pnc_map_test.cc
modules/map/pnc_map/route_segments.cc
modules/map/pnc_map/route_segments.h
modules/planning/integration_tests/sunnyvale_loop_test.cc
modules/planning/planning.cc
modules/planning/reference_line/reference_line_provider.cc

* to track driving progress
* to prepare solving routing loop problem

added state information in pnc map

---

modules/map/hdmap/adapter/xml_parser/util_xml_parser.cc

add z for outline to fix traffic light bug

add z for outline to fix traffic light bug 

---

modules/localization/common/localization_gflags.cc
modules/localization/common/localization_gflags.h
modules/localization/conf/localization.conf
modules/localization/msf/common/io/velodyne_utility.cc
modules/localization/msf/common/util/compression.cc
modules/localization/msf/local_map/base_map/base_map.cc
modules/localization/msf/local_map/base_map/base_map.h
modules/localization/msf/local_map/lossless_map/lossless_map_matrix.cc
modules/localization/msf/local_map/lossless_map/lossless_map_matrix.h
modules/localization/msf/local_map/lossless_map/lossless_map_node.h
modules/localization/msf/local_map/lossy_map/lossy_map_matrix_2d.cc
modules/localization/msf/local_tool/data_extraction/pcd_exporter.cc
modules/localization/msf/local_tool/local_visualization/engine/visualization_engine.cc
modules/localization/msf/local_tool/local_visualization/online_visual/online_local_visualizer.cc
modules/localization/msf/local_tool/map_creation/lossless_map_creator.cc
modules/localization/msf/msf_localization.cc
modules/localization/msf/msf_localization.h

Localization: Add antimu leverarm, velodyne 64 default height, and fix code style.

Localization: Add antimu leverarm, velodyne 64 default height, and fix code style.

---

modules/map/proto/map_stop_sign.proto

add type for stop sign proto

---

modules/perception/model/modest_radar_detector.config
modules/perception/obstacle/base/object.cc

perception: add confidence

---

modules/perception/common/perception_gflags.cc
modules/perception/common/perception_gflags.h
modules/perception/conf/perception.conf
modules/perception/onboard/transform_input.cc

perception: add gflag to change localization

perception: add gflag to change localization

---

modules/calibration/data/mkz8/gnss_params/ant_imu_leverarm.yaml
modules/calibration/data/mkz8/velodyne_params/velodyne64_height.yaml
modules/localization/common/localization_gflags.cc
modules/localization/msf/local_tool/local_visualization/online_visual/online_local_visualizer.cc
modules/localization/msf/msf_localization.cc
modules/localization/msf/params/gnss_params/ant_imu_leverarm.yaml
modules/localization/msf/params/velodyne_params/velodyne64_height.yaml
modules/localization/msf/params/velodyne_params/velodyne64_novatel_extrinsics_example.yaml

Localization: Add velodyne64, gnss lever arm default parameters.

 Localization: Add velodyne64, gnss lever arm default parameters.

---

modules/perception/common/perception_gflags.cc
modules/perception/common/perception_gflags.h
modules/perception/conf/adapter.conf
modules/perception/conf/perception.conf
modules/perception/obstacle/fusion/probabilistic_fusion/pbf_hm_track_object_matcher.cc
modules/perception/obstacle/onboard/radar_process_subnode.cc
modules/perception/obstacle/onboard/radar_process_subnode.h
modules/perception/tool/export_sensor_data/export_sensor_data.cc
modules/perception/tool/export_sensor_data/export_sensor_data.h

perception: change to use velocity of localization pose

perception: change to use velocity of localization pose

---

modules/map/tools/proto_map_generator.cc

fix proto map generator bug

---

modules/localization/msf/local_tool/local_visualization/engine/visualization_manager.cc
modules/localization/msf/local_tool/local_visualization/engine/visualization_manager.h

Localization: fix visual tool bug.

Localization: fix visual tool bug.

---

modules/planning/lattice/behavior_decider/adc_master_scenario.cc
modules/planning/lattice/behavior_decider/adc_master_scenario.h
modules/planning/lattice/behavior_decider/behavior_decider.cc
modules/planning/lattice/behavior_decider/scenario.h
modules/planning/lattice/behavior_decider/scenario_manager.cc
modules/planning/lattice/behavior_decider/scenario_manager.h
modules/planning/lattice/behavior_decider/signal_light_scenario.cc
modules/planning/lattice/behavior_decider/signal_light_scenario.h
modules/planning/lattice/trajectory1d_generator/trajectory1d_generator.cc
modules/planning/lattice/trajectory1d_generator/trajectory_evaluator.cc
modules/planning/proto/lattice_structure.proto

Warning: Might Break Scenarios

Refactor by dissolving decision type in PlanningTarget.

---

modules/tools/diagnostics/diagnostics.py

Since I'm not familiar with Python language, I strongly recommend Python Master here to review this, thanks.

tools: fix diagnostics error when default terminal width <= 80

---

modules/localization/conf/localization.conf
modules/localization/msf/local_tool/local_visualization/engine/visualization_engine.cc
modules/localization/msf/local_tool/local_visualization/engine/visualization_engine.h
modules/localization/msf/local_tool/local_visualization/engine/visualization_manager.cc
scripts/record_bag.sh

Localization: Set utm zone id to 10, and add gnss topics in record sh file.

 Localization: Set utm zone id to 10, and add gnss topics in record sh file.

---

modules/tools/rosbag/drive_event.py

* apollo directory is readonly in release docker

set drive event default directory to apollo/data

---

modules/perception/obstacle/base/object.cc
modules/perception/obstacle/base/object.h
modules/perception/obstacle/base/types.h
modules/perception/obstacle/lidar/segmentation/cnnseg/cluster2d.h
modules/perception/obstacle/lidar/tracker/hm_tracker/hm_tracker.cc
modules/perception/obstacle/radar/modest/object_builder.cc
modules/perception/proto/perception_obstacle.proto

Perception: add confidence type, lidar and radar confidence

Perception: add confidence type, lidar and radar confidence

---

scripts/localization_online_visualizer.sh

Localization: Add a localization visualizer tool.

Localization: Add a localization visualizer tool.

---

modules/perception/obstacle/fusion/interface/base_fusion.h
modules/perception/obstacle/fusion/probabilistic_fusion/probabilistic_fusion.h
modules/perception/obstacle/radar/interface/base_radar_detector.h
modules/perception/obstacle/radar/modest/modest_radar_detector.h
modules/perception/obstacle/radar/modest/object_builder.h
modules/perception/obstacle/radar/modest/radar_track_manager.cc
modules/perception/obstacle/radar/modest/radar_track_manager.h

Perception: add comments

---

modules/localization/msf/local_tool/local_visualization/engine/visualization_engine.cc
modules/localization/msf/local_tool/local_visualization/engine/visualization_engine.h
modules/localization/msf/local_tool/local_visualization/engine/visualization_manager.cc
modules/localization/msf/local_tool/local_visualization/engine/visualization_manager.h
modules/localization/msf/local_tool/local_visualization/online_visual/online_local_visualizer.cc

Localization: Upgrade online visualization tool for localization.

Localization: Upgrade online visualization tool for localization.

---

scripts/record_bag.sh

Localization: Add /apollo/localization/msf_gnss and msf_lidar topics in scripts/record_bag.sh.

Localization: Add /apollo/localization/msf_gnss and msf_lidar topics in scripts/record_bag.sh.

---

modules/tools/rosbag/drive_event.py

* use the earliest time when user presses 'd'
* timestamp returned by rospy.Time.now() seems incorrect.

tools: fix drive event utility timestamp problem

---

modules/planning/planning.cc

* but print an error message for every 10 seconds, incase the user
really forget to provide prediction message

planning: when perception message is not provided, keep planning

---

modules/map/pnc_map/pnc_map.cc
modules/map/pnc_map/pnc_map.h
modules/map/pnc_map/pnc_map_test.cc
modules/planning/reference_line/reference_line_provider.cc

* change to use synchronize update vehicle state in pnc_map

planning: fix waypoint tracking bug in pnc_map

---

tools/supervisord.conf

status
FYI http://supervisord.org/index.html

all: added a sample supervisord config file to help manage process

---

modules/control/controller/mpc_controller.cc

Control : Fix MPC scheduler bug

---

modules/planning/common/frame.cc
modules/planning/common/frame.h
modules/planning/common/reference_line_info.cc
modules/planning/common/reference_line_info.h
modules/planning/planner/em/em_planner.cc

* to avoid init unused reference line

planning: delay reference line info init step to planner

---

docs/FAQs/Calibration_FAQs.md
docs/FAQs/Calibration_FAQs_cn.md
docs/quickstart/apollo_2_0_sensor_calibration_guide.md
docs/quickstart/apollo_2_0_sensor_calibration_guide_cn.md

Calibration: fix some document errors

Calibration: fix some document errors

---

modules/planning/lattice/behavior_decider/condition_filter.cc
modules/planning/lattice/trajectory1d_generator/end_condition_sampler.cc
modules/planning/planner/lattice/lattice_planner.cc
modules/planning/proto/lattice_structure.proto

1. Add more info for time consuming
2. Use reference v to disable v dimension sampling

1. Add more info for time consuming 2. Use reference v to disable v dimension sampling

---

docs/howto/how_to_run_perception_module_on_your_local_computer.md
docs/specs/3d_obstacle_perception.md
modules/perception/README.md

Perception: modify documents

---

modules/perception/conf/perception.conf

fix word spelling chaning to changing

Update perception.conf fix word spelling chaning to changing

---

modules/planning/common/lag_prediction.cc
modules/planning/common/lag_prediction.h
modules/planning/common/planning_gflags.cc
modules/planning/common/planning_gflags.h

This reverts commit 01b905fd197337bc6d4b10687f28189780f8912f.

Revert "planning: added protected obstacles in lagged prediction"

---

modules/dreamview/conf/hmi.conf
modules/tools/supervisord/dev.conf
modules/tools/supervisord/release.conf
scripts/usb_camera.sh

* due to supervisor does not have customized stop command

tools: start/stop camera and velodyne with scripts

---

docs/quickstart/apollo_2_0_quick_start.md
docs/specs/3d_obstacle_perception.md
modules/perception/README.md

Updated English Version Perception README

Update Perception README.md

---

docs/FAQs/Calibration_FAQs.md
docs/FAQs/Calibration_FAQs_cn.md
scripts/sensor_calibration.sh

update scripts, now the calibration log includes stderr; 
update calibration FAQs;

now the calibration log includes stderr; update calibration FAQs

---

modules/planning/common/planning_gflags.cc
modules/planning/common/planning_gflags.h
modules/planning/lattice/trajectory1d_generator/trajectory_evaluator.cc
modules/planning/lattice/trajectory1d_generator/trajectory_evaluator.h
modules/planning/planner/lattice/BUILD
modules/planning/planner/lattice/lattice_planner.cc
modules/planning/planner/lattice/lattice_planner.h

2.Interface for converting future trajectory into current frame lonlat trajectory

1.Auto change lane

---

modules/control/common/pid_controller.cc
modules/control/common/pid_controller.h

-add the missing setter function.

-Issue #2437 (Missing a setter function for boolean member variable integrator_hold_ in class PIDController)

---

modules/map/hdmap/hdmap.cc
modules/map/hdmap/hdmap.h
modules/map/hdmap/hdmap_common.cc
modules/map/hdmap/hdmap_common.h
modules/map/hdmap/hdmap_common_test.cc
modules/map/hdmap/hdmap_impl.cc
modules/map/hdmap/hdmap_impl.h
modules/map/pnc_map/path.cc

add new hdmap interface to get associate lanes for stop sign

get associate lanes for stop sign

---

docker/scripts/dev_start.sh

scripts: add -l option to deal with local image

---

modules/map/hdmap/hdmap.cc
modules/map/hdmap/hdmap.h
modules/map/hdmap/hdmap_impl.cc
modules/map/hdmap/hdmap_impl.h

update hdmap interface

---

modules/map/pnc_map/pnc_map.cc
modules/map/pnc_map/pnc_map.h
modules/map/pnc_map/pnc_map_test.cc
modules/map/pnc_map/route_segments.cc
modules/map/pnc_map/route_segments.h

* reduce code complexity
* ready to solve the multi-loop problem.

pnc_map: refactor route_index

---

modules/map/hdmap/adapter/proto_organizer.cc
modules/map/hdmap/hdmap_common.cc
modules/map/hdmap/hdmap_common.h
modules/map/hdmap/hdmap_impl.cc

support stop sign association

---

.gitignore
docs/demo_guide/.gitignore

merge the separate .gitignore rule

---

docs/quickstart/apollo_2_0_sensor_calibration_guide.md

fix a document error

---

modules/planning/lattice/trajectory_generator/trajectory_evaluator.cc

Will move the constants to gflags in the next commit

Planning: [lattice] adjust cost functions to make them in the same scale

---

modules/localization/BUILD
modules/localization/localization.cc

avoid build issue on aarch64 platform

localization: added selective compile for x86_64 platform

---

modules/dreamview/frontend/src/store/meters.js

Dreamview: validate steering percentage and angle separately

---

modules/map/hdmap/adapter/xml_parser/lanes_xml_parser.cc
modules/map/hdmap/adapter/xml_parser/lanes_xml_parser.h
modules/map/hdmap/hdmap_common.cc
modules/map/hdmap/hdmap_common.h
modules/map/proto/map_lane.proto

add distance from lane center to road boundaries

add distance from lane center to road boundaries

---

docs/quickstart/apollo_software_installation_guide_cn.md
modules/tools/mock_routing/mock_routing_request.py

- tools:update routing proto in mock_routing_request.py 
- update typo

tools:update routing proto in mock_routing_request.py 

---

modules/canbus/vehicle/lincoln/protocol/steering_65.h
modules/canbus/vehicle/lincoln/protocol/wheelspeed_6a.h
modules/common/math/integral.h

canbus & common : fix missing standard headers

---

modules/map/hdmap/adapter/xml_parser/signals_xml_parser.cc

Fix to Ticket # 1194
Signed-off-by: Yu Ding <dingyu02@baidu.com>

Fix bug in xml parser

---

modules/perception/obstacle/base/object.h
modules/perception/obstacle/camera/cipv/BUILD
modules/perception/obstacle/camera/cipv/cipv.cc
modules/perception/obstacle/camera/cipv/cipv.h
modules/perception/obstacle/camera/common/lane_object.h

Added CIPV

---

modules/dreamview/backend/map/map_service.cc
modules/map/tools/sim_map_generator.cc
scripts/apollo_base.sh

Reduces lane element size to 1/10.

Dreamview: reduce map transmission size

---

scripts/dreamview.sh

Dreamview works fine w/o monitor/roscore offline.

Dreamview: remove echo

---

modules/perception/obstacle/onboard/cipv_subnode.cc

correct motion info is added to cipv

Perception: In cipv, motion information is provided

---

modules/perception/common/perception_gflags.cc
modules/perception/obstacle/fusion/async_fusion/async_fusion.cc

1. disable async fusion by default
2. create new track for camera only

fix new bugs

---

modules/planning/reference_line/reference_line.cc
modules/planning/reference_line/reference_line.h
modules/planning/reference_line/smoother_util.cc

improve stitching smoothness result

smoother_util: refactor reference line stitching method to further

---

modules/localization/msf/local_tool/map_creation/lossless_map_creator.cc
scripts/msf_simple_map_creator.sh

fixed a bug in lossless_map_creator.

 fixed a bug in lossless_map_creator

---

scripts/perception_lowcost.sh

adding perception 2.5 starting script

adding perception 2.5 starting script

---

modules/dreamview/frontend/src/store/websocket/index.js

this is needed since ws port is not fixed for offlineview

Dreamview: allow flexible ws port for offline mode

---

modules/perception/obstacle/base/object.cc
modules/perception/obstacle/base/object.h

It might be ugly but the addfourcorners function was added in object.cc

Perception: publish 4 corners of obstacle to PNC

---

docker/scripts/dev_start.sh

Update dev_start.sh to start from local image version

Update dev_start.sh to start from local image version

---

tools/bazel.rc

https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary.linkstatic

Build: Fix release error by linking binaries staticly.

---

modules/perception/cuda_util/BUILD

* to trigger cuda_util rebuild when relative files have changed.

perception: added file dependency in genrule

---

.gitignore
modules/perception/cuda_util/BUILD

cuda_util/build is conflict with cuda_util/BUILD on MacOS.

Perception: Refine cuda_util making rule.

---

modules/localization/msf/common/util/threadpool.h

Block until all of the work thread terminate.

Localization: Fix a bug in the Threadpool

---

modules/planning/common/planning_util.cc
modules/planning/constraint_checker/collision_checker.cc
modules/planning/lattice/behavior/path_time_graph.cc
modules/planning/lattice/behavior/prediction_querier.cc
modules/planning/lattice/trajectory1d/constant_deceleration_trajectory1d.cc
modules/planning/lattice/trajectory1d/piecewise_trajectory1d.cc
modules/planning/lattice/trajectory_generation/trajectory_evaluator.cc
modules/planning/tasks/qp_spline_path/qp_frenet_frame.cc

* always use fabs for float or double number

planning: fix potential abs bug.

---

docs/quickstart/README.md
docs/quickstart/apollo_2_0_hardware_system_installation_guide_v1.md
docs/quickstart/apollo_2_5_quick_start_cn.md

- correct dreamview port number
- fix MarkDown syntax
- add doc indexes for Apollo 2.5 quick start

docs: correct dreamview port number etc.

---

docs/howto/how_to_collect_map.md
docs/howto/how_to_collect_map_cn.md

update map collection document

update map collection document

---

docker/build/dev.x86_64.dockerfile
docker/build/installers/install_ceres_solver.sh
docs/quickstart/apollo_2_0_sensor_calibration_guide.md

1. add imu vehicle calibration tool and update the docs.
2. add ceres solver to dockerfile

Calibration doc

---

modules/canbus/tools/teleop.cc

Prior to this commit there was no turn signal functionality in the teleop demo. This commit adds that functionality.

Add functionality for turn signals

---

modules/perception/obstacle/fusion/probabilistic_fusion/pbf_track.cc
modules/perception/obstacle/fusion/probabilistic_fusion/pbf_track_object_distance.cc

1. modify assoc rule
2. remove bag_mode hack

modify fusion assoc rule

---

docker/scripts/README.md
docker/scripts/install_docker.sh

test the scritps that work properly.

docker:add a bash script to install and unistall docker-ce

---

docs/apollo_2.5_technical_tutorial.md

Added apollo 2.5 technical tutorial, which is a collection of apollo technical documents for fresher.

Added apollo 2.5 technical tutorial 

---

scripts/apollo_base.sh

A fix to https://github.com/ApolloAuto/apollo/commit/47cfd8e3e073f081ba39ffa82bb9141d4767cd45

Scripts: Fix error of calling git command in release container.

---

modules/common/util/ctpl_stl.h
modules/common/util/ctpl_stl_test.cc
modules/planning/common/planning_thread_pool.cc
modules/planning/common/planning_thread_pool.h

Please refer to [my blog](https://blog.csdn.net/davidhopper/article/details/80353501)  to see the reason for  changes.

Common: changed thread pool code to be more efficient and standardized.

---

modules/perception/conf/dag_camera_obstacle_offline_all.config
modules/perception/conf/perception_lowcost_vis.conf
modules/perception/obstacle/camera/cipv/cipv.cc
modules/perception/obstacle/camera/cipv/cipv.h
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc
modules/perception/obstacle/onboard/BUILD
modules/perception/obstacle/onboard/cipv_subnode.cc
modules/perception/obstacle/onboard/fusion_subnode.cc
modules/perception/obstacle/onboard/fusion_subnode.h

Thank you for reviewing it! 
I fixed the bug (yaw_rate->velocity). For other comments, I will PR next time.

Call cipv at fusion

---

modules/perception/lib/config_manager/calibration_config_manager.h
modules/perception/obstacle/base/object.h
modules/perception/obstacle/camera/dummy/dummy_algorithms.h
modules/perception/obstacle/camera/interface/base_camera_transformer.h
modules/perception/obstacle/camera/transformer/flat_camera_transformer.cc
modules/perception/obstacle/camera/transformer/flat_camera_transformer.h
modules/perception/obstacle/camera/visualizer/frame_content.cc
modules/perception/obstacle/camera/visualizer/frame_content.h
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.h
modules/perception/obstacle/onboard/camera_process_subnode.cc
modules/perception/obstacle/onboard/camera_process_subnode.h
modules/perception/obstacle/onboard/visualization_subnode.cc

Per-frame Pitch angle real-time calibration based on the assumption that objects should be on the ground

Perception: Real-time ego pose adjustment for the change of pitch angle between camera and ground plane

---

modules/map/relative_map/common/relative_map_gflags.cc
modules/map/relative_map/navigation_lane.cc
modules/map/relative_map/navigation_lane.h

The implementation of MergeNavigationLineAndLaneMarker()  is incorrect, temporarily disabled.

Map: fixed several bugs for multi-lane relatvie map.

---

modules/map/relative_map/navigation_lane.cc

Map: added the path priority parameter for a navigation path and fixed a bug in NavigationLane::MergeNavigationLineAndLaneMarker().

---

modules/planning/BUILD
modules/planning/conf/planning_config_navi.pb.txt
modules/planning/navi/common/local_path.h
modules/planning/navi/decider/BUILD
modules/planning/navi/decider/navi_path_decider.cc
modules/planning/navi/decider/navi_path_decider.h
modules/planning/navi/decider/navi_path_decider_test.cc
modules/planning/planning.cc
modules/planning/proto/BUILD
modules/planning/proto/navi_path_decider_config.proto
modules/planning/proto/planning_config.proto

Generate the most basic path data based on the reference line shifting

NaviPathDecider : Generate basic path data

---

modules/planning/navi/decider/navi_speed_decider.cc
modules/planning/navi/decider/navi_speed_decider.h
modules/planning/navi/decider/navi_speed_decider_test.cc

Make speed decision base on obstacles.

NaviSpeedDecider : Generate speed data

---

modules/drivers/pandora/pandora_driver/CMakeLists.txt
modules/drivers/pandora/pandora_driver/src/Pandar40P/CMakeLists.txt

`-std=c++11` instead of `--std=c++11`

Fix an error.

---

modules/planning/navi/decider/navi_speed_decider.cc
modules/planning/navi/decider/navi_speed_decider_test.cc

Update navi_speed_decider.cc and navi_speed_decider_test.cc.

NaviSpeedDecider: update some code

---

modules/planning/conf/planning_config_navi.pb.txt
modules/planning/navi/decider/navi_speed_decider.cc
modules/planning/navi/decider/navi_speed_decider.h
modules/planning/navi/decider/navi_speed_decider_test.cc
modules/planning/proto/BUILD
modules/planning/proto/navi_speed_decider_config.proto
modules/planning/proto/planning_config.proto

NaviSpeedDecider: add acceleration control.

---

modules/planning/navi/decider/BUILD
modules/planning/navi/decider/navi_obstacle_decider.cc
modules/planning/navi/decider/navi_obstacle_decider.h
modules/planning/navi/decider/navi_obstacle_decider_test.cc

According to the requirements of "navi_path_decider" , modify the program interface and adjust the internal calling relation of the program.

navi_obstacle_decider:modify program interface

---

modules/canbus/vehicle/gem/protocol/BUILD
modules/canbus/vehicle/gem/protocol/wiper_rpt_91_test.cc

 Canbus: Add test for gem wiper_rpt_91

---

modules/canbus/vehicle/gem/protocol/BUILD
modules/canbus/vehicle/gem/protocol/brake_motor_rpt_2_71_test.cc
modules/canbus/vehicle/gem/protocol/brake_motor_rpt_3_72_test.cc
modules/canbus/vehicle/gem/protocol/date_time_rpt_83_test.cc

Canbus: add test for brake_motor_rpt_2_71

---

modules/canbus/vehicle/gem/protocol/BUILD
modules/canbus/vehicle/gem/protocol/global_rpt_6a_test.cc

Canbus: add test to global_rpt_6a

---

docs/specs/dreamview_usage_table.md

Updated definitions for individual sections and formatting changes

DreamView Usage Table 

---

modules/canbus/vehicle/gem/protocol/BUILD
modules/canbus/vehicle/gem/protocol/lat_lon_heading_rpt_82_test.cc
modules/canbus/vehicle/gem/protocol/steering_motor_rpt_1_73_test.cc
modules/canbus/vehicle/gem/protocol/steering_motor_rpt_2_74_test.cc
modules/canbus/vehicle/gem/protocol/steering_motor_rpt_3_75_test.cc
modules/canbus/vehicle/gem/protocol/steering_rpt_1_6e_test.cc

Canbus: add test for lat_lon_heading_rpt_82

---

modules/localization/msf/common/util/BUILD
modules/localization/msf/common/util/threadpool.h
modules/localization/msf/local_map/base_map/BUILD
modules/localization/msf/local_map/base_map/base_map.cc
modules/localization/msf/local_map/base_map/base_map.h
modules/localization/msf/local_map/base_map/base_map_pool.cc
modules/localization/msf/local_map/base_map/base_map_pool.h

This reverts commit 83fdfced13f5ebc8ad018e426d1ec3b1af57991b.

fixed localization test:  Revert "change to use threadpool in common"

---

docs/quickstart/apollo_3_0_quick_start_cn.md

A guide for Chinese developers, this documentation serves as an user manual that includes many other information about how to install and use Apollo

documentation of Apollo3.0 quick start in Chinese

---

docs/quickstart/apollo_3_0_hardware_system_installation_guide_cn.md

Chinese version of Apollo 3.0 Hardware and System Installation Guide

hardware and installation document chinese version

---

modules/planning/navi/decider/navi_obstacle_decider.cc
modules/planning/navi/decider/navi_obstacle_decider.h
modules/planning/navi/decider/navi_obstacle_decider_test.cc

@yifeijiang 
Increase the obstacle judgement interface for obtaining information of unsafe obstacles between trajectory and reference line.

planning:add a obstacle judgment interface for navi_speed_decider

---

modules/planning/conf/planning_config_navi.pb.txt
modules/planning/navi/decider/BUILD
modules/planning/navi/decider/navi_speed_decider.cc
modules/planning/navi/decider/navi_speed_decider.h
modules/planning/navi/decider/navi_speed_decider_test.cc
modules/planning/navi/decider/navi_speed_ts_graph.cc
modules/planning/navi/decider/navi_speed_ts_graph.h
modules/planning/navi/decider/navi_speed_ts_graph_test.cc
modules/planning/proto/navi_speed_decider_config.proto

Planning: update speed decider for NaviPlanner.

---

docs/specs/Navigation/Navtech_NV-GI120_Installation_Guide.md
docs/specs/Navigation/Navtech_NV-GI120_Installation_Guide_cn.md

Fixing wrong information in the documentation

Yang han101 patch 1

---

docker/canary/setup_container.sh
docker/scripts/dev_start.sh
docker/scripts/release_start.sh
scripts/bootstrap.sh

This reverts commit 763c1621a80524f7e59aed3b1053a25eee1f3803.

Revert "docker: start supervisor when starting dev docker"

---

docs/specs/dreamview_usage_table_cn.md

hard to translate, needs lots of efforts ^_^

commit dreamview_usage_table chinese version

---

modules/perception/obstacle/camera/common/camera.h

Perception:Fix a code error of camera

perception:Fix a code error of camera

---

docs/howto/how_to_do_performance_profiling.md

[Document] typo

---

modules/common/util/BUILD
modules/common/util/testdata/simple.proto
modules/common/util/util.h
modules/common/util/util_test.cc

* the updated method is about 5 times faster than the original method.

util: improve protobuf message comparison code efficiency

---

modules/planning/tasks/traffic_decider/crosswalk.cc

planning: fix incorrect stop fence for pedestrian behind ADC upon a u-turn (#2428)

---

modules/planning/conf/planning_config_navi.pb.txt
modules/planning/navi/decider/navi_speed_decider.cc
modules/planning/navi/decider/navi_speed_decider.h
modules/planning/navi/decider/navi_speed_decider_test.cc
modules/planning/navi/decider/navi_speed_ts_graph.cc
modules/planning/navi/decider/navi_speed_ts_graph.h
modules/planning/navi/decider/navi_speed_ts_graph_test.cc
modules/planning/proto/navi_speed_decider_config.proto

NaviSpeedDecider: update and bugfix

---

modules/perception/obstacle/camera/filter/object_camera_filter.cc

fix issue #5246

---

RELEASE.md

@natashadsouza @lianglia-apollo

Fix typo error

---

modules/drivers/gnss/third_party/novatel.c
modules/drivers/gnss/third_party/rcvraw.c
modules/drivers/gnss/third_party/rtcm.c
modules/drivers/gnss/third_party/rtcm3.c
modules/drivers/gnss/third_party/rtkcmn.c
modules/drivers/gnss/third_party/rtklib.h

Make RTKLIB more readable

---

docs/specs/perception_apollo_3.0.md

tiny clerical error in  perception_apollo_3.0.md

---

modules/common/time/time.h
modules/common/time/time_test.cc
modules/planning/integration_tests/planning_test_base.cc

common: added SetNowInSeconds(double) function to make mocking time

---

modules/common/apollo_app.h
modules/localization/README.md
modules/localization/msf/README.md
modules/localization/msf/local_map/lossless_map/lossless_map_matrix.h
modules/localization/msf/local_map/lossless_map/lossless_map_node.h

- Fixed typos in code summary comments and mark up documents in the Localization module.
- Includes one file from outside localization module --modules/common/apollo_app.h

Localization:Fixed minor typos 

---

scripts/docker_adduser.sh

Work with
https://github.com/ApolloAuto/apollo/pull/5307

Scripts: Add ~/.lcovrc to enable branch coverage.

---

modules/dreamview/conf/hmi.conf
modules/monitor/conf/monitor_conf.pb.txt
scripts/record_bag.py

1. Unify to navigation mode.
2. front_6mm is only for navi mode, and we want to ignore them in standard mode.

Navi: Remove LowCost mode and move the front_6mm topic as CMD option.

---

modules/localization/common/localization_gflags.cc
modules/localization/common/localization_gflags.h
modules/localization/conf/localization.conf
modules/localization/msf/local_integ/localization_integ_impl.cc
modules/localization/msf/local_integ/localization_integ_impl.h
modules/localization/msf/local_integ/localization_integ_process.cc
modules/localization/msf/local_integ/localization_integ_process.h
modules/localization/msf/local_integ/localization_lidar_process.cc
modules/localization/msf/local_integ/localization_lidar_process.h
modules/localization/msf/local_integ/localization_params.h
modules/localization/msf/local_integ/measure_republish_process.cc
modules/localization/msf/local_integ/measure_republish_process.h
modules/localization/msf/msf_localization.cc
modules/tools/prediction/mlp_train/generate_h5.py

flag + AINFO is basically reinventing ADEBUG

localization: remove flag + AINFO coding pattern with ADEBUG

---

modules/planning/navi/decider/navi_speed_decider.cc

Fix an uninitialized variable.

NaviPlanner: fix an uninitialized variable

---

modules/control/controller/lon_controller.cc

@Capri2014 @lianglia-apollo @ycool

Control: Add TrajectoryType for lon_controller.cc

---

modules/prediction/container/adc_trajectory/adc_trajectory_container_test.cc
modules/prediction/container/container_manager.h
modules/prediction/scenario/BUILD
modules/prediction/scenario/feature_extractor/feature_extractor.cc
modules/prediction/scenario/scenario_manager.h
modules/prediction/scenario/scenario_manager_test.cc

Prediction: add more unit tests for scenario_manger and adc_trajectory_container

---

modules/tools/calibration/data_collector.py

fix two parameters in DataCollector 
referenced in issue #5451

[tools]* fix control calibration tools init parameters

---

modules/tools/calibration/result2pb.py

Lacking indentations after with statements.

Tools/calibration: Fix 2 syntax errors

---

docs/howto/how_to_update_vehicle_calibration.md
docs/howto/how_to_update_vehicle_calibration_cn.md

- update control calibration tool and docs

[docs] Control calibration docs

---

modules/data/tools/recorder/data_recorder_manager.py

It's better to catch the dedicated sub-exception rather than Exception. Also, reduce VM footprint is a minor benefit in this way.

Tools/recorder: Catch the OSError exception rather than Exception.

---

modules/drivers/velodyne/velodyne_driver/src/driver/driver.cpp

driver.cpp: replace while() with do...while() to reduce once 

---

modules/tools/map_gen/add_signal.py

Verify the passed in parameters number before using them.
Raise exception when any exception occur during open file and read.
Fix the var name map to _map, to avoid any confusion because map is
a keyword in python.

Tools/map_gen: Rewrite this program via a few bug fixes.

---

modules/localization/BUILD
modules/localization/common/localization_gflags.cc
modules/localization/common/localization_gflags.h
modules/localization/conf/lmd_adapter.conf
modules/localization/lmd/BUILD
modules/localization/lmd/lmd_localization.cc
modules/localization/lmd/lmd_localization.h
modules/localization/lmd/lmd_localization_test.cc
modules/localization/localization.cc
modules/localization/proto/BUILD
modules/localization/proto/localization_config.proto
modules/localization/proto/odometry_lane_marker.proto

Add framework for a new method named LMD.

Localization: add framework for a new method named LMD

---

modules/prediction/network/net_layer.cc

Fixed typo

---

docker/scripts/README.md

I fixed typo

---

cyber/README.md

More to come with our official release

framework: brief intro about Apollo Cyber RT

---

modules/planning/common/BUILD
modules/planning/common/obstacle_blocking_analyzer.cc
modules/planning/common/obstacle_blocking_analyzer.h
modules/planning/conf/scenario_side_pass_config.pb.txt
modules/planning/scenarios/side_pass/BUILD
modules/planning/scenarios/side_pass/side_pass_scenario.cc
modules/planning/scenarios/side_pass/stage_approach_obstacle.cc
modules/planning/toolkits/deciders/side_pass_path_decider.cc

- Uniformed the obstacle blocking analysis. (function written but not yet used in side_pass_scenario for stability consideration)
- Improved the path trimming logic of the side-pass.
- Fixed a bug in deciding whether one obstacle is blocked by others.

Planning: A few refactors

---

cyber/tools/cyber_monitor/general_message.cc
cyber/tools/cyber_monitor/general_message.h
cyber/tools/cyber_monitor/general_message_base.cc
cyber/tools/cyber_monitor/general_message_base.h
cyber/tools/cyber_monitor/screen.cc

Framework: add new function for cyber monitor

Framework: add new function for cyber monitor

---

modules/perception/production/data/perception/camera/models/traffic_light_detection/detection.pt

UNKNOWN traffic light at intersection was still an issue. We found a root cause and this PR will fix it.

Perception:Fix detection of very close traffic lights

---

modules/dreamview/backend/sim_control/sim_control.cc
modules/dreamview/backend/sim_control/sim_control.h

Just revert a commit made on sim control before on reverse gear. @unacao

Dreamview: Simcontrol: revert the change related to reverse gear

---

modules/localization/lmd/lmd_localization.cc

Bugfix Moved AdapterInit function before MsgCallBack.

Localization: Bugfix Moved AdapterInit function before MsgCallBack

---

modules/localization/lmd/lmd_localization.cc
modules/localization/lmd/predictor/output/predictor_output.cc
modules/localization/lmd/predictor/perception/lm_sampler.cc
modules/tools/localization/lane_markers_displayer.py

Using filteredimu message instead of raw imu

LMDLocalization: Used FilteredIMU message in predictor_output

---

modules/tools/navi_generator/backend/util/file_operator.cc

Fixed a bug that the file operator imported a 0xFF from file.

NaviGenerator:Fixed a bug that the file operator imported a 0xFF from file.

---

modules/common/time/timer_test.cc

It is hard to guarantee a fixed sleep time.

Common: Relaxed check range in timer_test.cc.

---

modules/tools/navi_generator/backend/util/BUILD
modules/tools/navi_generator/backend/util/trajectory_processor.cc
modules/tools/navi_generator/backend/util/trajectory_processor.h

…nResponse to response to frontend.

NaviGenerator: Used the message NaviResponse instead of struct NaviGenResponse to response to frontend.

---

modules/tools/record_analyzer/tools/perception_obstacle_sender.py

Tools:update perception_obstacle_sender.py

---

modules/tools/record_analyzer/tools/dump_message.py

support cyber for tool message_dump

Tools:support cyber for tool dump channel to file

---

modules/data/tools/rosbag_to_record/BUILD
modules/data/tools/rosbag_to_record/channel_info.cc
modules/data/tools/rosbag_to_record/channel_info.h
modules/data/tools/rosbag_to_record/rosbag_to_record.cc

This reverts commit 5b5b67ecddbd25e39679e8dcfbc2e2c58b9c067c.

Revert "Data: Retire rosbag_to_record tool. (#6158)"

---

modules/tools/mapshow/libs/plot_planning.py
modules/tools/mapshow/libs/plot_smoothness.py
modules/tools/mapshow/libs/plot_st.py
modules/tools/plot_control/plot_control.py
modules/tools/plot_control/realtime_test.py
modules/tools/realtime_plot/realtime_plot.py
modules/tools/rosbag/sample_pnc_topics.py
modules/tools/rosbag/stat_static_info.py

Tools:Update_7_tools_to_cybertron

Tools:Update_7_tools_to_cybertron_2

---

docs/cyber/CyberRT_Quick_Start_cn.md

translate  CyberRT_Quick_Start.md to cn , add doc file CyberRT_Quick_Start_cn.md

Docs: translation, add CyberRT_Quick_Start_cn.md

---

docs/quickstart/README.md

update 3.5 hardware installation link

Docs:Update README.md

---

docs/quickstart/apollo_2_0_hardware_system_installation_guide_v1.md

update Novatel PP6 configuration filed `EVENTOUTCONTROL`

Docs:Update apollo_2_0_hardware_system_installation_guide_v1.md

---

modules/map/hdmap/adapter/xml_parser/common_define.h
modules/map/hdmap/adapter/xml_parser/roads_xml_parser.cc
modules/map/hdmap/adapter/xml_parser/roads_xml_parser.h
modules/map/hdmap/hdmap_common.h
modules/map/proto/map_road.proto

add road type for hdmap to support routing in internal road

add road type for hdmap

---

docs/specs/Navigation/Npos320_guide.md
docs/specs/Navigation/images/Npos320_main.png
docs/specs/Navigation/images/Npos320_panel.png
modules/drivers/gnss/parser/novatel_messages.h
modules/drivers/gnss/proto/config.proto

Support new navigation BDStar Navigation NPOS 320.

Drivers:support new navigation

---

modules/map/hdmap/adapter/xml_parser/header_xml_parser.cc

support specified zone id in base_map.xml

support specified zone id in base_map.xml

---

modules/perception/camera/app/debug_info.cc
modules/perception/camera/app/obstacle_camera_perception.cc
modules/planning/common/indexed_list.h

This reverts commit 60dd9ffa920e1cf64c80e5f2d9c92ec60722c275.

Revert "perception: refactor WriteCalibrationOutput method (#6654)"

---

docs/cyber/CyberRT_Terms.md

framework: add Cyber_Terms.md

---

modules/perception/camera/app/lane_camera_perception.cc
modules/perception/camera/app/lane_camera_perception.h
modules/perception/camera/app/obstacle_camera_perception.cc
modules/perception/camera/app/obstacle_camera_perception.h
modules/perception/production/conf/perception/camera/obstacle.pt

Create output folder automatically based on config file

perception: address an issue with camera detection module

---

modules/planning/tasks/deciders/BUILD
modules/planning/tasks/deciders/path_bounds_decider.cc
modules/planning/tasks/deciders/path_bounds_decider.h

Planning: rename reference_line_decider to lateral_bounds_decider to make for sense

---

modules/common/configs/config_gflags.cc
modules/common/configs/config_gflags.h
modules/common/vehicle_model/BUILD
modules/common/vehicle_model/conf/vehicle_model_config.pb.txt
modules/common/vehicle_model/proto/BUILD
modules/common/vehicle_model/proto/vehicle_model.proto
modules/common/vehicle_model/vehicle_model.cc
modules/common/vehicle_model/vehicle_model.h
modules/planning/common/BUILD
modules/planning/common/trajectory_stitcher.cc
modules/planning/common/trajectory_stitcher.h

Test would fail now as many init point has a nonzero speed.
Plz have a review before I make any change to testdata.

Common: add vehicle model for trajectory stitcher

---

modules/dreamview/conf/hmi_modes/map_collection.pb.txt
modules/drivers/velodyne/conf/velodyne16_front_up_center_compensator.pb.txt
modules/drivers/velodyne/conf/velodyne16_front_up_compensator.pb.txt
modules/drivers/velodyne/conf/velodyne16_front_up_conf.pb.txt
modules/transform/conf/static_transform_conf.pb.txt
scripts/record_map_data.py

Change topics name for traffic light lidar.

Dreamview & Driver : set front up lidar for traffic lights

---

modules/tools/prediction/data_pipelines/data_preprocessing/features_labels_utils.py

Prediction: not check junction feature dim in merging labels, do it in model training, instead

---

modules/planning/common/ego_info.cc
modules/planning/common/ego_info.h
modules/planning/common/ego_info_test.cc
modules/planning/common/planning_gflags.cc
modules/planning/common/reference_line_info.h
modules/planning/common/speed_profile_generator.cc
modules/planning/common/speed_profile_generator.h
modules/planning/common/speed_profile_generator_test.cc
modules/planning/on_lane_planning.cc
modules/planning/scenarios/lane_follow/lane_follow_stage.cc
modules/planning/scenarios/side_pass/stage_stop_on_wait_point.cc
modules/planning/scenarios/stage.cc
modules/planning/tasks/deciders/path_bounds_decider.cc

This reverts commit 0c2d13d750e21809fdecad7804fea457bda6de64.

Revert "Planning: remove code related to front obs distance"

---

WORKSPACE.in
apollo.sh
docs/specs/[Jetson_TX2_Platform]build_apollo_from_source_cn.md
modules/localization/conf/localization_tx2.conf
modules/map/relative_map/conf/relative_map_tx2.conf
modules/map/relative_map/tools/navigator.cc
modules/perception/common/perception_gflags.cc
modules/perception/common/perception_gflags.h
modules/perception/obstacle/camera/detector/yolo_camera_detector/yolo_camera_detector.cc
modules/perception/obstacle/onboard/camera_process_subnode.cc
modules/perception/perception.cc
modules/planning/conf/planning_navi.conf
modules/planning/reference_line/reference_line_provider.cc
third_party/yaml_cpp.BUILD

optimization for tx2

---

docs/demo_guide/README.md
docs/demo_guide/README_cn.md

fix the wrong guide on branch r3.5.0

Demo: update demo docs and record.

---

modules/planning/common/open_space_info.h
modules/planning/proto/open_space_fallback_decider_config.proto
modules/planning/tasks/deciders/open_space_fallback_decider.cc
modules/planning/tasks/deciders/open_space_fallback_decider.h
modules/planning/tasks/deciders/open_space_roi_decider.h

The testing cases have been generated before.

planning: implement open space fall back decider

---

docs/cyber/CyberRT_Migration_Guide.md

Docs:update markdown title format CyberRT_Migration_Guide.md

---

modules/planning/open_space/trajectory_smoother/planning_block.cu

fix a bug when initialize cuda

fix a bug when initialize cuda

---

docker/build/installers/py27_requirements.txt

pyproj have update to 2.0 version ,If no specific version would cause a build problem

Docker:fix pyproj install problem

---

modules/perception/common/i_lib/pc/i_struct_s.h

Perception: Fix voxel issue #6945

---

modules/tools/perception/empty_prediction.py
modules/tools/perception/extend_prediction.py
modules/tools/perception/print_perception.py
modules/tools/perception/replay_perception.py

remove unused import and Unnecessary else after return (no-else-return)

tools:fix python codes by lint report

---

modules/planning/on_lane_planning.cc
modules/planning/proto/decision.proto

To fix the "NotReady" fence in parking scenarios.

Planning: add engage advice and main decision in parking stage 

---

modules/planning/common/open_space_info.h
modules/planning/conf/planning.conf
modules/planning/on_lane_planning.cc

remove redundant debug flag in open space

planning: openspace, disable export chart flag for conflict issue

---

modules/map/hdmap/adapter/xml_parser/common_define.h
modules/map/hdmap/adapter/xml_parser/lanes_xml_parser.cc
modules/map/hdmap/adapter/xml_parser/lanes_xml_parser.h
modules/map/hdmap/adapter/xml_parser/signals_xml_parser.cc
modules/map/hdmap/adapter/xml_parser/signals_xml_parser.h
modules/map/proto/map_signal.proto

add no right turn on red for traffic light & support different sample points size between left and right boundary

add no right turn on red for traffic light

---

docs/cyber/CyberRT_Developer_Tools.md

Based on the pull request https://github.com/ApolloAuto/apollo/pull/7243

framework: add new option for cyber_recorder play

---

modules/planning/common/planning_context.cc
modules/planning/common/planning_context.h
modules/planning/scenarios/scenario_manager.cc
modules/planning/scenarios/side_pass/side_pass_scenario.cc
modules/planning/tasks/deciders/path_assessment_decider.cc
modules/planning/tasks/deciders/path_assessment_decider.h
modules/planning/tasks/deciders/speed_bounds_decider/speed_bounds_decider.cc

@jmtao The change in scenario_manager is a little hacky for now and I will update it later to conform to the general requirements you told me.

Planning: refactored side-pass transitioning logics.

---

modules/planning/on_lane_planning.cc
modules/planning/on_lane_planning.h

Will optimize and re-org of the charts later.

Planning: Finish porting and enable all debug chart for open space planner

---

modules/common/util/BUILD
modules/common/util/file.h
modules/perception/camera/lib/lane/detector/darkSCNN/BUILD
modules/perception/camera/lib/lane/detector/darkSCNN/darkSCNN_lane_detector.cc
modules/perception/camera/lib/lane/postprocessor/darkSCNN/BUILD
modules/perception/camera/lib/lane/postprocessor/darkSCNN/darkSCNN_lane_postprocessor.cc
modules/prediction/pipeline/BUILD
modules/prediction/util/BUILD

Reverts ApolloAuto/apollo#7527: Will put this back after more test

Revert "Common: remove common/file.h"

---

modules/tools/vehicle_calibration/sensor_calibration/extract_data.py

* Add new argument to extract a given channel that is more flexible
* Add new argument to define data extraction ratio (%10 by default)
* Add record validation method
* Add directory operation method
* Add data compression method (GZIP)
* Add fake code for extracting JPG file (WIP)
* Add fake code for extracting PCD file (WIP)
* Refactor record extraction method

Tools: update extract_data

---

modules/canbus/vehicle/lincoln/protocol/brake_60.cc
modules/canbus/vehicle/lincoln/protocol/brake_60_test.cc
modules/canbus/vehicle/lincoln/protocol/gear_66.cc
modules/canbus/vehicle/lincoln/protocol/gear_66_test.cc
modules/canbus/vehicle/lincoln/protocol/steering_64.cc
modules/canbus/vehicle/lincoln/protocol/steering_64_test.cc
modules/canbus/vehicle/lincoln/protocol/throttle_62.cc
modules/canbus/vehicle/lincoln/protocol/throttle_62_test.cc

Canbus : update lincoln rate as well

---

modules/planning/tasks/deciders/open_space_fallback_decider.cc

TODO(Runxin): find a better fallback trajectory.

planning: open space fixed wrong fallback trajectory

---

modules/perception/conf/dag_streaming_camera_lidar_tx2.config
modules/perception/conf/perception_camera_lidar_tx2.conf
modules/perception/obstacle/base/types.cc
modules/perception/obstacle/fusion/probabilistic_fusion/probabilistic_fusion.cc

These modifications have been verified on MKZ.

config files and code modifications for lida16&camera on TX2

---

modules/tools/vehicle_calibration/sensor_calibration/extract_data.py

(1)Redefine logistics about channel message extraction.
(2)Enable multi-channel extraction.
(3)Fix bugs about storage criterion.
(4)Switch from opencv1 to opencv2 in Mat handling.:w

Tools: Update cyber data extraction tools. major update on data_extract.py

---

modules/control/controller/lat_controller.cc
modules/control/controller/lat_controller.h
modules/control/controller/lat_controller_test.cc
modules/control/controller/lon_controller.cc
modules/control/controller/lon_controller.h
modules/control/controller/lon_controller_test.cc
modules/control/proto/control_cmd.proto

Verified by the bag files generated from dreamland simulation

Control: compute the acceleration, jerk variables for Lon/Lat Controller

---

docker/build/installers/py27_requirements.txt
modules/tools/vehicle_calibration/sensor_calibration/extract_data.py

(1) Enable PointCloud extraction. support multi-channel extractions for camera, lidar channels.
(2) Update data_extract.py
(3) Add python dependency.

Tools: add PointCloud extraction. support multi-channel extractions for camera, lidar channels.

---

modules/planning/conf/planning_config.pb.txt
modules/planning/proto/open_space_fallback_decider_config.proto
modules/planning/tasks/deciders/open_space_fallback_decider.cc
modules/planning/tasks/deciders/open_space_fallback_decider.h

open space fallback: modify fallback velocity, acceleration and stopping position.

planning: modify openspace fallback trajectory 

---

WORKSPACE.in
modules/planning/tasks/rss/BUILD
modules/planning/tasks/rss/decider_rss.cc
modules/planning/tasks/rss/decider_rss.h
modules/planning/tasks/rss/decider_rss_test.cc
third_party/rss_lib.BUILD

RSS open source library is hosted in https://github.com/intel/ad-rss-lib
Here is the patch to intercept it with Apollo.  
With help of this patch, Apollo will fetch the RSS open source library from remote repository and build it automatically. 
The patch has been pass unit test and integrated test.

rss open source library x apollo 

---

modules/tools/vehicle_calibration/sensor_calibration/data_file_object.py
modules/tools/vehicle_calibration/sensor_calibration/extract_data.py

(1)Enable small channel storage procedure, as in bin file; 
(2) Enable different extraction rates for different channels; 
(3) Enable Gps Extraction;
(4) Add more saint checks;

Tools: update data extraction. 

---

modules/canbus/vehicle/lincoln/protocol/brake_60.cc
modules/canbus/vehicle/lincoln/protocol/brake_60_test.cc
modules/canbus/vehicle/lincoln/protocol/gear_66.cc
modules/canbus/vehicle/lincoln/protocol/gear_66_test.cc
modules/canbus/vehicle/lincoln/protocol/steering_64.cc
modules/canbus/vehicle/lincoln/protocol/steering_64_test.cc
modules/canbus/vehicle/lincoln/protocol/throttle_62.cc
modules/canbus/vehicle/lincoln/protocol/throttle_62_test.cc

This reverts commit 65476509f2e2e3c79bbb363f8217a5baecea6977.

Revert "Canbus : update lincoln rate as well"

---

modules/tools/vehicle_calibration/sensor_calibration/data_file_object.py

* FileObject class should inherit from object for compatibility
* s/type()/isinstance()/ for testing list type

Tools: update data_file_object

---

modules/tools/vehicle_calibration/sensor_calibration/extract_data.py

1) enable multiple record files or folder of files as input
2) addmore cyber record saint checks

Tools: update data extract. 

---

modules/common/time/time_util.h
modules/drivers/gnss/conf/gnss_conf_newton.pb.txt
modules/drivers/gnss/parser/BUILD
modules/drivers/gnss/parser/data_parser.cc
modules/drivers/gnss/parser/newtonm2_parser.cc
modules/drivers/gnss/parser/newtonm2_parser.h
modules/drivers/gnss/parser/parser.h
modules/drivers/gnss/proto/config.proto
modules/drivers/gnss/util/time_conversion.h
modules/localization/common/localization_gflags.cc
modules/localization/common/localization_gflags.h
modules/localization/conf/msf_adapter.conf
modules/localization/msf/common/util/BUILD
modules/localization/msf/common/util/math_util.h
modules/localization/msf/local_integ/BUILD
modules/localization/msf/local_integ/localization_integ.cc
modules/localization/msf/local_integ/localization_integ.h
modules/localization/msf/local_integ/localization_integ_impl.cc
modules/localization/msf/local_integ/localization_integ_impl.h
modules/localization/msf/local_integ/localization_params.h
modules/localization/msf/local_integ/measure_republish_process.cc
modules/localization/msf/local_integ/measure_republish_process.h
modules/localization/msf/msf_localization.cc
modules/localization/msf/msf_localization.h
scripts/docker_adduser.sh

Add Newton-M2 GPS which is cherry-picked from branch v3.1_dev.

Add Newton-M2 GPS which is cherry-picked from branch v3.1_dev

---

modules/tools/calibration/data_collector.py
modules/tools/calibration/process.py
modules/tools/calibration/process_data.sh

modified the calibration scripts

modified the calibration scripts

---

modules/planning/tasks/deciders/open_space_fallback_decider.cc
modules/planning/tasks/deciders/open_space_fallback_decider.h

fallback trajectory's start point issue fixed

planning: open space fallback, bug fix

---

modules/calibration/data/ch/calibration_table.pb.txt
modules/calibration/data/ch/calibration_table.txt
modules/calibration/data/ch/gnss_params/ant_imu_leverarm.yaml
modules/calibration/data/ch/gnss_params/gnss_conf.pb.txt
modules/calibration/data/ch/navigation_ch.pb.txt
modules/calibration/data/ch/vehicle_info.pb.txt
modules/calibration/data/ch/vehicle_param.pb.txt
modules/calibration/data/ch/vehicle_params/vehicle_imu_extrinsics.yaml

Add the coolhigh config files which are cherry-picked from branch v3.1_dev.

Add the coolhigh config files which are cherry-picked from branch v3.1_dev

---

modules/planning/common/planning_gflags.cc
modules/planning/common/planning_gflags.h
modules/planning/proto/decision.proto
modules/planning/proto/speed_bounds_decider_config.proto
modules/planning/tasks/deciders/speed_bounds_decider/speed_bounds_decider.cc
modules/planning/tasks/deciders/speed_bounds_decider/speed_bounds_decider.h

Current logic is simply stopping and waiting. Future implementation will be based on this.

Planning: initial implementation for lane-change urgency checking

---

modules/tools/sensor_calibration/data_file_object.py
modules/tools/sensor_calibration/extract_data.py
modules/tools/sensor_calibration/sensor_msg_extractor.py

Tool: update data extract:
(1) encapsulate sensor message parser as scalable classes.
(2) generate timestamps file for each sensor message
(3) re-factor the whole tool
(4) fix bug of *.pcd generation
(5) fix a typo bug from previous commit

Tools: data extraction tool. major revision

---

modules/planning/tasks/deciders/open_space_fallback_decider.cc

reopen this pull request, fix fallback trajectory shaking in scenario 562.

planning: fix open space fallback shaking issue

---

modules/tools/sensor_calibration/config/camera_to_lidar_calibration.config
modules/tools/sensor_calibration/config/lidar_to_GNSS_calibration.config
modules/tools/sensor_calibration/extract_data.py
modules/tools/sensor_calibration/proto/extractor_config.proto
modules/tools/sensor_calibration/sensor_msg_extractor.py

(1) switch to protobuf text_format as configuration handler 
(2) add configuration example for sensor data extraction   
(3) enable simple one-line command
(4) save point timestamp in second in pcd

Tools: update data extractor. 

---

modules/tools/calibration/data_collector.py
modules/tools/calibration/process.py
modules/tools/calibration/process_data.sh
scripts/docker_adduser.sh

Modified the calibration scripts which are cherry-picked from branch v3.1_dev and the environment variable

Modified the calibration scripts which are cherry-picked from branch v3.1_dev and the environment variable

---

modules/planning/tasks/deciders/speed_bounds_decider/speed_bounds_decider.cc
modules/planning/tasks/deciders/speed_bounds_decider/speed_bounds_decider.h

Cherry-pick from planning_path_debug

Planning: skip side pass stop with self path

---

modules/prediction/common/road_graph.cc

https://github.com/ApolloAuto/apollo/blob/master/docs/technical_tutorial/best_coding_practice.md

Prediction: Refactor per C++ best practice.

---

modules/planning/open_space/coarse_trajectory_generator/grid_search.cc
modules/planning/open_space/coarse_trajectory_generator/grid_search.h
modules/planning/open_space/coarse_trajectory_generator/reeds_shepp_path.cc
modules/planning/open_space/coarse_trajectory_generator/reeds_shepp_path.h
modules/planning/open_space/open_space_trajectory_generator.cc
modules/planning/open_space/open_space_trajectory_generator.h
modules/planning/open_space/trajectory_partition/trajectory_partitioner.cc
modules/planning/open_space/trajectory_partition/trajectory_partitioner.h
modules/planning/open_space/trajectory_smoother/distance_approach_problem.cc
modules/planning/open_space/trajectory_smoother/distance_approach_problem.h
modules/planning/open_space/trajectory_smoother/dual_variable_warm_start_problem.cc
modules/planning/open_space/trajectory_smoother/dual_variable_warm_start_problem.h
modules/planning/planner/open_space/open_space_planner.cc
modules/planning/planner/open_space/open_space_planner.h
modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_optimizer.cc
modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_optimizer.h
modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_provider.cc
modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_provider.h

https://github.com/xiaoxq/apollo/blob/master/docs/technical_tutorial/best_coding_practice.md
Point 5

Planning: Pass scala types by value per best practice.

---

modules/perception/camera/lib/lane/postprocessor/denseline/denseline_lane_postprocessor.cc
modules/perception/onboard/component/fusion_camera_detection_component.cc
modules/perception/onboard/component/fusion_camera_detection_component.h

The fitting parameters c0, c1, c2, c3 lies in car coordinates: x forward, y left, z up

Perception: fill lane detection results into output channel: /perception/obstacles

---

modules/tools/calibration/data_collector.py
modules/tools/calibration/process_data.sh

modified the process_data.sh and  data_collector.py, to align with apollo 3.5

modified the process_data.sh and  data_collector.py

---

modules/tools/calibration/data_collector.py
modules/tools/calibration/process_data.sh

Modified the process_data.sh and data_collector.py which are cherry-picked from branch v3.1_dev

Modified the process_data.sh and data_collector.py which are cherry-picked from branch v3.1_dev

---

modules/calibration/modes/mkz_standard/calibration.launch

Calibration: Switch to video raw image during calibration

no compression during calibration

---

modules/planning/conf/planning_config.pb.txt
modules/planning/tasks/optimizers/piecewise_jerk_path/piecewise_jerk_path_optimizer.cc

This reverts commit 1a4dfe61357eb133970a4abb19b6f10b7e7438df.

Revert "Planning: consider lon_speed for piecewise_path"

---

modules/drivers/gnss/conf/gnss_conf_newton.pb.txt
modules/drivers/gnss/parser/BUILD
modules/drivers/gnss/parser/data_parser.cc
modules/drivers/gnss/parser/newtonm2_parser.cc
modules/drivers/gnss/parser/newtonm2_parser.h
modules/drivers/gnss/parser/parser.h
modules/drivers/gnss/proto/config.proto
scripts/docker_adduser.sh

Add Newton-M2 GPS to branch master which is cherry-picked from branch v3.1_dev.

Add Newton-M2 GPS to branch master

---

modules/tools/visualizer/main.cc
modules/tools/visualizer/main_window.cc
modules/tools/visualizer/main_window.h
modules/tools/visualizer/shaders/video_image_plane.frag
modules/tools/visualizer/texture.cc

support bgr8
support specific topic names

fix issue 8002

---

modules/planning/conf/cosTheta_smoother_config.pb.txt
modules/planning/conf/planning.conf
modules/planning/proto/reference_line_smoother_config.proto
modules/planning/reference_line/BUILD
modules/planning/reference_line/cos_theta_problem_interface.cc
modules/planning/reference_line/cos_theta_problem_interface.h
modules/planning/reference_line/cos_theta_reference_line_smoother.cc
modules/planning/reference_line/cos_theta_reference_line_smoother.h

 Planning: Costheta reference line smoother improvements

---

modules/planning/conf/planning.conf

Set failsafe to be false in default.

Planning: openspace: disable smoother failsafe

---

modules/prediction/proto/feature.proto

Prediction: add adc trajectory into feature proto for better feature extraction

---

modules/planning/tasks/optimizers/road_graph/comparable_cost.h
modules/planning/tasks/optimizers/road_graph/comparable_cost_test.cc
modules/planning/tasks/optimizers/road_graph/dp_road_graph.cc
modules/planning/tasks/optimizers/road_graph/dp_road_graph.h
modules/planning/tasks/optimizers/road_graph/trajectory_cost.cc
modules/planning/tasks/optimizers/road_graph/trajectory_cost.h
modules/planning/tasks/optimizers/road_graph/trajectory_cost_test.cc
modules/planning/tasks/optimizers/road_graph/waypoint_sampler.cc
modules/planning/tasks/optimizers/road_graph/waypoint_sampler.h

This reverts commit f1d0cbf1b6bd3238ee05df751dd18a553b83e2bb.
Per request, the deprecated code might be used for further research. Revert the deletion.

planning: Revert "planning: deprecate road_graph"

---

modules/planning/open_space/trajectory_smoother/distance_approach_ipopt_interface.cc
modules/planning/open_space/trajectory_smoother/distance_approach_ipopt_interface.h

Planning: openspace: model simplification

---

modules/planning/common/planning_gflags.cc
modules/planning/tasks/deciders/path_assessment_decider.cc
modules/planning/tasks/deciders/path_lane_borrow_decider/path_lane_borrow_decider.cc
modules/planning/tasks/optimizers/piecewise_jerk_path/piecewise_jerk_path_optimizer.cc
modules/prediction/evaluator/evaluator_manager.cc
modules/prediction/evaluator/evaluator_manager.h
modules/prediction/evaluator/pedestrian/pedestrian_interaction_evaluator.cc
modules/prediction/proto/prediction_conf.proto

Please see each commit's name for details.

Planning & Prediction: several changes

---

modules/planning/on_lane_planning.cc
modules/planning/proto/planning_internal.proto

@yifeijiang I made a few changes in reference line evaluation, could you update it to dreamland quantitative analysis? Thanks!

Planning: add more detail reference line evaluation

---

.travis.yml

Try fixing according to https://github.com/travis-ci/travis-ci/issues/8787

Travis: Cache LFS data.

---

docker/scripts/dev_start.sh

This should work
```
docker/scripts/dev_start.sh
/apollo/docker/scripts/dev_start.sh
```

run_docker_start_from_symlink

---

apollo.sh
docker/scripts/cyber_into.sh
docker/scripts/cyber_start.sh
scripts/docker_adduser.sh

* adding build_cyber option in apollo.sh
* add docker start and into scripts for Cyber RT only docker containers

cyber: add build and docker support for Cyber RT development

---

modules/perception/camera/app/cipv_camera.cc
modules/perception/camera/app/cipv_camera.h

Select two laterally longest points for lane overlap and select one closest point for distance of object

Perception: Changed CIPV selection mechanism

---

modules/planning/navi/decider/navi_path_decider.cc

s = v0 * t + 1 / 2.0 * a * t^2

fix path length calculation

---

modules/planning/reference_line/reference_line_provider.cc

fix the missing update of lane_change_type

fix the missing update of lane_change_type

---

modules/dreamview/frontend/src/renderer/tileground.js

Only fetching available images.

Dreamview: update offlineview fetching image map

---

modules/planning/open_space/coarse_trajectory_generator/hybrid_a_star.cc
modules/planning/tasks/deciders/path_assessment_decider/path_assessment_decider.cc
modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc

Please refer to my blog: https://blog.csdn.net/davidhopper/article/details/90674399 for details.

Planning:  used C++11 move semantics to improve efficiency.

---

modules/planning/proto/planning_status.proto
modules/planning/scenarios/scenario_manager.cc
modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc
modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.h

- generate pull-over boundary separately.
- use road boundary as pull-over boundary.
- once found a boundary, keep checking validity rather than look for new one again.

Planning: several changes

---

modules/perception/camera/lib/traffic_light/tracker/semantic_decision.cc

The bracket positions were totally incorrect.

Perception: Fix traffic light tracking issue

---

cyber/tools/cyber_launch/cyber_launch
modules/prediction/launch/prediction.launch

cyber: Add user-defined environment variable into cyber_launch && Fix

---

modules/localization/msf/local_integ/localization_integ_impl.cc

1. Remove the effect of gravity in acceleration_vrf.
2. Use standard gravity to correct acceleration.

Localization: Fix acceleration_vrf.

---

modules/bridge/common/bridge_header.cc

This reverts commit 4be98f1e7d69615b83f3051b83eceef4f2b67a48.

Revert "Bridge: code logic refinement"

---

modules/perception/camera/common/camera_frame.h
modules/perception/camera/lib/lane/common/darkSCNN.proto
modules/perception/camera/lib/lane/detector/darkSCNN/darkSCNN_lane_detector.cc
modules/perception/camera/lib/lane/detector/darkSCNN/darkSCNN_lane_detector.h
modules/perception/camera/tools/offline/visualizer.cc
modules/perception/production/data/perception/camera/models/lane_detector/config_darkSCNN.pt
modules/perception/production/data/perception/camera/models/lane_detector/darkSCNN/dark_SCNN_vpt_8x_trainable_xavier_lighter_ud_deploy.pt
modules/perception/production/data/perception/camera/models/lane_detector/darkSCNN/deploy.prototxt
modules/perception/proto/perception_camera.proto
modules/perception/testdata/camera/lib/lane/detector/darkSCNN/data/config.pt
modules/perception/testdata/camera/lib/lane/detector/darkSCNN/data/config_for_test.pt
modules/perception/testdata/camera/lib/lane/detector/darkSCNN/data/darkSCNN/deploy.prototxt
modules/perception/testdata/camera/lib/lane/postprocessor/darkSCNN/data/config.pt
modules/perception/testdata/camera/lib/lane/postprocessor/darkSCNN/data/darkSCNN/deploy.prototxt

Modify lane detection code to support running lane detection without output vanishing point.
Update unit test for model updates

Perception: Update laneline detection model and add network output for vanishing point detection

---

third_party/tf2/src/buffer_core.cpp

between signed and unsigned interger expressions on ARM platform.

Third_Party:fixed build comparison error

---

modules/planning/common/planning_gflags.cc
modules/planning/common/planning_gflags.h
modules/planning/common/reference_line_info.cc
modules/planning/common/speed_limit.cc
modules/planning/common/speed_limit.h
modules/planning/common/speed_profile_generator.cc
modules/planning/common/speed_profile_generator.h
modules/planning/scenarios/lane_follow/lane_follow_stage.cc
modules/planning/tasks/deciders/speed_bounds_decider/speed_limit_decider.cc
modules/planning/tasks/optimizers/path_time_heuristic/dp_st_cost.cc
modules/planning/tasks/optimizers/path_time_heuristic/gridded_path_time_graph.cc
modules/planning/tasks/optimizers/path_time_heuristic/gridded_path_time_graph_test.cc
modules/planning/tuning/autotuning_raw_feature_generator.cc

Code related to soft speed limit is removed. The similar logic will be added in decider level in future.

planning: code clean-up and refactor

---

docs/specs/apollo_3.0_development_kits_user_manual_cn.md

Modified the md file

---

docs/specs/apollo_3.0_development_kits_user_manual_cn.md

Update the markdown file of coohigh's user manual which is cherry-picked from branch v3.1_dev to branch r3.0.0 thirdly

Update the markdown file of coohigh's user manual which is cherry-picked from branch v3.1_dev to branch r3.0.0 thirdly

---

modules/tools/calibration/data_collector.py

Modified the data_collector.py

Modified the data_collector.py

---

modules/perception/common/i_lib/pc/i_ground.cc
modules/perception/lidar/common/pcl_util.h
modules/perception/lidar/lib/ground_detector/spatio_temporal_ground_detector/spatio_temporal_ground_detector.cc
modules/perception/lidar/lib/segmentation/ncut/BUILD
modules/perception/lidar/lib/segmentation/ncut/ncut.cc
modules/perception/lidar/lib/segmentation/ncut/ncut.h
modules/perception/lidar/lib/segmentation/ncut/ncut_segmentation.cc
modules/perception/lidar/lib/segmentation/ncut/ncut_segmentation.h
modules/perception/lidar/lib/segmentation/ncut/proto/BUILD
modules/perception/lidar/lib/segmentation/ncut/proto/ncut_config.proto
modules/perception/lidar/lib/segmentation/ncut/proto/ncut_param.proto
modules/perception/onboard/component/BUILD
modules/perception/production/conf/perception/lidar/config_manager.config
modules/perception/production/conf/perception/lidar/modules/ncut.config
modules/perception/production/data/perception/lidar/models/ncut/ncut.conf
modules/perception/production/data/perception/lidar/models/ncut/ncut_param.conf

1. add pcl vis
2. fix bug in ground removal

ncut config and fixes

---

docs/specs/apollo_3.0_development_kits_user_manual_cn.md

Docs: Update 创建引导盘

---

modules/map/tools/map_datachecker/server/static_align.cc
modules/map/tools/map_datachecker/server/static_align.h
modules/map/tools/map_datachecker/server/worker.cc
modules/map/tools/map_datachecker/server/worker.h
modules/map/tools/map_datachecker/server/worker_agent.cc
modules/map/tools/map_datachecker/server/worker_agent.h
modules/map/tools/map_datachecker/server/worker_cyber_node.cc
modules/map/tools/map_datachecker/server/worker_cyber_node.h
modules/map/tools/map_datachecker/server/worker_gflags.cc
modules/map/tools/map_datachecker/server/worker_gflags.h

map tools: data verification tool, third ten files

map tools: data verification tool, third ten files

---

modules/map/tools/map_datachecker/server/common.h
modules/map/tools/map_datachecker/server/loops_verify_agent.cc
modules/map/tools/map_datachecker/server/loops_verify_agent.h
modules/map/tools/map_datachecker/server/main.cc
modules/map/tools/map_datachecker/server/pj_transformer.cc
modules/map/tools/map_datachecker/server/pj_transformer.h
modules/map/tools/map_datachecker/server/pose_collection.cc
modules/map/tools/map_datachecker/server/pose_collection.h
modules/map/tools/map_datachecker/server/pose_collection_agent.cc
modules/map/tools/map_datachecker/server/pose_collection_agent.h

map tools: data verification tool, second ten files

map tools: data verification tool, second ten files

---

modules/map/tools/map_datachecker/client/client.cc
modules/map/tools/map_datachecker/client/client.h
modules/map/tools/map_datachecker/client/client_alignment.h
modules/map/tools/map_datachecker/client/client_channel_checker.cc
modules/map/tools/map_datachecker/client/client_channel_checker.h
modules/map/tools/map_datachecker/client/client_common.cc
modules/map/tools/map_datachecker/client/client_common.h
modules/map/tools/map_datachecker/client/client_gflags.cc
modules/map/tools/map_datachecker/client/client_gflags.h
modules/map/tools/map_datachecker/client/client_loops_check.cc
modules/map/tools/map_datachecker/client/client_loops_check.h
modules/map/tools/map_datachecker/client/exception_handler.cc
modules/map/tools/map_datachecker/client/exception_handler.h
modules/map/tools/map_datachecker/client/main.cc

map tools: data verification tool, fourth ten files

map tools: data verification tool, fourth ten files

---

modules/perception/camera/tools/offline/visualizer.cc

Exception handling motion_buffer in case that it is nullptr

Perception: Handle nullptr of motion_buffer

---

modules/localization/msf/local_integ/localization_integ_impl.cc
modules/localization/msf/local_integ/localization_integ_process.cc
modules/localization/msf/local_integ/localization_integ_process.h

Corresponding issue: 
http://newicafe.baidu.com/issue/IDG-Apollo-3670/show?from=page
注意: 需要等定位的docker volume更新之后才能通过CI .

Localization: Use corrected imu from SINS

---

docs/specs/apollo_3.0_development_kits_user_manual_cn.md

Update the md file fourth time

Update the md file fourth time

---

modules/localization/msf/common/io/velodyne_utility.cc
modules/localization/msf/common/util/extract_ground_plane.h
modules/localization/msf/local_tool/map_creation/lossless_map_creator.cc
modules/localization/msf/local_tool/map_creation/lossless_map_to_lossy_map.cc
modules/localization/msf/local_tool/map_creation/poses_interpolation/poses_interpolation.cc
modules/localization/msf/local_tool/map_creation/poses_interpolator.cc

Corresponding issue:
http://newicafe.baidu.com/issue/IDG-Apollo-3657/show?from=page

Localization: Update logs level in map creation.

---

modules/tools/calibration/result2pb.py

Fixed some identation problems in /apollo/modules/tools/calibration/result2pb.py

fix python identation problem

---

docs/specs/apollo_3.0_development_kits_user_manual_cn.md

Update the md file the fifth time

Update the md file the fifth time

---

modules/perception/camera/app/cipv_camera.cc
modules/perception/camera/app/cipv_camera.h

considering different curvature of left and right lane lines

Perception: Better virtual lane line for CIPV selection

---

modules/map/hdmap/adapter/xml_parser/common_define.h
modules/map/hdmap/adapter/xml_parser/objects_xml_parser.cc
modules/map/hdmap/adapter/xml_parser/objects_xml_parser.h
modules/map/proto/map_pnc_junction.proto

add passage and associate signals for pnc junction

add passage and associate signals for pnc junction

---

modules/perception/proto/motion_service.proto
modules/perception/proto/perception_camera.proto
modules/perception/proto/perception_lane.proto
modules/perception/proto/perception_obstacle.proto
modules/perception/proto/perception_ultrasonic.proto
modules/planning/proto/planning_status.proto
modules/prediction/proto/feature.proto

find . -name *.proto | xargs sed -i -E 's/(optional|repeated|required) (cyber|routing|monitor|canbus|control|hdmap|relative_map|drivers|image_decompress|dreamview|prediction|third_party_perception|guardian|transform|static_transform|perception|v2x|localization|dbmap|tools|data|bridge|planning_internal|common|planning)/\1 apollo.\2/'

Add full namespace to proto files

---

cyber/component/timer_component.cc
cyber/component/timer_component.h

It is convenient to get the interval directly from TimerComponent.

cyber TimerComponent GetInterval

---

README.md

I have fixed some grammar mistakes which were detected by Grammarly.

Grammar fixes in the README file.

---

docs/specs/apollo_3.0_development_kits_user_manual_cn.md

Update the md file the sixth time

Update the md file the sixth time

---

docs/specs/apollo_3.0_development_kits_user_manual_cn.md

Update the markdown file of coohigh's user manual which is cherry-picked from branch v3.1_dev to branch r3.0.0 the sixth time

Update the markdown file of coohigh's user manual which is cherry-picked from branch v3.1_dev to branch r3.0.0 the sixth time

---

modules/common/configs/config_gflags.cc
modules/common/configs/config_gflags.h
modules/map/hdmap/hdmap_common.cc
modules/perception/obstacle/lidar/roi_filter/hdmap_roi_filter/polygon_scan_converter.cc

set a gflag to replace the parameter half vehicle width and fix a bug for ROI filter

fix bug for ch2.0

---

modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc

modified the data length check of can frame

modified the socketcan, data length of can frame can be 0 - 8 bytes

---

modules/planning/lattice/trajectory_generation/lateral_osqp_optimizer.cc
modules/planning/lattice/trajectory_generation/lateral_osqp_optimizer.h

May cause problem as described https://github.com/ApolloAuto/apollo/issues/9330#issue-477800595

Planning: remove duplicate definition of delta_s_

---

cyber/message/message_traits.h
cyber/message/message_traits_test.cc
cyber/message/raw_message.h
cyber/record/BUILD
cyber/record/record_writer.h
cyber/transport/BUILD
cyber/transport/dispatcher/intra_dispatcher.cc
cyber/transport/dispatcher/intra_dispatcher.h
cyber/transport/dispatcher/intra_dispatcher_test.cc
cyber/transport/message/listener_handler.h

support different message type in intra-dispatcher, and update record-writer to use message-traits

cyber: support different message type in intra-dispatcher

---

modules/data/proto/static_info.proto

This proto needs to be retired soon.

Data: added lexus support for vehicle static proto

---

modules/planning/lattice/trajectory_generation/trajectory1d_generator.h

`ptr_trajectory_bundle` could have its original size

Planning: Adjust reserve size

---

modules/planning/tasks/deciders/path_assessment_decider/path_assessment_decider.cc

1. retire and adjust remove empty path_data as @panjiacheng required.
2. some other refine

Planning: retire and adjust remove empty path_data, as well as some other refines

---

modules/canbus/proto/ch.proto
modules/canbus/vehicle/ch/protocol/brake_status__511.cc
modules/canbus/vehicle/ch/protocol/brake_status__511.h
modules/canbus/vehicle/ch/protocol/ecu_status_1_515.cc
modules/canbus/vehicle/ch/protocol/ecu_status_1_515_test.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.h
modules/canbus/vehicle/ch/protocol/gear_command_114.cc
modules/canbus/vehicle/ch/protocol/gear_command_114.h
modules/canbus/vehicle/ch/protocol/gear_status_514.cc
modules/canbus/vehicle/ch/protocol/gear_status_514.h
modules/canbus/vehicle/ch/protocol/steer_status__512.cc
modules/canbus/vehicle/ch/protocol/steer_status__512.h
modules/canbus/vehicle/ch/protocol/throttle_status__510.cc
modules/canbus/vehicle/ch/protocol/throttle_status__510.h

Canbus: Update the coolhigh canbus protocols which is cherry-picked from branch master to branch r5.0.0

Canbus: Update the coolhigh canbus protocols which is cherry-picked from branch master to branch r5.0.0

---

modules/canbus/proto/ch.proto
modules/canbus/vehicle/ch/ch_controller.cc
modules/canbus/vehicle/ch/protocol/brake_status__511.cc
modules/canbus/vehicle/ch/protocol/brake_status__511.h
modules/canbus/vehicle/ch/protocol/brake_status__511_test.cc
modules/canbus/vehicle/ch/protocol/steer_status__512.cc
modules/canbus/vehicle/ch/protocol/steer_status__512.h
modules/canbus/vehicle/ch/protocol/steer_status__512_test.cc
modules/canbus/vehicle/ch/protocol/throttle_status__510.cc
modules/canbus/vehicle/ch/protocol/throttle_status__510.h
modules/canbus/vehicle/ch/protocol/throttle_status__510_test.cc

Canbus: add the coolhigh vehicle chassis error report protocols  which is cherry-picked from branch master to branch r3.0.0. We has done job, lint, check, test.

Canbus: add the coolhigh vehicle chassis error report protocols  which is cherry-picked from branch master to branch r3.0.0

---

modules/prediction/container/obstacles/obstacle.cc

For comment: No reward for high speed

Prediction: twice damping --> once damping

---

modules/dreamview/frontend/src/store/index.js

`updatePlanning` is decorated by `@action` while `this.planning` is not decorated by `@observable`

Dreamview: remove useless and abnormal func

---

README.md

This is for fixing the clarity of README.md.

Clarity of text for HowTo

---

modules/map/tools/map_datachecker/server/conf/map-datachecker.json

Modify the configuration of map data colletion

data_verification tool: Update map-datachecker.json

---

docs/specs/D-kit/Auto_Driving--perception_adaptation.md
docs/specs/D-kit/Auto_Driving--planning_adaptation.md

Update the Auto_driving_planning_adaptation and auto_driving_perception_adaptation documents

modify ch2.0 documents

---

modules/map/hdmap/hdmap_impl.cc

fix some unnecessary security checks to be compatible with illegal map data.

fix some unnecessary security checks

---

docs/specs/D-kit/Auto_Driving--Sensor_calibration_cn.md
docs/specs/D-kit/Auto_Driving--local_map_generation_cn.md

for Auto_Driving--Sensor_calibration_cn.md
1、add “执行标定” chapter 
2、corrent a format mistake
for Auto_Driving--local_map_generation_cn.md
1、add brief introduction about the document
2、add  descriptions of "lidar_localization" setting

Docs: add some content in Auto_Driving--Sensor_calibration_cn.md Auto_Driving--local_map_generation_cn.md

---

modules/perception/camera/app/lane_camera_perception.cc
modules/perception/camera/app/obstacle_camera_perception.cc
modules/perception/camera/app/perception.proto
modules/perception/camera/test/camera_lib_lane_postprocessor_darkscnn_lane_postprocessor_test.cc
modules/perception/camera/tools/offline/visualizer.cc
modules/perception/camera/tools/offline/visualizer.h
modules/perception/onboard/component/fusion_camera_detection_component.cc
modules/perception/onboard/component/lane_detection_component.cc
modules/perception/production/conf/perception/camera/obstacle.pt

* Run lane line detector for other cameras also (perception.proto, obstacle.pt)
* Allow visualizer to visualize two cameras (later multiple cameras)

Perception: Support multiple cameras in visualizer

---

modules/tools/fuel_proxy/proto/job_config.proto

simplehdmap: add simplehdmap fuel job_type

---

apollo.sh
cyber/record/BUILD
cyber/record/file/record_file_integration_test.cc
cyber/record/file/record_file_test.cc
cyber/record/file/record_file_writer.cc
cyber/record/file/record_file_writer.h
cyber/record/record_reader_test.cc
cyber/record/record_viewer_test.cc

Continued from https://github.com/ApolloAuto/apollo/pull/9108
@xiaoxq Thanks for the feedback. There was a bad merge and some of the modules disabled for compilation were reenabled accidentally. Still not sure about CI.

record file cleanup

---

modules/planning/common/speed/st_boundary.cc
modules/planning/common/speed/st_boundary.h
modules/planning/common/speed/st_point.h
modules/planning/tasks/deciders/st_bounds_decider/st_guide_line.cc
modules/planning/tasks/deciders/st_bounds_decider/st_guide_line.h

- code cleaning.
- added comments for better understanding.
- added new functions for accurate boundary generation.

Planning: ST-boundary updates.

---

WORKSPACE.in
docker/build/cyber.x86_64.dockerfile
modules/tools/visualizer/BUILD
modules/tools/visualizer/abstract_camera.h
modules/tools/visualizer/fixedaspectratiowidget.cc
modules/tools/visualizer/fixedaspectratiowidget.h
modules/tools/visualizer/grid.h
modules/tools/visualizer/main.cc
modules/tools/visualizer/main_window.cc
modules/tools/visualizer/main_window.h
modules/tools/visualizer/msg_dialog.h
modules/tools/visualizer/radarpoints.h
modules/tools/visualizer/renderable_object.h
modules/tools/visualizer/scene_camera_dialog.cc
modules/tools/visualizer/scene_camera_dialog.h
modules/tools/visualizer/scene_viewer.cc
modules/tools/visualizer/scene_viewer.h
modules/tools/visualizer/texture.h
modules/tools/visualizer/treewidget.cc
modules/tools/visualizer/treewidget.h
modules/tools/visualizer/video_image_viewer.h
modules/tools/visualizer/video_images_dialog.h
tools/bazel.rc
tools/qt.bzl

apollo: replace customized Qt installation with official Qt on Ubuntu …
cyber: fix building process for visualizer on ubuntu 18.04 …

cyber: upgrade Qt support in apollo

---

MANIFESTO.md

Since a personalized code of conduct is missing, I believe it is necessary to add the Manifesto to obtain consistency between the website and the repository

Apollo Manifesto

---

docs/specs/D-kit/Waypoint_following--Apollo_software_installation_cn.md

Modified the Waypoint_following--Apollo_software_installation_cn.md file

Modified the Waypoint_following--Apollo_software_installation_cn.md file

---

docs/specs/D-kit/Waypoint_following--Apollo_software_installation_cn.md

Modified the Waypoint_following--Apollo_software_installation_cn.md file which is cherry-picked from v3.1_dev

Modified the Waypoint_following--Apollo_software_installation_cn.md file which is cherry-picked from v3.1_dev

---

modules/common/adapters/adapter_gflags.cc
modules/common/adapters/adapter_gflags.h
modules/prediction/common/message_process.cc
modules/prediction/common/message_process.h
modules/prediction/submodules/BUILD
modules/prediction/submodules/container_submodule.cc
modules/prediction/submodules/container_submodule.h

Prediction: Init readers in container submodule and refactor some api in message process

---

modules/prediction/common/message_process.cc
modules/prediction/common/message_process.h
modules/prediction/submodules/container_submodule.cc

Prediction: separate container process and apply it in container submodule proc

---

modules/common/math/linear_quadratic_regulator.cc
modules/common/math/linear_quadratic_regulator.h

Implementation of issue #9894 with cross term matrix M i.e., x'Qx + u'Ru + 2x'Mu.
The necessary condition for the existence of a Riccati stabilizing solution will be added later.

Implemented LQR solver with cross term matrix as of issue #9894

---

scripts/msf_simple_map_creator.sh

In /apollo/modules/tools/fuel_proxy folder running this script cannot navigate to $APOLLO_BIN_PREFIX

localmap: fix bug for running localmap tool in fuel_proxy folder

---

modules/tools/fuel_proxy/conf/example_job.pb.txt
modules/tools/fuel_proxy/proto/job_config.proto
scripts/msf_simple_map_creator.sh

local_map generator need zoneid and lidar type

fue-proxy: update local map generator config

---

docs/specs/D-kit/Auto_Driving--Sensor_calibration_cn.md

1、fix a bug of hyperlink
2、add descriptions about how to change the frequenchy of camear topic

Docs: fix a hyperlink bug in Auto_Driving--Sensor_calibration_cn.md

---

docs/specs/D-kit/Auto_Driving--Sensor_calibration_cn.md

1、fix a bug of hyperlink
2、add descriptions about how to change the frequency of camera topic

fix a bug of hyperlink; add descriptions about how to change the frequency of camera topic

---

modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc

https://github.com/ApolloAuto/apollo/commit/9277728c64b4fcc3189fc01ff94b859f090bcd05#r35669976

Planning: Fix miss-matched brackets.

---

modules/planning/math/smoothing_spline/spline_1d_solver.h

Fix https://github.com/ApolloAuto/apollo/issues/10057

Planning: Fix potential mem leak caused by missing dtor.

---

modules/dreamview/conf/hmi_modes/car_teleop.pb.txt
modules/dreamview/conf/vehicle_data.pb.txt

Also renamed car1_encoder to teleop_video_encoder

Added conf.pb.txt files for teleop to the vehicle_data.pb.txt. 

---

modules/planning/common/frame.h
modules/planning/integration_tests/planning_test_base.h
modules/planning/math/smoothing_spline/spline_2d_solver.h
modules/planning/open_space/trajectory_smoother/distance_approach_interface.h
modules/planning/tasks/optimizers/road_graph/waypoint_sampler.h
modules/planning/tuning/autotuning_base_model.h
modules/planning/tuning/autotuning_feature_builder.h
modules/planning/tuning/speed_model/autotuning_speed_feature_builder.h
modules/storytelling/story_tellers/base_teller.h

https://www.geeksforgeeks.org/virtual-destructor/

Planning: Base classes should have virtual dtor.

---

README.md

Modified the readme.md files

---

modules/prediction/scenario/prioritization/obstacles_prioritizer.cc

Prediction: deprecate direct dependencies on pose_container in prioritization

---

modules/dreamview/backend/teleop/teleop.cc
modules/dreamview/backend/teleop/teleop.h

And checking the planning message for confirmation.

Teleop: Added pad message for Pull Over, E Stop and Resume Cruise

---

modules/prediction/evaluator/vehicle/semantic_lstm_evaluator.cc
modules/prediction/scenario/prioritization/obstacles_prioritizer.cc

Prediction: garantee positive values in ellipse coordinates and tmp disable general caution in junction due to computation limits on GPU

---

CONTRIBUTING.md

the link in the contributing pointing to the issues with tag need helps was corrected

fix-link-contributing

---

modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc

Planning: allow side-pass during lane-changing.

---

modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc

Planning: not allowing pull-over stop within junctions.

---

modules/monitor/hardware/resource_monitor.cc
modules/monitor/hardware/resource_monitor.h

Fix https://github.com/ApolloAuto/apollo/issues/10253

Monitor: Move uninitialized static member to function local.

---

modules/common/adapters/adapter_gflags.cc
modules/common/adapters/adapter_gflags.h
modules/control/conf/control.conf
modules/control/control_component.cc
modules/control/dag/lateral_longitudinal_module.dag
modules/control/dag/mpc_module.dag
modules/control/submodules/lat_lon_controller_submodule.cc
modules/control/submodules/lat_lon_controller_submodule.h
modules/control/submodules/preprocessor_submodule.cc
modules/control/submodules/preprocessor_submodule.h

More on MPC/Postprocessing submodules needed, as well as TODO cleaning in Preprocess and Lat-Lon submodules.

Control: initial cleaning for sub-modules design.  

---

docs/specs/D-kit/Auto_Driving--audo_driving_demonstration.md
docs/specs/D-kit/Auto_Driving--planning_adaptation.md

Fix the bug of the scripts for auto driving planning docs for DevelopmentKit2.0

fix a bug for DevelopmentKit2.0 Auto Driving docs

---

cyber/transport/message/message_test.cc

Handle issue https://github.com/ApolloAuto/apollo/issues/10333

Cyber: message_test uses identity correctly

---

docker/scripts/dev_start.sh

This commit redo the patch of b79975bbc29

scripts: refix the return status check of docker run

---

modules/tools/open_space_visualization/distance_approach_visualizer.py
modules/tools/plot_planning/imu_speed_acc.py
modules/tools/relative_map_viewer/relative_map_viewer.py
modules/tools/sensor_calibration/extract_static_data.py
modules/tools/vehicle_calibration/process.py

This reverts commit cd2bd711530123f552f720bea8aa3919bdb5fd2a.

Revert "Robot: Fix typos."

---

docs/specs/D-kit/Auto_Driving--audo_driving_demonstration.md
docs/specs/D-kit/Auto_Driving--perception_adaptation.md
docs/specs/D-kit/Auto_Driving--planning_adaptation.md

fixed the bug of viewing  the /tf_static topic in d-kit docs

fix bugs for D-kit docs

---

docs/specs/D-kit/Waypoint_following--Apollo_software_installation_cn.md

Update the Waypoint_following--Apollo_software_installation_cn.md file

Update the Waypoint_following--Apollo_software_installation_cn.md file

---

modules/perception/inference/utils/cuda_util.cu
modules/perception/inference/utils/gemm.cu
modules/perception/inference/utils/resize.cu
modules/perception/inference/utils/util.cu

cuda kernel execution configuration `<<<Ng, Nb>>>`

Perception: lint cuda kernel functions execution configuration

---

modules/prediction/README.md

Apollo 5.5 update to prediction readme
- Caution Obstacle Model
- Semantic LSTM Evaluator
- Extrapolation Predictor

Docs: Prediction update

---

modules/calibration/data/dev_kit/transform_conf/static_transform_conf.pb.txt
modules/common/configs/config_gflags.cc
modules/common/configs/config_gflags.h
modules/dreamview/conf/vehicle_data.pb.txt
modules/drivers/camera/dag/dev_kit_camera.dag
modules/drivers/camera/launch/dev_kit_camera.launch
modules/map/hdmap/hdmap_common.cc
modules/perception/production/dag/dev_kit_dag_streaming_perception.dag
modules/perception/production/launch/dev_kit_perception.launch
modules/perception/production/launch/dev_kit_perception_camera.launch
modules/tools/sensor_calibration/ins_stat_publisher.py
modules/tools/sensor_calibration/odom_publisher.py

1、add odometry generate tools for dev-kit
2、add dag & launch files for dev-kit
3、add a gflag for kMinHalfWidth in hdmap_common.cc

[D-kit]add adaption files for D-kit 

---

modules/calibration/data/dev_kit/transform_conf/static_transform_conf.pb.txt
modules/common/configs/config_gflags.cc
modules/common/configs/config_gflags.h
modules/dreamview/conf/vehicle_data.pb.txt
modules/drivers/camera/dag/dev_kit_camera.dag
modules/drivers/camera/launch/dev_kit_camera.launch
modules/map/hdmap/hdmap_common.cc
modules/perception/production/dag/dev_kit_dag_streaming_perception.dag
modules/perception/production/launch/dev_kit_perception.launch
modules/perception/production/launch/dev_kit_perception_camera.launch
modules/tools/sensor_calibration/ins_stat_publisher.py
modules/tools/sensor_calibration/odom_publisher.py

* add odometry generate tools for dev-kit
* add dag & launch files for dev-kit
* add a gflag for kMinHalfWidth in hdmap_common.cc

[D-kit]add adaption files for D-kit  (#10642)

---

modules/dreamview/backend/teleop/BUILD
modules/dreamview/backend/teleop/teleop.cc
modules/dreamview/backend/teleop/teleop.h
modules/dreamview/conf/hmi_modes/car_teleop.pb.txt
modules/dreamview/conf/hmi_modes/console_teleop.pb.txt
modules/dreamview/conf/vehicle_data.pb.txt

This refactor contains:
- node name and channel name changes
- updated vehicle_data.pb.txt and hmis (calibration data should be updated accordingly)
It should be synchronized with the corresponding teleop PR

Teleop refactor

---

docker/scripts/dev_start.sh
docker/scripts/restart_map_volume.sh

Provide a way to skip docker pulling procedure if we know exactly those images are up to date.
Call for test!
And any better option name than '-n' ?

scripts: add -n option to skip pull docker image

---

modules/drivers/velodyne/dag/velodyne16.dag
modules/drivers/velodyne/launch/velodyne16.launch

add velodyne16.dag velodyne16.launch

[Drivers/Velodyne]add velodyne16.dag velodyne16.launch

---

docs/specs/D-kit/Camera_Based_Auto_Driving--Perception_Adaptation_cn.md
docs/specs/D-kit/Lidar_Based_Auto_Driving--Sensor_Calibration_cn.md

Docs:Modified the md files of D-kit folder

Docs:Modified the md files of D-kit folder

---

docs/specs/D-kit/Auto_Driving--Virtual_Lane_Generation_cn.md
docs/specs/D-kit/Camera_Based_Auto_Driving--Perception_Adaptation_cn.md
docs/specs/D-kit/Lidar_Based_Auto_Driving--Perception_Adaptation_cn.md
docs/specs/D-kit/Lidar_Based_Auto_Driving--Sensor_Calibration_cn.md
docs/specs/D-kit/Lidar_Based_Auto_Driving--Sensor_Integration_cn.md
docs/specs/D-kit/Waypoint_Following--Vehicle_Calibration_Online_cn.md

Docs:Modified some formatting errors of the D-kit md files which are cherry-picked from branch master

Docs:Modified some formatting errors of the D-kit md files which are cherry-picked from branch master

---

docs/specs/D-kit/Camera_Based_Auto_Driving--Sensor_Calibration_cn.md

Correct some errors in [Camera_Based_Auto_Driving--Sensor_Calibration_cn.md]

[Docs]Correct some errors

---

docs/specs/D-kit/Camera_Based_Auto_Driving--Sensor_Calibration_cn.md

Correct some errors in [Camera_Based_Auto_Driving--Sensor_Calibration_cn.md]

[Docs]Correct some errors (#10772)

---

docs/specs/D-kit/Lidar_Based_Auto_Driving--Sensor_Calibration_cn.md

correct an error in Lidar_Based_Auto_Driving--Sensor_Calibration_cn.md

[Docs]modify Lidar_Based_Auto_Driving--Sensor_Calibration_cn.md

---

README.md

I misunderstood the arrow (">") as a "greater than" sign, so I couldn't understand the meaning of the phrase. It took me some time to figure out that it means upgrading from version 1.0. I think a "->" would be a more clear arrow symbol.

Clarified the versions installation order in "README.md" section "Basic Requirements:"

---

docs/specs/D-kit/Camera_Based_Auto_Driving--Sensor_Calibration_cn.md

modify Camera_Based_Auto_Driving--Sensor_Calibration_cn.md accroding to function changes

[Docs]modify Camera_Based_Auto_Driving--Sensor_Calibration_cn.md

---

docs/specs/D-kit/Camera_Based_Auto_Driving--Sensor_Calibration_cn.md

modify Camera_Based_Auto_Driving--Sensor_Calibration_cn.md accroding to function changes

[Docs]modify Camera_Based_Auto_Driving--Sensor_Calibration_cn.md (#10800)

---

docker/scripts/dev_start.sh

增加-c or --china 自动设置镜像加速选项。使用网易163镜像。

add -c optional for developer in china to set up mirror speed

---

modules/calibration/data/dev_kit/vehicle_param.pb.txt

calibration: update the dev_kit vehicle param, such as front_edge_to_center, back_edge_to_center, min_turn_radius, max_steer_angle, wheel_base, brake_deadzone and so on.

calibration: update the dev_kit vehicle param

---

modules/calibration/data/dev_kit/vehicle_param.pb.txt

calibration: update the dev_kit vehicle param which is cherry-pick from master:
calibration: update the dev_kit vehicle param, such as front_edge_to_center, back_edge_to_center, min_turn_radius, max_steer_angle, wheel_base, brake_deadzone and so on.

calibration: update the dev_kit vehicle param which is cherry-pick from master

---

modules/third_party_perception/tools/conversion_smartereye.cc

fix the bug of relative speed and direction of obstacles

third party perception: fix the bug of smartereye conversion

---

.gitignore
docker/build/installers/install_bosfs.sh
docker/build/installers/install_glew.sh
docker/build/installers/install_openh264.sh
docker/build/installers/post_install.sh
third_party/glew.BUILD

1) using system provided glew-2.0
2) remove copied /tmp/archives after install

remove archive after successful installation

---

modules/planning/tasks/optimizers/open_space_trajectory_partition/open_space_trajectory_partition.cc

OpenSpace: fix the last point of each trajectory in trajectory partition

---

modules/contrib/lgsvl_msgs/CHANGELOG.rst
modules/contrib/lgsvl_msgs/LICENSE
modules/contrib/lgsvl_msgs/README.md
modules/contrib/lgsvl_msgs/proto/BUILD
modules/contrib/lgsvl_msgs/proto/detection2d.proto
modules/contrib/lgsvl_msgs/proto/detection2darray.proto
modules/contrib/lgsvl_msgs/proto/detection3d.proto
modules/contrib/lgsvl_msgs/proto/detection3darray.proto

LGSVL Simulator change (part 4)

---

docs/specs/D-kit/Waypoint_Following--Apollo_Software_Installation_cn.md

Docs : Update the Waypoint_Following--Apollo_Software_Installation_cn.md file

Docs : Update the Waypoint_Following--Apollo_Software_Installation_cn.md file

---

modules/prediction/common/prediction_gflags.cc
modules/prediction/common/prediction_gflags.h
modules/prediction/scenario/prioritization/obstacles_prioritizer.cc
modules/prediction/scenario/prioritization/obstacles_prioritizer.h
modules/tools/prediction/data_pipelines/scripts/records_to_dump_records.sh

Prediction: refactor functions for caution pedestrian, add caution pedestrian in front for new model testing

---

.bazelignore
.gitignore
apollo.sh
apollo_docker.sh
docker/scripts/cyber_start.sh
docker/scripts/dev_start.sh
docker/scripts/release_start.sh
scripts/ota.sh
tools/bazel.rc

Bazel cache directory now defaults to ` /apollo/.cache/bazel`

Bazel: backport  --output_user_root startup option from master

---

docs/specs/D-kit/Auto_Driving--Planning_Adaptation_cn.md
docs/specs/D-kit/Camera_Based_Auto_Driving--Auto_Driving_Demonstration_cn.md
docs/specs/D-kit/Camera_Based_Auto_Driving--Perception_Adaptation_cn.md
docs/specs/D-kit/Lidar_Based_Auto_Driving--Auto_Driving_Demonstration_cn.md
docs/specs/D-kit/Lidar_Based_Auto_Driving--Perception_Adaptation_cn.md
docs/specs/D-kit/Waypoint_Following--Apollo_Software_Installation_cn.md
docs/specs/D-kit/Waypoint_Following--Vehicle_Calibration_Online_cn.md

1、modify Apollo_Software_Installation_cn.md
2、suggest users use opt method to build

[Docs]update docs for D-kit

---

docs/specs/D-kit/Auto_Driving--Planning_Adaptation_cn.md
docs/specs/D-kit/Camera_Based_Auto_Driving--Auto_Driving_Demonstration_cn.md
docs/specs/D-kit/Camera_Based_Auto_Driving--Perception_Adaptation_cn.md
docs/specs/D-kit/Lidar_Based_Auto_Driving--Auto_Driving_Demonstration_cn.md
docs/specs/D-kit/Lidar_Based_Auto_Driving--Perception_Adaptation_cn.md
docs/specs/D-kit/Waypoint_Following--Apollo_Software_Installation_cn.md
docs/specs/D-kit/Waypoint_Following--Vehicle_Calibration_Online_cn.md

1、modify Apollo_Software_Installation_cn.md
2、suggest users use opt method to build

[Docs]modify docs for D-kit

---

docs/specs/D-kit/Waypoint_Following--Apollo_Software_Installation_cn.md
docs/specs/D-kit/Waypoint_Following--Localization_Configuration_cn.md

Docs : Update the d_kit files

---

modules/dreamview/conf/hmi_modes/mkz_lgsvl.pb.txt
modules/perception/production/conf/perception/lidar/velodyne128_segmentation_conf_lgsvl.pb.txt
modules/perception/production/dag/dag_streaming_perception_lgsvl.dag
scripts/bootstrap_lgsvl.sh

Changed config files to have the simulator running correctly.

LGSVL Simulator change (part 5)

---

docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md

Modified the docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md file:
1, adjust the order of paragraphs.
2, modify the operation steps of the pre installed system's customers.

D-KIT : Modified the Apollo_Installation_cn.md file

---

docs/specs/D-kit/Third_Party_Perception/Perception_Configuration_cn.md
docs/specs/D-kit/Third_Party_Perception/Start_Auto_Driving_cn.md

Perception_Configuration_cn.md : Delete no useful changes and modify the start style of the TPP
Start_Auto_Driving_cn.md : modify the start style of the TPP

D-KIT : Modified the Perception_Configuration_cn.md and Start_Auto_Driving_cn.md files

---

modules/dreamview/backend/simulation_world/simulation_world_service.cc
modules/dreamview/backend/simulation_world/simulation_world_service.h
modules/dreamview/proto/simulation_world.proto
modules/drivers/camera/proto/BUILD
modules/drivers/gnss/proto/BUILD
modules/drivers/hesai/proto/BUILD
modules/drivers/tools/image_decompress/proto/BUILD
modules/drivers/velodyne/proto/BUILD
modules/drivers/video/proto/BUILD

Dreamview:add sensormeasurement info in simworld object at backend

---

docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md
docs/specs/D-kit/Waypoint_Following/Localization_Configuration_cn.md

1,Reorgnize the structure of the files
2,Add the default  user and password of the IPC
3,Add the website address of the network card driver
4,Add command to check the branch of apollo
5,Check the configuration of the IMU when it was upgraded

D-KIT : Modify some files which are relative with Waypoint_Following

---

docs/specs/D-kit/Waypoint_Following/Localization_Configuration_cn.md

add descriptions about how to configure planning.conf

[D-kit] add descriptions about how to configure planning.conf

---

docs/specs/D-kit/Waypoint_Following/Localization_Configuration_cn.md

add descriptions about how to configure planning.conf

 [D-kit] add descriptions about how to configure planning.conf

---

docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md
docs/specs/D-kit/Waypoint_Following/Localization_Configuration_cn.md

Add the common questions which are users usually mistake into the Apollo_Installation_cn.md and Localization_Configuration_cn.md files

D-Kit : Add questions into the Apollo_Installation_cn.md and Localization_Configuration_cn.md files

---

modules/perception/base/BUILD
modules/perception/base/concurrent_object_pool.h
modules/perception/base/frame.h
modules/perception/base/object.h
modules/perception/base/point_cloud.h
modules/perception/lidar/common/lidar_frame.h
modules/perception/lidar/lib/segmentation/cnnseg/cnn_segmentation_test.cc
modules/perception/radar/lib/detector/conti_ars_detector/conti_ars_detector_test.cc
modules/perception/radar/lib/tracker/common/radar_track.cc
scripts/clang-format.sh

http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html

Build: fix eigen error when -c dbg

---

docker/build/installers/install_golang.sh
docker/build/installers/install_qa_tools.sh
docker/scripts/cyber_into.sh
docker/scripts/cyber_start.sh

Docker: updated cyber.aarch64 image and cyber_start/into.sh

---

docs/specs/D-kit/Third_Party_Perception/Perception_Configuration_cn.md
docs/specs/D-kit/Third_Party_Perception/Sensor_Integration_cn.md
docs/specs/D-kit/Third_Party_Perception/Start_Auto_Driving_cn.md

Perception_Configuration_cn.md : Modified "dreamview" to "DreamView";
Sensor_Integration_cn.md : Modified "sentor" to "sensor";
Start_Auto_Driving_cn.md : Modified "topic" to "channel".

D-Kit : Update the Third_Party_Perception files

---

modules/calibration/data/dev_kit/dreamview_conf/data_collection_table.pb.txt
modules/dreamview/conf/vehicle_data.pb.txt

D-KIT: add the vehicle calibration data collection config and modify the dreamview config rule when select the vehicle to copy this config from the vehicle folder.

D-KIT: add the vehicle calbration data collection config

---

modules/calibration/data/dev_kit/planning_conf/planning.conf
modules/calibration/data/dev_kit/planning_conf/planning_config.pb.txt

add planning conf files for calibration module of d-kit

D-kit: add planning conf files for calibration module of d-kit

---

modules/calibration/data/dev_kit/planning_conf/planning.conf
modules/calibration/data/dev_kit/planning_conf/planning_config.pb.txt

add planning conf files for calibration module of d-kit

D-kit: add planning conf files for calibration module of d-kit 

---

WORKSPACE
tools/workspace.bzl

This reverts commit f18a4f7cf778423d7df41c8ecdd6cd0829ae7946.

Revert "Bazel: skylib|rules_proto|grpc"

---

modules/planning/common/planning_gflags.cc
modules/planning/common/planning_gflags.h
modules/planning/conf/planning.conf
modules/planning/conf/scenario/learning_model_sample_config.pb.txt
modules/planning/learning_based/model_inference/trajectory_imitation_libtorch_inference.cc
modules/planning/learning_based/model_inference/trajectory_imitation_tensorrt_inference.cc
modules/planning/proto/task_config.proto
modules/planning/scenarios/scenario_manager.cc
modules/planning/tasks/learning_model/learning_model_inference_task_test.cc
modules/planning/testdata/model_inference_test/test_libtorch_inference_task_config.pb.txt
modules/planning/testdata/model_inference_test/test_tensorrt_inference_task_config.pb.txt

Only one set of models is uploaded. Will reduce the updating frequency and number of models in the future commit to minimize affect to git history

Planning: add cpu models and a configuration on rule-based planning to learning-based transition 

---

modules/drivers/hesai/BUILD
modules/drivers/hesai/component.cc
modules/drivers/hesai/conf/hesai40p.pb.txt
modules/drivers/hesai/conf/hesai40p_compensator.pb.txt
modules/drivers/hesai/conf/hesai64.pb.txt
modules/drivers/hesai/conf/hesai64_compensator.pb.txt
modules/drivers/hesai/const_var.h
modules/drivers/hesai/dag/hesai40.dag
modules/drivers/hesai/dag/hesai64.dag
modules/drivers/hesai/driver.cc
modules/drivers/hesai/driver.h
modules/drivers/hesai/hesai40_parser.cc
modules/drivers/hesai/hesai64_parser.cc
modules/drivers/hesai/hesai_convert_component.h
modules/drivers/hesai/hesai_driver_component.h
modules/drivers/hesai/parser.cc
modules/drivers/hesai/parser.h
modules/drivers/hesai/proto/BUILD
modules/drivers/hesai/proto/config.proto
modules/drivers/hesai/proto/hesai.proto
modules/drivers/hesai/tcp_cmd_client.cc
modules/drivers/hesai/tcp_cmd_client.h
modules/drivers/hesai/type_defs.h
modules/drivers/hesai/udp_input.cc
modules/drivers/hesai/udp_input.h

cherry-pick hesai lidar driver from master to r5.5.0

support for hesai lidar (#10729)

---

tools/bazel.rc

Bazel: add coverage support

---

docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md

Modify the installation of the Socket Can in the start.sh script file.

D-Kit : Modify the installation of the Socket Can

---

docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md

D-kit : Modify the address of the install_nvidia_docker.sh script in the Apollo_Installation_cn.md file

D-kit : Modify the address of the install_nvidia_docker.sh script in the Apollo_Installation_cn.md file

---

modules/canbus/proto/devkit.proto
modules/canbus/vehicle/devkit/protocol/brake_command_101.cc
modules/canbus/vehicle/devkit/protocol/brake_command_101.h
modules/canbus/vehicle/devkit/protocol/brake_report_501.cc
modules/canbus/vehicle/devkit/protocol/brake_report_501.h
modules/canbus/vehicle/devkit/protocol/steering_command_102.cc
modules/canbus/vehicle/devkit/protocol/steering_command_102.h
modules/canbus/vehicle/devkit/protocol/steering_report_502.cc
modules/canbus/vehicle/devkit/protocol/steering_report_502.h
modules/canbus/vehicle/devkit/protocol/throttle_command_100.cc
modules/canbus/vehicle/devkit/protocol/throttle_command_100.h
modules/canbus/vehicle/devkit/protocol/throttle_report_500.cc
modules/canbus/vehicle/devkit/protocol/throttle_report_500.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_1_507.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_2_508.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_2_508.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_3_509.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_3_509.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_4_510.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_4_510.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_5_511.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_5_511.h
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h
modules/canbus/vehicle/devkit/protocol/vcu_report_505_test.cc
modules/canbus/vehicle/devkit/protocol/wheelspeed_report_506.cc
modules/canbus/vehicle/devkit/protocol/wheelspeed_report_506.h

Add the devkit protocol AEB status and some signals' units.

Canbus: add the devkit protocol AEB status and some units

---

modules/dreamview/conf/hmi_modes/dev_kit_close_loop.pb.txt
modules/dreamview/conf/hmi_modes/dev_kit_debug.pb.txt
modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt
scripts/record_bag.py

1、change stop_signal to SIGINT of mhi_mode conf files
2、add channels about camera、velodyne16 to record_bag.py

Dreamview: change recorder stop_signal to SIGINT

---

modules/canbus/proto/devkit.proto
modules/canbus/vehicle/devkit/protocol/brake_command_101.cc
modules/canbus/vehicle/devkit/protocol/brake_command_101.h
modules/canbus/vehicle/devkit/protocol/brake_report_501.cc
modules/canbus/vehicle/devkit/protocol/brake_report_501.h
modules/canbus/vehicle/devkit/protocol/steering_command_102.cc
modules/canbus/vehicle/devkit/protocol/steering_command_102.h
modules/canbus/vehicle/devkit/protocol/steering_report_502.cc
modules/canbus/vehicle/devkit/protocol/steering_report_502.h
modules/canbus/vehicle/devkit/protocol/throttle_command_100.cc
modules/canbus/vehicle/devkit/protocol/throttle_command_100.h
modules/canbus/vehicle/devkit/protocol/throttle_report_500.cc
modules/canbus/vehicle/devkit/protocol/throttle_report_500.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_1_507.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_2_508.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_2_508.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_3_509.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_3_509.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_4_510.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_4_510.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_5_511.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_5_511.h
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h
modules/canbus/vehicle/devkit/protocol/vcu_report_505_test.cc
modules/canbus/vehicle/devkit/protocol/wheelspeed_report_506.cc
modules/canbus/vehicle/devkit/protocol/wheelspeed_report_506.h

Canbus: devkit protocol: add the AEB state and some signals' unit.

Canbus: devkit protocol: add the AEB state and some signals' unit

---

modules/dreamview/conf/hmi_modes/rtk.pb.txt

1、 change recorder stop_signal to SIGINT in RTK mode

Dreamview: change recorder stop_signal to SIGINT in RTK mode

---

modules/canbus/proto/devkit.proto
modules/canbus/vehicle/devkit/protocol/ultr_sensor_5_511.cc
modules/canbus/vehicle/devkit/protocol/ultr_sensor_5_511.h
modules/canbus/vehicle/devkit/protocol/ultr_sensor_5_511_test.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h

Modify the AEB type and fix the ultrasonic protocol mistakes.

Canbus: modify the AEB type and fix the ultrasonic protocol mistakes

---

modules/drivers/camera/usb_cam.cc
modules/drivers/camera/usb_cam.h

D-Kit : Transform the pixel format from UYVY to YUYV, fix a bug of that the existing driver does not support the camera of uyuy pixel format.

D-Kit : Transform the pixel format from UYVY to YUYV

---

docker/build/installers/installer_base.sh

`SM +=[5.0]` to support cuda architecture "Maxwell".

Docker: enable cuda arch "Maxwell" support

---

docs/specs/D-kit/Waypoint_Following/Localization_Configuration_cn.md
modules/calibration/data/dev_kit/gnss_conf/gnss_conf.pb.txt

1、Update the configuration of the GNSS;
2、Modify the baud rate of the IMU;

D-Kit : Update Localization_Configuration_cn.md and gnss_conf.pb.txt of the dev-kit

---

docker/scripts/dev_start.sh

This reverts commit 798190ad141ec3c1926e6ff2e5cc1f81974500a8.

Revert "dev_start:add image exist judge" unless bugfixed

---

modules/audio/tools/BUILD
modules/audio/tools/audiosaver.py

* Subscribe audio channel and save all channels data to wave files.
* Fix: Remove an unnecessary `import` on audio driver proto...

Audio: add audio wave saver for testing

---

docker/build/installers/install_boost.sh

Docker: update user-config.jam to be consistent with openmpi 

---

modules/localization/msf/BUILD
modules/localization/msf/msf_localization.cc
modules/localization/msf/msf_localization.h
modules/localization/msf/msf_localization_component.cc
modules/localization/msf/msf_localization_component.h

Localization: raw imu frequency match with odometry frequency

Localization: raw imu frequency match with odometry frequency

---

modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc

Canbus: fix filter size in socket CAN

---

modules/audio/audio_component.cc
modules/audio/audio_component.h
modules/audio/conf/audio_conf.pb.txt
modules/audio/conf/respeaker_extrinsics.yaml
modules/audio/inference/BUILD
modules/audio/inference/direction_detection.cc
modules/audio/inference/direction_detection.h
modules/audio/proto/BUILD
modules/audio/proto/audio.proto
modules/audio/proto/audio_conf.proto
modules/dreamview/conf/vehicle_data.pb.txt

* Fix bugs in direction detection -- didn't notice LibTorch does not support complex type, etc.
* add direction transformation code
* Refactor the direction_detection to a class

Audio: add direction transformation code, refactor & fix bugs

---

modules/audio/common/audio_info.cc
modules/drivers/microphone/conf/respeaker.pb.txt
modules/drivers/microphone/microphone_component.cc
modules/drivers/microphone/proto/audio.proto

* Lower frequency of microphone to about 6Hz (0.17 s)
* Remove size in proto (it doesn't work actually, I guess it's due to some conflicts with protocol buffer)
* I added it previously with the concern that '\0' might influence the size of data (chars)
* But it won't, refer to [here](https://stackoverflow.com/questions/11467567/why-protocol-buffer-bytes-is-string-in-c). So just use string.length()

Drivers: decrese microphone driver frequency

---

.github/ISSUE_TEMPLATE/issues.md

```
Prompt> ./apollo.sh config
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2020-08-13-5270c6761e
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20200811_2001
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=true USE_GPU=1
```

infra: updated issue template for "apollo.sh config" on master

---

modules/common/monitor_log/monitor_logger.cc
modules/common/util/message_util.h
modules/data/tools/smart_recorder/realtime_record_processor.cc
modules/dreamview/backend/hmi/hmi_worker.cc
modules/guardian/guardian_component.cc
modules/planning/open_space/trajectory_smoother/BUILD
modules/planning/open_space/trajectory_smoother/distance_approach_problem.cc
modules/planning/open_space/trajectory_smoother/dual_variable_warm_start_problem.cc
modules/transform/buffer.cc

MockTime support: time/PERF updated

---

scripts/pad.sh

Sample script to enable the `restart` option @lx18233184051 
See https://github.com/ApolloAuto/apollo/pull/12182#discussion_r473484113

Scripts: "restart" option for pad.sh

---

modules/audio/BUILD
modules/audio/audio_component.cc
modules/audio/proto/BUILD
modules/audio/proto/audio.proto
modules/drivers/microphone/conf/respeaker.pb.txt

Find this TODO when writing auto labeler -- not feasible without timestamp in Header

Audio: add Header to proto

---

docs/specs/D-kit/Waypoint_Following/Localization_Configuration_cn.md

D-kit : Add the solve solution of the problem that the signal of the IMU is single.

D-kit : Add the solve solution of the problem that the signal of the IMU is single

---

modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt

HMI: add audio detection button in debug mode

---

modules/perception/tool/benchmark/lidar/util/io_util.cc

tainted_data_argument: Calling function operator >> taints argument object_number
Untrusted loop bound (TAINTED_SCALAR)： tainted_data: Using tainted variable object_number as a loop boundary.

perception:io_util add range check

---

modules/perception/lidar/lib/classifier/fused_classifier/util.cc
modules/perception/tool/benchmark/lidar/util/io_util.cc

perception: check num to make sure its range

---

modules/audio/proto/BUILD
modules/audio/proto/audio.proto
modules/audio/proto/audio_common.proto
modules/audio/proto/audio_event.proto
modules/tools/common/BUILD
modules/tools/common/message_manager.py
modules/tools/rosbag/BUILD
modules/tools/rosbag/audio_event_record.py

Tools: add initial audio_event_record

---

cyber/tools/cyber_channel/cyber_channel.py

fix error described in #12279.

Cyber: fix cyber_channel error

---

.teamcity/run_ci.sh
scripts/apollo_build.sh
scripts/apollo_coverage.sh
scripts/apollo_test.sh

This PR is a follow up of #12282 
It provides a workaround for Bazel's `/usr/bin/bazel: Argument list too long` error.
See https://github.com/bazelbuild/intellij/issues/1081
Should be rebased after #12282  was checked in. 
Besides,  all common functions to `scripts/apollo_{build,test,coverage}.sh` should go to `apollo.bashrc`.
Will be done in the next PRs.

Workaround for Bazel error "Argument list too long"

---

modules/planning/README.md

For better html output for mkdocs

Docs: updated format for planning/README.md

---

cyber/transport/BUILD
modules/dreamview/backend/simulation_world/simulation_world_service.cc
modules/dreamview/backend/simulation_world/simulation_world_service.h
modules/dreamview/frontend/src/renderer/obstacles.js
modules/dreamview/frontend/src/store/config/MenuData.js
modules/dreamview/frontend/src/store/config/parameters.yml
modules/dreamview/frontend/src/utils/draw.js
modules/dreamview/proto/simulation_world.proto
modules/perception/proto/perception_obstacle.proto

Dreamview:Implement the v2x feature

---

modules/canbus/proto/devkit.proto
modules/canbus/vehicle/devkit/protocol/brake_command_101.cc
modules/canbus/vehicle/devkit/protocol/brake_command_101.h
modules/canbus/vehicle/devkit/protocol/gear_command_103.cc
modules/canbus/vehicle/devkit/protocol/gear_command_103.h
modules/canbus/vehicle/devkit/protocol/park_command_104.cc
modules/canbus/vehicle/devkit/protocol/park_command_104.h
modules/canbus/vehicle/devkit/protocol/steering_command_102.cc
modules/canbus/vehicle/devkit/protocol/steering_command_102.h
modules/canbus/vehicle/devkit/protocol/throttle_command_100.cc
modules/canbus/vehicle/devkit/protocol/throttle_command_100.h

modify some protocol name and add some units in vehicle devkit

Canbus: modify some protocol name and add some units in vehicle devkit

---

cyber/python/internal/py_cyber.cc
cyber/tools/cyber_channel/BUILD
cyber/tools/cyber_channel/cyber_channel.py

Cyber: fix decoding error when using cyber_channel info

---

scripts/apollo_format.sh
scripts/autopep8.sh
scripts/clang_format.sh
scripts/shfmt.sh

If no option specified, parse all.

Scripts: improved apollo_format.sh

---

docs/specs/D-kit/Waypoint_Following/Localization_Configuration_cn.md

D-Kit : Add the rules file of Newton M2 GPS device

D-Kit : Add the rules file of Newton M2 GPS device

---

modules/calibration/data/dev_kit/gnss_conf/gnss_conf.pb.txt

D-Kit : Update the gnss conf file

D-Kit : Update the gnss conf file

---

scripts/record_bag.py

The overall logic has been verified and works fine.

Recorder: add audio event into small bag

---

modules/map/hdmap/hdmap_common.cc

map: remove a function that always return true

---

modules/dreamview/backend/BUILD
modules/dreamview/backend/teleop/BUILD
modules/monitor/hardware/esdcan_monitor.cc
modules/planning/open_space/trajectory_smoother/distance_approach_ipopt_cuda_interface.cc
tools/apollo.bazelrc.sample
tools/platform/BUILD
tools/platform/build_defs.bzl

Should run `rm -rf ${APOLLO_ROOT_DIR}/.apollo.bazelrc` for the change to take effect.

Build: unified use for USE_ESD_CAN & WITH_TELEOP & USE_GPU

---

modules/v2x/proto/BUILD
modules/v2x/proto/v2x_junction.proto
modules/v2x/proto/v2x_monitor.proto
modules/v2x/proto/v2x_obu_rsi.proto
modules/v2x/proto/v2x_obu_traffic_light.proto
modules/v2x/proto/v2x_rsi.proto

V2X: splited PR2: add forked and new proto

V2X: splited PR2: add new proto

---

modules/v2x/BUILD
modules/v2x/common/v2x_proxy_gflags.cc
modules/v2x/proto/v2x_obu_traffic_light.proto
modules/v2x/proto/v2x_traffic_light.proto
modules/v2x/v2x_proxy/proto_adapter/BUILD
modules/v2x/v2x_proxy/proto_adapter/proto_adapter.cc
modules/v2x/v2x_proxy/proto_adapter/proto_adapter.h
modules/v2x/v2x_proxy/proto_adapter/proto_adapter_test.cc

V2X: splited PR3: add proto adapter

V2X: splited PR3: add proto adapter

---

docker/scripts/dev_start.sh

Add yolov4 in Apollo

---

modules/dreamview/frontend/src/renderer/obstacles.js

为了让v2x特征更显眼一点，把v2x type text颜色变成红色

Dreamview: change the v2x text color to red

---

modules/common/proto/BUILD
modules/common/proto/direction.proto

Common: add directrion proto

---

docker/scripts/dev_start.sh

dev_start.sh: added notes on "jq not found" for geolocation setter

---

scripts/apollo_build.sh
scripts/apollo_test.sh

Build: update bazel except for cpu mode

---

modules/calibration/data/dev_kit/planning_conf/planning.conf

change default planning params to make nudge more obvious

Dkit: change default planning params to make nudge more obvious

---

docs/D-kit/Waypoint_Following/localization_configuration_cn.md
docs/D-kit/sample/imu.conf
modules/calibration/data/dev_kit/gnss_conf/gnss_conf.pb.txt

D-Kit : Simplified the GNSS configuration

D-Kit : Simplified the GNSS configuration

---

modules/map/hdmap/adapter/opendrive_adapter.cc
modules/map/hdmap/adapter/proto_organizer.cc
modules/map/hdmap/adapter/proto_organizer.h
modules/map/hdmap/adapter/xml_parser/common_define.h
modules/map/hdmap/adapter/xml_parser/objects_xml_parser.cc
modules/map/hdmap/adapter/xml_parser/objects_xml_parser.h
modules/map/hdmap/hdmap.cc
modules/map/hdmap/hdmap.h
modules/map/hdmap/hdmap_common.cc
modules/map/hdmap/hdmap_common.h
modules/map/hdmap/hdmap_impl.cc
modules/map/hdmap/hdmap_impl.h
modules/map/proto/BUILD
modules/map/proto/map.proto
modules/map/proto/map_overlap.proto
modules/map/proto/map_rsu.proto

1. add rus element in hdmap;
2. add hdmap interface;

HDMap: add rsu element for hdmap

---

scripts/apollo.bashrc
scripts/apollo_format.sh
scripts/autopep8.sh
scripts/clang_format.sh
scripts/mdfmt.sh

With this PR, we no longer need to run various formatters on the same file, since a file can only be formatted by one formatter.

Scripts: make "apollo.sh format" smarter

---

apollo.sh
docs/specs/linters_and_formatters.md
scripts/apollo_lint.sh

Allow multiple options to be specified simultaneously.

apollo.sh: apollo.sh lint --help support

---

docker/build/installers/install_bazel.sh
docker/build/installers/install_device_query.sh

Used by `apollo_config.sh` interactive mode.

Docker: add deviceQuery binary to determine cuda compute capability

---

modules/v2x/launch/v2x.launch

remove v2x fusion dag in launch

V2X: remove v2x fusion dag in launch

---

docs/quickstart/apollo_3_0_hardware_system_installation_guide.md
docs/quickstart/apollo_3_0_quick_start.md
docs/quickstart/apollo_3_0_quick_start_cn.md
docs/quickstart/apollo_3_5_quick_start.md
docs/quickstart/apollo_5_0_quick_start.md
docs/quickstart/apollo_5_5_quick_start.md

According markdownlint to format some quick start docs

docs: format some quick start docs

---

modules/calibration/data/dev_kit/planning_conf/planning.conf

1、change default planning params to make nudge more obvious

Dkit: change default planning params to make nudge more obvious (#12499)

---

modules/dreamview/conf/vehicle_data.pb.txt

add perception_conf to calibration modules

D-KIT: add perception_conf to calibration modules (#12652)

---

docs/D-kit/Camera_Based_Auto_Driving/perception_configuration_cn.md
docs/D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md
docs/D-kit/Camera_Based_Auto_Driving/start_auto_driving_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/perception_configuration_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/sensor_integration_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/start_auto_driving_cn.md
docs/D-kit/Third_Party_Perception/perception_configuration_cn.md
docs/D-kit/Third_Party_Perception/start_auto_driving_cn.md
docs/D-kit/Waypoint_Following/localization_configuration_cn.md
docs/D-kit/Waypoint_Following/start_waypoint_following_cn.md

add more details about how to use cyber_monitor

D-KIT:add more details about how to use cyber_monitor

---

docs/D-kit/Camera_Based_Auto_Driving/perception_configuration_cn.md
docs/D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md
docs/D-kit/Camera_Based_Auto_Driving/start_auto_driving_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/perception_configuration_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/sensor_integration_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/start_auto_driving_cn.md
docs/D-kit/Third_Party_Perception/perception_configuration_cn.md
docs/D-kit/Third_Party_Perception/start_auto_driving_cn.md
docs/D-kit/Waypoint_Following/localization_configuration_cn.md
docs/D-kit/Waypoint_Following/start_waypoint_following_cn.md

:add more details about how to use cyber_monitor

D-KIT:add more details about how to use cyber_monitor (#12688)

---

cyber/class_loader/test/base.h
cyber/service_discovery/topology_manager.h

cyber: unified preprocessing format

cyber: unified preprocessing format

---

modules/tools/sensor_calibration/extract_data.py
modules/tools/sensor_calibration/proto/extractor_config.proto

multi lidars data extraction available in data extract tool

Tools: multi lidars data extraction available in data extract tool

---

modules/calibration/data/dev_kit/radar_dag/conti_radar.dag
modules/dreamview/conf/vehicle_data.pb.txt

add radar dag file to calibration

D-KIT: add radar dag file to calibration

---

modules/calibration/data/dev_kit/radar_dag/conti_radar.dag
modules/dreamview/conf/vehicle_data.pb.txt

add radar dag file to calibration

D-KIT: add radar dag file to calibration (#12752)

---

modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc

change the socket can filter for devkit

Driver: change the socket can filter for devkit for master

---

modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc

change the socket can filter for devkit which is cherry-picked from master

Driver: change the socket can filter for devkit

---

modules/monitor/software/channel_monitor.cc

Replaced channel identification based on serial string matching with hash map matching.
Ran format, lint and tests on monitor module.

Monitor: Optimized GetReaderAndLatestMessage function

---

modules/canbus/proto/devkit.proto
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h
modules/canbus/vehicle/devkit/protocol/vcu_report_505_test.cc

add the battery info protocol in devkit

Canbus: add the battery info protocol in devkit

---

docker/scripts/cyber_start.sh
docker/scripts/dev_start.sh

{cyber,dev}_start.sh: registry.baidubce.com for hosting Apollo Docker images for CN users

---

modules/localization/msf/BUILD
modules/localization/msf/msf_localization.cc
modules/localization/msf/msf_localization.h
modules/localization/msf/msf_localization_component.cc
modules/localization/msf/msf_localization_component.h

D-Kit : Add localization timer

D-Kit : Add localization timer

---

modules/localization/msf/BUILD
modules/localization/msf/msf_localization.cc
modules/localization/msf/msf_localization.h
modules/localization/msf/msf_localization_component.cc
modules/localization/msf/msf_localization_component.h

D-Kit : Add localization timer

D-Kit : Add localization timer (#12796)

---

modules/tools/record_play/rtk_recorder.py
scripts/rtk_recorder.sh

Scripts: rtk_recorder/rtk_player log dir for issue #12831

Scripts: log dir, fix issue #12831

---

modules/canbus/proto/chassis.proto
modules/canbus/proto/devkit.proto
modules/canbus/vehicle/devkit/devkit_controller.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h
modules/canbus/vehicle/devkit/protocol/vcu_report_505_test.cc

1. add the new battery soc protocol in chassis for vehicle dev_kit;
2. fix a typo in dev_kit.

canbus: add the new battery soc protocol in chassis for vehicle dev_kit

---

modules/canbus/proto/chassis.proto
modules/canbus/vehicle/devkit/devkit_controller.cc

fix a typo in chassis battery soc info

canbus: fix a typo in chassis battery soc info

---

cyber/transport/common/endpoint.cc
cyber/transport/common/endpoint.h
cyber/transport/common/endpoint_test.cc
cyber/transport/common/identity.cc
cyber/transport/common/identity.h
cyber/transport/common/identity_test.cc
cyber/transport/message/message_info.cc
cyber/transport/rtps/underlay_message.cc
cyber/transport/rtps/underlay_message.h
cyber/transport/shm/block.h
third_party/fastrtps/workspace.bzl

1) simplified identity implementation
2) remove WIN32 related preprocessing

cyber: code optimization for transport

---

modules/canbus/proto/ch.proto
modules/canbus/vehicle/ch/ch_controller.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.h
modules/canbus/vehicle/ch/protocol/ecu_status_2_516_test.cc

add the battery info in vehicle ch

canbus: add the battery info in vehicle ch

---

modules/canbus/proto/ch.proto
modules/canbus/proto/chassis.proto
modules/canbus/proto/devkit.proto
modules/canbus/vehicle/ch/ch_controller.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.cc
modules/canbus/vehicle/ch/protocol/ecu_status_2_516.h
modules/canbus/vehicle/ch/protocol/ecu_status_2_516_test.cc
modules/canbus/vehicle/devkit/devkit_controller.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h
modules/canbus/vehicle/devkit/protocol/vcu_report_505_test.cc

add the new battery soc protocol in vehicle dev_kit
add the battery info in vehicle ch

Canbus: add the battery info in vehicle devkit and ch for chassis info

---

docker/build/installers/install_libtorch.sh
docker/build/installers/installer_base.sh
docker/build/user_dev.x86_64.dockerfile
docker/scripts/cyber_start.sh
docker/scripts/dev_start.sh
third_party/npp/npp.BUILD

Enable it with `dev_start.sh -d testing`.

Ampere support:  dev.x86_64 image for cuda-11.1

---

modules/tools/sensor_calibration/extract_data.py

add default main_sensor value to data extract tool

D-KIT:add default main_sensor value to data extract tool

---

modules/tools/sensor_calibration/extract_data.py

add default main_sensor in data extract tool

D-KIT:add default main_sensor in data extract tool (#12941)

---

docs/howto/how_to_clone_apollo_repo_from_china.md
docs/howto/how_to_clone_apollo_repo_from_china_cn.md

Docs : Modified the apollo address of gitee

Docs : Modified the apollo address of gitee

---

docs/D-kit/Waypoint_Following/apollo_installation_cn.md

D-Kit : Modified the method of cloning the apollo code

D-Kit : Modified the method of cloning the apollo code

---

docs/howto/how_to_clone_apollo_repo_from_china.md
docs/howto/how_to_clone_apollo_repo_from_china_cn.md

Docs : Update the apollo address of gitee

Docs : Update the apollo address of gitee

---

docs/howto/how_to_clone_apollo_repo_from_china.md
docs/howto/how_to_clone_apollo_repo_from_china_cn.md

Docs : Add the how_to_clone_apollo_repo_from_china.md to branch r6.0.0

Docs : Add the how_to_clone_apollo_repo_from_china.md to branch r6.0.0

---

docs/howto/how_to_clone_apollo_repo_from_china.md
docs/howto/how_to_clone_apollo_repo_from_china_cn.md

Docs : Add the how_to_clone_apollo_repo_from_china.md to branch r5.5.0

Docs : Add the how_to_clone_apollo_repo_from_china.md to branch r5.5.0

---

docs/D-kit/Waypoint_Following/localization_configuration_cn.md

D-Kit : Modified the localization_configuration_cn.md file

D-Kit : Modified the localization_configuration_cn.md file

---

docs/specs/D-kit/Waypoint_Following/Localization_Configuration_cn.md

D-Kit : Modified the localization_configuration_cn.md file (#13001)

D-Kit : Modified the localization_configuration_cn.md file (#13001)

---

docs/D-kit/Waypoint_Following/localization_configuration_cn.md

D-Kit : Update the localization_configuration_cn.md file

D-Kit : Update the localization_configuration_cn.md file

---

modules/tools/record_parse_save/BUILD
modules/tools/record_parse_save/README.md
modules/tools/record_parse_save/record_parse_save.py

related issue is reported in #13022

Tools: updated record_parse_save and relevant instructions

---

modules/canbus/proto/neolix_edu.proto
modules/canbus/vehicle/neolix_edu/neolix_edu_controller.cc
modules/canbus/vehicle/neolix_edu/protocol/vcu_powerstatus_214.cc
modules/canbus/vehicle/neolix_edu/protocol/vcu_powerstatus_214.h

which is cherry-picked from master.

canbus: neolix_edu add battery signals (#13044)

---

docs/D-kit/Waypoint_Following/apollo_installation_cn.md

D-Kit : Add the git operations to the apollo_installation_cn.md file

D-Kit : Add the git operations to the apollo_installation_cn.md file

---

modules/calibration/data/dev_kit/lidar_conf/lidar_conf.pb.txt
modules/calibration/data/dev_kit/lidar_params/velodyne16_novatel_extrinsics.yaml
modules/calibration/data/dev_kit/transform_conf/static_transform_conf.pb.txt
modules/calibration/data/dev_kit_advanced_ne-b/lidar_conf/surestar.conf
modules/calibration/data/dev_kit_advanced_ne-b/lidar_params/velodyne16_novatel_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_ne-b/transform_conf/static_transform_conf.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/lidar_conf/rs16.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/lidar_params/velodyne16_novatel_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_ne-s/transform_conf/static_transform_conf.pb.txt
modules/calibration/data/dev_kit_advanced_sne-r/lidar_params/velodyne16_novatel_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_sne-r/transform_conf/static_transform_conf.pb.txt
modules/calibration/data/dev_kit_standard/lidar_conf/lidar_conf.pb.txt
modules/calibration/data/dev_kit_standard/lidar_params/velodyne16_novatel_extrinsics.yaml
modules/calibration/data/dev_kit_standard/transform_conf/static_transform_conf.pb.txt

This reverts commit b08acc2c86723fddd24c98e7a3ef7a9c694a5888.

Revert "D-kit: Fix the frame id from 'velodyne16' to 'lidar16'"

---

modules/monitor/hardware/BUILD
modules/monitor/hardware/gps_monitor.cc

Monitor : Change the monitored GPS signal from GnssStatus and InsStatus to SolutionType of GnssBestPose

Monitor : Change the monitored GPS signal from GnssStatus and InsStatus to SolutionType of GnssBestPose

---

modules/canbus/proto/chassis.proto
modules/canbus/proto/devkit.proto
modules/canbus/vehicle/ch/ch_controller.cc
modules/canbus/vehicle/devkit/devkit_controller.cc
modules/canbus/vehicle/devkit/devkit_message_manager.cc
modules/canbus/vehicle/devkit/devkit_message_manager_test.cc
modules/canbus/vehicle/devkit/protocol/BUILD
modules/canbus/vehicle/devkit/protocol/bms_report_512.cc
modules/canbus/vehicle/devkit/protocol/bms_report_512.h
modules/canbus/vehicle/devkit/protocol/bms_report_512_test.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h
modules/dreamview/proto/simulation_world.proto

canbus: update the devkit bms report
canbus: modify the battery soc good display for ch
dreamview: modify the types of battery percent

Canbus: update battery info for good display in D-KIT

---

modules/canbus/proto/chassis.proto
modules/canbus/proto/devkit.proto
modules/canbus/vehicle/ch/ch_controller.cc
modules/canbus/vehicle/devkit/devkit_controller.cc
modules/canbus/vehicle/devkit/devkit_message_manager.cc
modules/canbus/vehicle/devkit/devkit_message_manager_test.cc
modules/canbus/vehicle/devkit/protocol/BUILD
modules/canbus/vehicle/devkit/protocol/bms_report_512.cc
modules/canbus/vehicle/devkit/protocol/bms_report_512.h
modules/canbus/vehicle/devkit/protocol/bms_report_512_test.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h
modules/dreamview/proto/simulation_world.proto

* dreamview: modify the types of battery percent
* canbus: modify the battery soc display in ch
* canbus: update the devkit bms report

Canbus: update battery info for good display in D-KIT (#13110)

---

modules/canbus/proto/chassis.proto
modules/canbus/proto/devkit.proto
modules/canbus/vehicle/ch/ch_controller.cc
modules/canbus/vehicle/devkit/devkit_controller.cc
modules/canbus/vehicle/devkit/devkit_message_manager.cc
modules/canbus/vehicle/devkit/devkit_message_manager_test.cc
modules/canbus/vehicle/devkit/protocol/BUILD
modules/canbus/vehicle/devkit/protocol/bms_report_512.cc
modules/canbus/vehicle/devkit/protocol/bms_report_512.h
modules/canbus/vehicle/devkit/protocol/bms_report_512_test.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.cc
modules/canbus/vehicle/devkit/protocol/vcu_report_505.h

update the devkit battery soc and ch battery info

canbus: update the devkit battery soc and ch battery info

---

docs/D-kit/Waypoint_Following/apollo_installation_cn.md
docs/D-kit/Waypoint_Following/reinstall_my_apollo_system_cn.md

D-Kit : Separate the reinstall_my_apollo_system_cn.md from apollo_installation_cn.md

D-Kit : Separate the reinstall_my_apollo_system_cn.md from apollo_installation_cn.md

---

modules/tools/record_play/rtk_recorder.py

modify the rtk_record in curvature for different vehicles

RTK: modify the rtk_record curvature for different vehicles

---

apollo.sh

D-Kit : Open the building of the visualizer

D-Kit : Open the building of the visualizer

---

modules/calibration/data/dev_kit_standard/control_conf.pb.txt
modules/calibration/data/dev_kit_standard/dreamview_conf/data_collection_table.pb.txt
modules/calibration/data/dev_kit_standard/vehicle_param.pb.txt
modules/canbus/proto/devkit.proto
modules/canbus/vehicle/devkit/devkit_controller.cc
modules/canbus/vehicle/devkit/protocol/brake_command_101.cc
modules/canbus/vehicle/devkit/protocol/brake_command_101.h
modules/canbus/vehicle/devkit/protocol/steering_command_102.cc
modules/canbus/vehicle/devkit/protocol/steering_command_102.h
modules/canbus/vehicle/devkit/protocol/steering_command_102_test.cc
modules/canbus/vehicle/devkit/protocol/steering_report_502.cc
modules/canbus/vehicle/devkit/protocol/steering_report_502.h
modules/canbus/vehicle/devkit/protocol/steering_report_502_test.cc

Canbus: add aeb control command in devkit   
Canbus: update steering command and report in devkit
Calibration:update kinetic calibration parameter for dev_kit_standard (#13141)

Canbus: add aeb control command in devkit cherry pick from master

---

modules/common/adapters/adapter_gflags.cc
modules/common/adapters/adapter_gflags.h
modules/dreamview/conf/hmi_modes/dev_kit_close_loop.pb.txt
modules/dreamview/conf/hmi_modes/dev_kit_debug.pb.txt
modules/dreamview/conf/hmi_modes/vehicle_calibration.pb.txt
modules/monitor/software/channel_monitor.cc

add pointcloud_16_topic to monitor module

add pointcloud_16_topic to monitor module

---

modules/calibration/data/dev_kit_standard/cancard_params/canbus.conf
modules/canbus/common/canbus_gflags.cc
modules/canbus/common/canbus_gflags.h
modules/canbus/vehicle/devkit/BUILD
modules/canbus/vehicle/devkit/devkit_controller.cc

canbus: add the aeb control flag for DKIT Standard

canbus: add the aeb control flag for DKIT Standard

---

cyber/base/bounded_queue.h

cyber: BoundedQueue Enqueue(T&&) use std::move to change lvalue to rvalue #13156

cyber: BoundedQueue Enqueue(T&&) use std::move to change lvalue to rvalue

---

modules/common/adapters/adapter_gflags.cc
modules/common/adapters/adapter_gflags.h
modules/dreamview/conf/hmi_modes/dev_kit_close_loop.pb.txt
modules/dreamview/conf/hmi_modes/dev_kit_debug.pb.txt
modules/monitor/software/channel_monitor.cc

1、add pointcloud_16_topic to monitor module

monitor: add pointcloud_16_topic to monitor module

---

modules/common/adapters/adapter_gflags.cc
modules/common/adapters/adapter_gflags.h
modules/dreamview/conf/hmi_modes/dev_kit_close_loop.pb.txt
modules/dreamview/conf/hmi_modes/dev_kit_debug.pb.txt
modules/monitor/software/channel_monitor.cc

add pointcloud_16_topic to monitor module

monitor: add pointcloud_16_topic to monitor module (#13184)

---

modules/calibration/data/dev_kit_standard/cancard_params/canbus.conf
modules/canbus/common/canbus_gflags.cc
modules/canbus/common/canbus_gflags.h
modules/canbus/vehicle/devkit/devkit_controller.cc

canbus: modify the aeb control flag for D-KIT

canbus: modify the aeb control flag for D-KIT

---

docs/D-kit/Waypoint_Following/apollo_installation_cn.md

D-Kit : Update the apollo_installation_cn.md file

D-Kit : Update the apollo_installation_cn.md file

---

modules/tools/record_analyzer/common/distribution_analyzer.py
modules/tools/record_analyzer/common/error_code_analyzer.py
modules/tools/record_analyzer/common/error_msg_analyzer.py
modules/tools/record_analyzer/module_control_analyzer.py

Please help check the PR works @changsh726 . Used demo_3.5.record from docs/demo_guide/ as an example.
this fixed issue #12136

Bugfix: modules/tools/record_analyzer/main

---

modules/perception/lidar/lib/detection/lidar_point_pillars/postprocess_cuda.cu

fix a bug in postprocess_cuda.cu that affects nms of pointpillars

---

modules/perception/onboard/component/fusion_camera_detection_component.cc
modules/perception/onboard/component/fusion_camera_detection_component.h
modules/perception/onboard/proto/fusion_camera_detection_component.proto

make lidar height file could be specified

Perception: make lidar height file could be specified

---

scripts/apollo_base.sh

https://huntr.dev/users/Anon-Artist has fixed the Arbitrary Code Execution vulnerability 🔨. Think you could fix a vulnerability like this?
Get involved at https://huntr.dev/
Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/apollo/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/other/apollo/1/README.md
Arbitrary code exec vulnerability 
Arbitrary Code Excecution in gen_proto_file.py in ApolloAuto/Apollo. An open autonomous driving platform.
This package was vulnerable to Arbitrary code execution due to the use of a known vulnerable function load() in YAML. Changing that to safe_load or using SafeLoader will fix the issue.
Install the package and run the below code:
```import os
exploit = '''protocol_conf: …
```

Security Fix for Arbitrary Code Execution - huntr.dev

---

modules/perception/camera/lib/traffic_light/detector/detection/detection.cc
modules/perception/camera/lib/traffic_light/detector/recognition/classify.cc
modules/perception/camera/lib/traffic_light/detector/recognition/recognition.h
modules/perception/inference/tensorrt/entropy_calibrator.cc
modules/perception/inference/tensorrt/entropy_calibrator.h
modules/perception/inference/tensorrt/entropy_calibrator_test.cc
modules/perception/inference/tensorrt/plugins/BUILD
modules/perception/inference/tensorrt/plugins/dfmb_psroi_align_plugin.cu
modules/perception/inference/tensorrt/plugins/dfmb_psroi_align_plugin.h
modules/perception/inference/tensorrt/plugins/kernels.cu
modules/perception/inference/tensorrt/plugins/kernels.h
modules/perception/inference/tensorrt/plugins/nms_cuda.cu
modules/perception/inference/tensorrt/plugins/rcnn_proposal_plugin.cu
modules/perception/inference/tensorrt/plugins/rcnn_proposal_plugin.h
modules/perception/inference/tensorrt/plugins/rpn_proposal_ssd_plugin.cu
modules/perception/inference/tensorrt/plugins/rpn_proposal_ssd_plugin.h
modules/perception/inference/tensorrt/plugins/softmax_plugin.h
modules/perception/inference/tensorrt/rt_common.cc
modules/perception/inference/tensorrt/rt_common.h
modules/perception/inference/tensorrt/rt_net.cc
modules/perception/inference/tensorrt/rt_net.h
modules/perception/onboard/component/trafficlights_perception_component.cc
modules/perception/production/conf/perception/perception_common.flag
modules/perception/production/data/perception/camera/models/traffic_light_detection/deploy.prototxt
modules/perception/production/data/perception/camera/models/traffic_light_detection/detection.pt
modules/perception/production/data/perception/camera/models/traffic_light_recognition/recognition.pt
modules/perception/proto/rt.proto

1. Resume traffic light Caffe model.
2. Load traffic light detection Caffe model into TensorRT by defining TensoRT plugins.
3. Fix some problems in rt_net.

Perception: resume traffic light module

---

modules/calibration/data/dev_kit/vehicle_param.pb.txt
modules/calibration/data/dev_kit_standard/vehicle_param.pb.txt

Add the stop speed in dev_kit and dev_kit_standard.

Calibration: add the stop speed in DKIT

---

modules/planning/open_space/coarse_trajectory_generator/grid_search.cc
modules/planning/open_space/coarse_trajectory_generator/grid_search.h

This reverts commit 5ddf4e3749170d7aa44ee7767d48b453b8321eea.

Revert "Planning: fix collision check in grid_search (#11524)"

---

modules/calibration/data/dev_kit/perception_dag/dag_streaming_perception_dev_kit_lidar.dag
modules/calibration/data/dev_kit/transform_conf/static_transform_conf.pb.txt
modules/calibration/data/dev_kit_advanced_ne-b/perception_dag/dag_streaming_perception_dev_kit_lidar.dag
modules/calibration/data/dev_kit_advanced_ne-b/planning_conf/planning_config.pb.txt
modules/calibration/data/dev_kit_advanced_ne-b/transform_conf/static_transform_conf.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/perception_dag/dag_streaming_perception_dev_kit_lidar.dag
modules/calibration/data/dev_kit_advanced_ne-s/planning_conf/planning_config.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/transform_conf/static_transform_conf.pb.txt
modules/calibration/data/dev_kit_advanced_sne-r/perception_dag/dag_streaming_perception_dev_kit_lidar.dag
modules/calibration/data/dev_kit_advanced_sne-r/planning_conf/planning_config.pb.txt
modules/calibration/data/dev_kit_advanced_sne-r/transform_conf/static_transform_conf.pb.txt
modules/calibration/data/dev_kit_standard/perception_dag/dag_streaming_perception_dev_kit_lidar.dag
modules/calibration/data/dev_kit_standard/planning_conf/planning_config.pb.txt
modules/calibration/data/dev_kit_standard/transform_conf/static_transform_conf.pb.txt

1、correct tf_static conf & modify planning conf
2、add v2x config to lidar perception dag file

D-KIT:correct tf_static conf & add v2x config to lidar perception dag file

---

docker/build/installers/install_deviceQuery.sh

I encountered a trouble (download time out) while trying to install the prebuillt deviceQuery binary and made the alternative install script.

Docker: Update deviceQuery install script

---

modules/calibration/data/dev_kit/camera_params/front_12mm_extrinsics.yaml
modules/calibration/data/dev_kit/camera_params/front_6mm_extrinsics.yaml
modules/calibration/data/dev_kit/radar_params/radar_front_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_ne-b/camera_params/front_12mm_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_ne-b/camera_params/front_6mm_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_ne-b/radar_params/radar_front_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_ne-s/camera_params/front_12mm_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_ne-s/camera_params/front_6mm_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_ne-s/radar_params/radar_front_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_sne-r/camera_params/front_12mm_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_sne-r/camera_params/front_6mm_extrinsics.yaml
modules/calibration/data/dev_kit_advanced_sne-r/radar_params/radar_front_extrinsics.yaml
modules/calibration/data/dev_kit_standard/camera_params/front_12mm_extrinsics.yaml
modules/calibration/data/dev_kit_standard/camera_params/front_6mm_extrinsics.yaml
modules/calibration/data/dev_kit_standard/radar_params/radar_front_extrinsics.yaml

correct camera & radar frame_id

D-KIT: correct camera & radar frame_id

---

docker/build/installers/install_opencv.sh

to workaround timeout issue of face_landmark_model.dat
See https://github.com/opencv/opencv/issues/10825

Docker: use local cached model data for opencv_contrib

---

docs/D-kit/Camera_Based_Auto_Driving/perception_configuration_cn.md
docs/D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md
docs/D-kit/Camera_Based_Auto_Driving/start_auto_driving_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/perception_configuration_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/sensor_integration_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/start_auto_driving_cn.md

modify docs do adjust multiple vehicle types

D-KIT: modify docs do adjust multiple vehicle types

---

docs/D-kit/Camera_Based_Auto_Driving/perception_configuration_cn.md
docs/D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md
docs/D-kit/Camera_Based_Auto_Driving/start_auto_driving_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/perception_configuration_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/sensor_integration_cn.md
docs/D-kit/Lidar_Based_Auto_Driving/start_auto_driving_cn.md

modify docs do adjust multiple vehicle types

D-KIT: modify docs do adjust multiple vehicle types (#13457)

---

modules/calibration/data/dev_kit/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_ne-b/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_sne-r/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_standard/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/dreamview/conf/vehicle_data.pb.txt

add lidar_to_gnss_preprocess_table.pb.txt to dreamview_conf

D-KIT add lidar_to_gnss_preprocess_table.pb.txt to dreamview_conf

---

modules/calibration/data/dev_kit/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_ne-b/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_sne-r/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_standard/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/dreamview/conf/vehicle_data.pb.txt

add lidar_to_gnss_preprocess_table.pb.txt to dreamview_conf

D-KIT add lidar_to_gnss_preprocess_table.pb.txt to dreamview_conf 

---

modules/calibration/data/dev_kit/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_ne-b/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_advanced_sne-r/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt
modules/calibration/data/dev_kit_standard/dreamview_conf/lidar_to_gnss_preprocess_table.pb.txt

add lidar_to_gnss_preprocess_table.pb.txt to dreamview_conf

 D-KIT add lidar_to_gnss_preprocess_table.pb.txt to dreamview_conf

---

modules/perception/camera/lib/traffic_light/detector/detection/detection.cc

Bug fix: when HDmap inputs multi traffic lights at the same frame, it will cause crash, because so far traffic light detection model only supports batch size=1. Implementation of multi traffic light inference leaves to the future.

Perception: temporarily inference serially for multi traffic lights

---

docs/D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md

modify Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md

D-KIT: modify Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md

---

docs/D-kit/Waypoint_Following/start_waypoint_following_cn.md
docs/D-kit/Waypoint_Following/vehicle_calibration_online_cn.md

add the vehicle type guide for devkit guide

Docs: add the vehicle type guide for devkit guide

---

docs/D-kit/Waypoint_Following/start_waypoint_following_cn.md
docs/D-kit/Waypoint_Following/vehicle_calibration_online_cn.md

add the vehicle type guide for devkit guide

Docs: add the vehicle type guide for DKIT guide

---

docs/cyber/CyberRT_Docker.md

… framework both on x86_64 and ARM64

Docs: updated CyberRT_Docker.md on how to play with Cyber RT

---

modules/tools/control_info/control_info.py

longitudinal spell mistake, will lead to error in running

Tools: spell mistake

---

modules/drivers/canbus/can_client/BUILD
modules/drivers/canbus/can_client/can_client_factory.cc
modules/drivers/canbus/can_client/can_client_factory_test.cc
modules/monitor/hardware/BUILD
modules/monitor/hardware/esdcan_monitor.cc
tools/platform/build_defs.bzl

Resolve [issue](https://github.com/ApolloAuto/apollo/issues/13527#issue-824601927)

fix(canbus): Resolve the issue with creating ESD_CAN client

---

docker/build/build_docker.sh
docker/build/runtime.x86_64.dockerfile.sample
docker/scripts/dev_start.sh
docker/scripts/runtime_start.sh

and cherry-picked unamed-docker-volume issue fix from Martin @shr-project

Runtime docker: added Runtime Dockerfile sample

---

modules/calibration/data/dev_kit/control_conf.pb.txt
modules/calibration/data/dev_kit/planning_conf/planning.conf
modules/calibration/data/dev_kit/planning_conf/planning_config.pb.txt
modules/control/conf/control_conf.pb.txt
modules/planning/conf/planning.conf

update the param of planning and control

Planning: update the param of planning and control

---

modules/dreamview/conf/hmi_modes/camera-Lidar_sensor_calibration.pb.txt
modules/dreamview/conf/hmi_modes/dev_kit_close_loop.pb.txt
modules/dreamview/conf/hmi_modes/dev_kit_debug.pb.txt

remove video.dag in D-KIT related mode

D-KIT: remove video.dag in D-KIT related mode

---

modules/dreamview/conf/hmi_modes/camera-Lidar_sensor_calibration.pb.txt
modules/dreamview/conf/hmi_modes/dev_kit_close_loop.pb.txt
modules/dreamview/conf/hmi_modes/dev_kit_debug.pb.txt

remove video.dag in D-KIT related mode

D-KIT: remove video.dag in D-KIT related mode (#13556)

---

modules/localization/msf/local_tool/local_visualization/engine/visualization_engine.cc

Localization: limit level to pass security check

Localization: limit level to pass security check

---

modules/drivers/camera/usb_cam.cc

corret camera driver to adjust software trigger

Driver: corret camera driver to adjust software trigger

---

scripts/docker_start_user.sh

Scripts: re-enable buggy core pattern

---

modules/calibration/data/dev_kit/perception_conf/camera/fusion_camera_detection_component.pb.txt
modules/calibration/data/dev_kit_advanced_ne-b/perception_conf/camera/fusion_camera_detection_component.pb.txt
modules/calibration/data/dev_kit_advanced_ne-s/perception_conf/camera/fusion_camera_detection_component.pb.txt
modules/calibration/data/dev_kit_advanced_sne-r/perception_conf/camera/fusion_camera_detection_component.pb.txt
modules/calibration/data/dev_kit_standard/perception_conf/camera/fusion_camera_detection_component.pb.txt

D-KIT: correct lidar_type parameter

---

scripts/apollo_base.sh

Before:
```bash
$ bootstrap.sh 
nohup: appending output to 'nohup.out'
nohup: failed to run command 'cyber_launch': No such file or directory
Could not launch module monitor. Is it already built?
nohup: appending output to 'nohup.out'
nohup: failed to run command 'cyber_launch': No such file or directory
Could not launch module dreamview. Is it already built?
```
After: 
```bash
$ bootstrap.sh 
[ERROR] Could not launch module monitor. Is it already built?
[ERROR] Could not launch module dreamview. Is it already built?
```

Scripts: add pretty output in apollo_base.sh

---

modules/tools/sensor_calibration/configuration_yaml_generator.py
modules/tools/sensor_calibration/extract_data.py

FuelClient: bug fix

---

docs/cyber/CyberRT_Quick_Start.md
docs/cyber/CyberRT_Quick_Start_cn.md

Docs: bugfix for sample DAG file

---

docker/build/installers/install_opencv.sh

Docker: update opencv installer to fix msf_visualizer startup issue

---

modules/tools/record_play/rtk_player.py
modules/tools/record_play/rtk_recorder.py

Tools: modify the curvature and trajectory type in rtk recorder and player scripts

Tools: modify the rtk recorder and player scripts

---

modules/dreamview/backend/sim_control/sim_control.cc
modules/dreamview/backend/sim_control/sim_control.h
modules/dreamview/backend/sim_control/sim_control_interface.h

InitStartPoint() can handle  using localization point and using dummy point.if localization is not empty, program will jump here.

dreamview: fix bug at sim control

---

modules/perception/common/perception_gflags.cc
modules/perception/common/perception_gflags.h
modules/perception/onboard/component/fusion_camera_detection_component.cc
modules/perception/onboard/component/fusion_camera_detection_component.h
modules/perception/onboard/component/lane_detection_component.cc
modules/perception/onboard/proto/fusion_camera_detection_component.proto

add gflag to make lidar height file could be specified

Perception: add gflag to make lidar height file could be specified

---

modules/perception/common/perception_gflags.cc
modules/perception/common/perception_gflags.h
modules/perception/onboard/component/fusion_camera_detection_component.cc
modules/perception/onboard/component/fusion_camera_detection_component.h
modules/perception/onboard/component/lane_detection_component.cc
modules/perception/onboard/proto/fusion_camera_detection_component.proto

add gflag to make lidar height could be specified

perception: add gflag to make lidar height could be specified

---

modules/tools/record_play/rtk_recorder.py

Reverts ApolloAuto/apollo#13819

Revert "Tools: fix the typo in rtk recorder"

---

modules/perception/onboard/transform_wrapper/transform_wrapper.cc

make camera perception tf adjust soft trigger

perception: correct camera perception tf to adjust soft trigger

---

modules/localization/msf/msf_localization.cc

Correct the indent of the source code.

Style: Correct the code style.

---

modules/dreamview/conf/vehicle_data.pb.txt

correct novatel_localization_extrinsics.yaml config

DreamView: correct novatel_localization_extrinsics.yaml config

---

modules/drivers/lidar/velodyne/driver/driver.cc

fix a bug: base_time couldn't update on the hour

Velodyne: fix a bug: base_time couldn't update on the hour

---

modules/drivers/lidar/velodyne/driver/driver.cc

fix a bug: base_time couldn't update on the hour

Velodyne: fix a bug: base_time couldn't update on the hour (#13920)

---

modules/prediction/evaluator/vehicle/jointly_prediction_planning_evaluator.cc
modules/prediction/evaluator/vehicle/jointly_prediction_planning_evaluator.h

Prediction: modified jointly evaluator to prevent core dump when adc-traj point num is less than 1
Change-Id: Ib27016f580b92d035e9628b65b66ab83f584d367

Prediction: modified jointly evaluator to prevent core dump

---

docs/D-kit/Waypoint_Following/apollo_installation_cn.md

D-Kit : Modify the docs/D-kit/Waypoint_Following/apollo_installation_cn.md file for branch v6.0_edu

D-Kit : Modify the docs/D-kit/Waypoint_Following/apollo_installation_cn.md file for branch v6.0_edu

---

docs/specs/D-kit/Lidar_Based_Auto_Driving/Virtual_Lane_Generation_cn.md

fix a broken link in Virtual_Lane_Generation_cn.md

D-KIT: fix a broken link in Virtual_Lane_Generation_cn.md

---

modules/canbus/vehicle/lincoln/protocol/wheelspeed_6a.cc
modules/canbus/vehicle/lincoln/protocol/wheelspeed_6a.h

Fix the lincoln mkz wheel speed and wheel direction protocol bug

Canbus: fix the lincoln mkz wheel speed protocol bug

---

modules/control/conf/control.conf
modules/control/conf/control_conf.pb.txt

modify control conf

---

modules/planning/scenarios/dead_end/deadend_turnaround/deadend_turnaround_scenario.cc
modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_provider.cc
modules/planning/tasks/optimizers/open_space_trajectory_partition/open_space_trajectory_partition.cc
modules/task_manager/dead_end_routing_manager.cc

Change-Id: If3ef3f2011fcf47b4ef26c847e65f24df8e3b114

Lint: fix some lint bug

---

modules/dreamview/backend/map/map_service.cc

fix routing start point failed at roadside

Dreamview: fix map service bug

---

modules/planning/conf/scenario/traffic_light_unprotected_left_turn_config.pb.txt
modules/planning/scenarios/common/stage_intersection_cruise_impl.cc
modules/planning/scenarios/traffic_light/unprotected_left_turn/stage_approach.cc

Change-Id: If37b2f000889393553800507bf604c381cb846f3

Planning: fix left turn with multi stop line

---

modules/planning/conf/planning_config.pb.txt

at the middle of lane borrowing, adc will get into self_lane

Planning: fix bug in lane borrow

---

modules/planning/open_space/coarse_trajectory_generator/reeds_shepp_path.cc

Planning: fix bug in reeds shepp

---

modules/planning/scenarios/scenario_manager.cc

Planning always use traffic light unprotected scenario in turn left lane

Planning:fix traffic light scenarion selection bug

---

modules/drivers/lidar/velodyne/compensator/compensator.cc

[velodyne driver]delete unnessary log info

---

modules/drivers/lidar/velodyne/compensator/compensator.cc

[velodyne driver]delete unnessary log info (#14321)

---

modules/control/control_component.cc

Change-Id: Iba8e32ef5d0fc5f8dddfe4c2add6bf3a4aa4d01b

fix(control):enable CheckTimestamp

---

scripts/apollo_build.sh

Change-Id: Ic3d7353935be1df50839a1bdfd5f598acb904230

improve bazel distdir

---

modules/planning/common/reference_line_info.cc
modules/planning/common/reference_line_info.h
modules/planning/common/util/util.cc
modules/planning/common/util/util.h
modules/planning/scenarios/common/stage_intersection_cruise_impl.cc

Change-Id: I5155b263c9bd7bb61e950ec41664ce1b555dafc8

use junction instead of pnc_junction

---

modules/planning/conf/planning.conf

Change-Id: Icdd800604ebb2465b2b533d99c7615f2a4ac29ad

fix open space param

---

modules/planning/planning_component.cc

Change-Id: I7bf54b0388786cd9feca4d28ecbfa2e0b4018cdf

Planning: Make trajectoy smoother between frames

---

modules/planning/common/speed_profile_generator.cc

Change-Id: Ie148ec6f5c5aabb03ba93a30b934f5e721a94655

Somtimes fallback will generate unreliable trajectory if using reference

---

modules/perception/README_paddle3D_CN.md

[Perception] add paddle3d introduction

---

modules/perception/README_paddle3D_CN.md

[Perception] modify README_paddle3D_CN.md

---

modules/perception/inference/migraphx/plugins/plugin.h
modules/perception/onboard/component/lidar_tracking_component.cc
modules/perception/onboard/component/lidar_tracking_component.h

fix ci pipeline and lint code.

fix: fix lint issue

---

tools/apollo_package.bzl

fix a typo in apollo_package.bzl

fix: fix a typo in apollo_package.bzl

---

modules/dreamview_plus/README.md

fix: dreamview_plus documentation

---

modules/planning/planning_base/open_space/coarse_trajectory_generator/reeds_shepp_path.cc

del redundant add for cost in "ShortestRSP"

fix(planning): del redundant add for cost

---

modules/drivers/gnss/conf/gnss_conf.pb.txt
modules/drivers/gnss/parser/enbroad_parser/enbroad_messages.h
modules/drivers/gnss/parser/enbroad_parser/enbroad_parser.cc
modules/drivers/gnss/parser/parser.h
modules/drivers/gnss/proto/config.proto

路测通过，并在z客户apollo上使用。具体详细说明，参考《亿波达组合惯导接入Apollol设计方案》

road test pass. modify Enbroad gnss driver  code and improve compatibility and restore gnss_conf.pb.txt

---

docs/02_Quick Start/apollo_6_0_quick_start_cn.md

Fix broken link (Apollo 3.5 硬件与系统安装指南)
修复损坏的404链接

Fix apollo_6_0_quick_start_cn.md link
